// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `AFPDIFAPAEA.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:AFPDIFAPAEA)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AFPDIFAPAEA {
    // message fields
    // @@protoc_insertion_point(field:AFPDIFAPAEA.queue_position)
    pub queue_position: u32,
    // message oneof groups
    pub FGLIODAJFML: ::std::option::Option<afpdifapaea::FGLIODAJFML>,
    // special fields
    // @@protoc_insertion_point(special_field:AFPDIFAPAEA.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AFPDIFAPAEA {
    fn default() -> &'a AFPDIFAPAEA {
        <AFPDIFAPAEA as ::protobuf::Message>::default_instance()
    }
}

impl AFPDIFAPAEA {
    pub fn new() -> AFPDIFAPAEA {
        ::std::default::Default::default()
    }

    // .LAPOAFHDNCM MFFCPLBNHCF = 1465;

    pub fn MFFCPLBNHCF(&self) -> &super::LAPOAFHDNCM::LAPOAFHDNCM {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(ref v)) => v,
            _ => <super::LAPOAFHDNCM::LAPOAFHDNCM as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_MFFCPLBNHCF(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_MFFCPLBNHCF(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_MFFCPLBNHCF(&mut self, v: super::LAPOAFHDNCM::LAPOAFHDNCM) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_MFFCPLBNHCF(&mut self) -> &mut super::LAPOAFHDNCM::LAPOAFHDNCM {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(super::LAPOAFHDNCM::LAPOAFHDNCM::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_MFFCPLBNHCF(&mut self) -> super::LAPOAFHDNCM::LAPOAFHDNCM {
        if self.has_MFFCPLBNHCF() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::LAPOAFHDNCM::LAPOAFHDNCM::new()
        }
    }

    // .EPLJJNHCJIF DCPHLHNLNKF = 1796;

    pub fn DCPHLHNLNKF(&self) -> &super::EPLJJNHCJIF::EPLJJNHCJIF {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(ref v)) => v,
            _ => <super::EPLJJNHCJIF::EPLJJNHCJIF as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_DCPHLHNLNKF(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_DCPHLHNLNKF(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_DCPHLHNLNKF(&mut self, v: super::EPLJJNHCJIF::EPLJJNHCJIF) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_DCPHLHNLNKF(&mut self) -> &mut super::EPLJJNHCJIF::EPLJJNHCJIF {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(super::EPLJJNHCJIF::EPLJJNHCJIF::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_DCPHLHNLNKF(&mut self) -> super::EPLJJNHCJIF::EPLJJNHCJIF {
        if self.has_DCPHLHNLNKF() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::EPLJJNHCJIF::EPLJJNHCJIF::new()
        }
    }

    // .CJPOMFIDLOA IBCHMBNIPLK = 1996;

    pub fn IBCHMBNIPLK(&self) -> &super::CJPOMFIDLOA::CJPOMFIDLOA {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(ref v)) => v,
            _ => <super::CJPOMFIDLOA::CJPOMFIDLOA as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_IBCHMBNIPLK(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_IBCHMBNIPLK(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_IBCHMBNIPLK(&mut self, v: super::CJPOMFIDLOA::CJPOMFIDLOA) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(v))
    }

    // Mutable pointer to the field.
    pub fn mut_IBCHMBNIPLK(&mut self) -> &mut super::CJPOMFIDLOA::CJPOMFIDLOA {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(super::CJPOMFIDLOA::CJPOMFIDLOA::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_IBCHMBNIPLK(&mut self) -> super::CJPOMFIDLOA::CJPOMFIDLOA {
        if self.has_IBCHMBNIPLK() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(v)) => v,
                _ => panic!(),
            }
        } else {
            super::CJPOMFIDLOA::CJPOMFIDLOA::new()
        }
    }

    // .GIOLAAKLDED DAJDBBEPMMA = 1960;

    pub fn DAJDBBEPMMA(&self) -> &super::GIOLAAKLDED::GIOLAAKLDED {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(ref v)) => v,
            _ => <super::GIOLAAKLDED::GIOLAAKLDED as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_DAJDBBEPMMA(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_DAJDBBEPMMA(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_DAJDBBEPMMA(&mut self, v: super::GIOLAAKLDED::GIOLAAKLDED) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(v))
    }

    // Mutable pointer to the field.
    pub fn mut_DAJDBBEPMMA(&mut self) -> &mut super::GIOLAAKLDED::GIOLAAKLDED {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(super::GIOLAAKLDED::GIOLAAKLDED::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_DAJDBBEPMMA(&mut self) -> super::GIOLAAKLDED::GIOLAAKLDED {
        if self.has_DAJDBBEPMMA() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(v)) => v,
                _ => panic!(),
            }
        } else {
            super::GIOLAAKLDED::GIOLAAKLDED::new()
        }
    }

    // .GKLDOELMEIN PKHJLKNGCGH = 1315;

    pub fn PKHJLKNGCGH(&self) -> &super::GKLDOELMEIN::GKLDOELMEIN {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(ref v)) => v,
            _ => <super::GKLDOELMEIN::GKLDOELMEIN as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_PKHJLKNGCGH(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_PKHJLKNGCGH(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_PKHJLKNGCGH(&mut self, v: super::GKLDOELMEIN::GKLDOELMEIN) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(v))
    }

    // Mutable pointer to the field.
    pub fn mut_PKHJLKNGCGH(&mut self) -> &mut super::GKLDOELMEIN::GKLDOELMEIN {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(super::GKLDOELMEIN::GKLDOELMEIN::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_PKHJLKNGCGH(&mut self) -> super::GKLDOELMEIN::GKLDOELMEIN {
        if self.has_PKHJLKNGCGH() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(v)) => v,
                _ => panic!(),
            }
        } else {
            super::GKLDOELMEIN::GKLDOELMEIN::new()
        }
    }

    // .OHAINOHGKCM BAKAKODKECM = 1553;

    pub fn BAKAKODKECM(&self) -> &super::OHAINOHGKCM::OHAINOHGKCM {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::BAKAKODKECM(ref v)) => v,
            _ => <super::OHAINOHGKCM::OHAINOHGKCM as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_BAKAKODKECM(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_BAKAKODKECM(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::BAKAKODKECM(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_BAKAKODKECM(&mut self, v: super::OHAINOHGKCM::OHAINOHGKCM) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::BAKAKODKECM(v))
    }

    // Mutable pointer to the field.
    pub fn mut_BAKAKODKECM(&mut self) -> &mut super::OHAINOHGKCM::OHAINOHGKCM {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::BAKAKODKECM(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::BAKAKODKECM(super::OHAINOHGKCM::OHAINOHGKCM::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::BAKAKODKECM(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_BAKAKODKECM(&mut self) -> super::OHAINOHGKCM::OHAINOHGKCM {
        if self.has_BAKAKODKECM() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::BAKAKODKECM(v)) => v,
                _ => panic!(),
            }
        } else {
            super::OHAINOHGKCM::OHAINOHGKCM::new()
        }
    }

    // .NIDJPBLNDLH JLPOPEAJHMF = 272;

    pub fn JLPOPEAJHMF(&self) -> &super::NIDJPBLNDLH::NIDJPBLNDLH {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(ref v)) => v,
            _ => <super::NIDJPBLNDLH::NIDJPBLNDLH as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_JLPOPEAJHMF(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_JLPOPEAJHMF(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_JLPOPEAJHMF(&mut self, v: super::NIDJPBLNDLH::NIDJPBLNDLH) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_JLPOPEAJHMF(&mut self) -> &mut super::NIDJPBLNDLH::NIDJPBLNDLH {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(super::NIDJPBLNDLH::NIDJPBLNDLH::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_JLPOPEAJHMF(&mut self) -> super::NIDJPBLNDLH::NIDJPBLNDLH {
        if self.has_JLPOPEAJHMF() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::NIDJPBLNDLH::NIDJPBLNDLH::new()
        }
    }

    // .NNFPCAPDENH KEBDKGKEJDD = 2009;

    pub fn KEBDKGKEJDD(&self) -> &super::NNFPCAPDENH::NNFPCAPDENH {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(ref v)) => v,
            _ => <super::NNFPCAPDENH::NNFPCAPDENH as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_KEBDKGKEJDD(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_KEBDKGKEJDD(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_KEBDKGKEJDD(&mut self, v: super::NNFPCAPDENH::NNFPCAPDENH) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(v))
    }

    // Mutable pointer to the field.
    pub fn mut_KEBDKGKEJDD(&mut self) -> &mut super::NNFPCAPDENH::NNFPCAPDENH {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(super::NNFPCAPDENH::NNFPCAPDENH::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_KEBDKGKEJDD(&mut self) -> super::NNFPCAPDENH::NNFPCAPDENH {
        if self.has_KEBDKGKEJDD() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(v)) => v,
                _ => panic!(),
            }
        } else {
            super::NNFPCAPDENH::NNFPCAPDENH::new()
        }
    }

    // .AJDFPFHBFJM NNDGEJFLGGF = 446;

    pub fn NNDGEJFLGGF(&self) -> &super::AJDFPFHBFJM::AJDFPFHBFJM {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(ref v)) => v,
            _ => <super::AJDFPFHBFJM::AJDFPFHBFJM as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_NNDGEJFLGGF(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_NNDGEJFLGGF(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_NNDGEJFLGGF(&mut self, v: super::AJDFPFHBFJM::AJDFPFHBFJM) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_NNDGEJFLGGF(&mut self) -> &mut super::AJDFPFHBFJM::AJDFPFHBFJM {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(super::AJDFPFHBFJM::AJDFPFHBFJM::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_NNDGEJFLGGF(&mut self) -> super::AJDFPFHBFJM::AJDFPFHBFJM {
        if self.has_NNDGEJFLGGF() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::AJDFPFHBFJM::AJDFPFHBFJM::new()
        }
    }

    // .NEMAKFJPGDF LGNPHHBGKFH = 149;

    pub fn LGNPHHBGKFH(&self) -> &super::NEMAKFJPGDF::NEMAKFJPGDF {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(ref v)) => v,
            _ => <super::NEMAKFJPGDF::NEMAKFJPGDF as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_LGNPHHBGKFH(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_LGNPHHBGKFH(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_LGNPHHBGKFH(&mut self, v: super::NEMAKFJPGDF::NEMAKFJPGDF) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(v))
    }

    // Mutable pointer to the field.
    pub fn mut_LGNPHHBGKFH(&mut self) -> &mut super::NEMAKFJPGDF::NEMAKFJPGDF {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(super::NEMAKFJPGDF::NEMAKFJPGDF::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_LGNPHHBGKFH(&mut self) -> super::NEMAKFJPGDF::NEMAKFJPGDF {
        if self.has_LGNPHHBGKFH() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(v)) => v,
                _ => panic!(),
            }
        } else {
            super::NEMAKFJPGDF::NEMAKFJPGDF::new()
        }
    }

    // .HMNMJKCHABE FIKAGBAEOAP = 1256;

    pub fn FIKAGBAEOAP(&self) -> &super::HMNMJKCHABE::HMNMJKCHABE {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(ref v)) => v,
            _ => <super::HMNMJKCHABE::HMNMJKCHABE as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_FIKAGBAEOAP(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_FIKAGBAEOAP(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_FIKAGBAEOAP(&mut self, v: super::HMNMJKCHABE::HMNMJKCHABE) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(v))
    }

    // Mutable pointer to the field.
    pub fn mut_FIKAGBAEOAP(&mut self) -> &mut super::HMNMJKCHABE::HMNMJKCHABE {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(super::HMNMJKCHABE::HMNMJKCHABE::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_FIKAGBAEOAP(&mut self) -> super::HMNMJKCHABE::HMNMJKCHABE {
        if self.has_FIKAGBAEOAP() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(v)) => v,
                _ => panic!(),
            }
        } else {
            super::HMNMJKCHABE::HMNMJKCHABE::new()
        }
    }

    // .DFMGEJCCBPD IACBCOBMGJB = 744;

    pub fn IACBCOBMGJB(&self) -> &super::DFMGEJCCBPD::DFMGEJCCBPD {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IACBCOBMGJB(ref v)) => v,
            _ => <super::DFMGEJCCBPD::DFMGEJCCBPD as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_IACBCOBMGJB(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_IACBCOBMGJB(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IACBCOBMGJB(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_IACBCOBMGJB(&mut self, v: super::DFMGEJCCBPD::DFMGEJCCBPD) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IACBCOBMGJB(v))
    }

    // Mutable pointer to the field.
    pub fn mut_IACBCOBMGJB(&mut self) -> &mut super::DFMGEJCCBPD::DFMGEJCCBPD {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IACBCOBMGJB(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IACBCOBMGJB(super::DFMGEJCCBPD::DFMGEJCCBPD::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IACBCOBMGJB(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_IACBCOBMGJB(&mut self) -> super::DFMGEJCCBPD::DFMGEJCCBPD {
        if self.has_IACBCOBMGJB() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IACBCOBMGJB(v)) => v,
                _ => panic!(),
            }
        } else {
            super::DFMGEJCCBPD::DFMGEJCCBPD::new()
        }
    }

    // .PDKGKIDCBKA HOKCPPPLJIO = 1742;

    pub fn HOKCPPPLJIO(&self) -> &super::PDKGKIDCBKA::PDKGKIDCBKA {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(ref v)) => v,
            _ => <super::PDKGKIDCBKA::PDKGKIDCBKA as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_HOKCPPPLJIO(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_HOKCPPPLJIO(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_HOKCPPPLJIO(&mut self, v: super::PDKGKIDCBKA::PDKGKIDCBKA) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(v))
    }

    // Mutable pointer to the field.
    pub fn mut_HOKCPPPLJIO(&mut self) -> &mut super::PDKGKIDCBKA::PDKGKIDCBKA {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(super::PDKGKIDCBKA::PDKGKIDCBKA::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_HOKCPPPLJIO(&mut self) -> super::PDKGKIDCBKA::PDKGKIDCBKA {
        if self.has_HOKCPPPLJIO() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(v)) => v,
                _ => panic!(),
            }
        } else {
            super::PDKGKIDCBKA::PDKGKIDCBKA::new()
        }
    }

    // .DGILDLDMGEI EMMPHLKJAJN = 549;

    pub fn EMMPHLKJAJN(&self) -> &super::DGILDLDMGEI::DGILDLDMGEI {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(ref v)) => v,
            _ => <super::DGILDLDMGEI::DGILDLDMGEI as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_EMMPHLKJAJN(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_EMMPHLKJAJN(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_EMMPHLKJAJN(&mut self, v: super::DGILDLDMGEI::DGILDLDMGEI) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(v))
    }

    // Mutable pointer to the field.
    pub fn mut_EMMPHLKJAJN(&mut self) -> &mut super::DGILDLDMGEI::DGILDLDMGEI {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(super::DGILDLDMGEI::DGILDLDMGEI::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_EMMPHLKJAJN(&mut self) -> super::DGILDLDMGEI::DGILDLDMGEI {
        if self.has_EMMPHLKJAJN() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(v)) => v,
                _ => panic!(),
            }
        } else {
            super::DGILDLDMGEI::DGILDLDMGEI::new()
        }
    }

    // .PCCGPNAFMHP HHNPEHMBDKD = 1037;

    pub fn HHNPEHMBDKD(&self) -> &super::PCCGPNAFMHP::PCCGPNAFMHP {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(ref v)) => v,
            _ => <super::PCCGPNAFMHP::PCCGPNAFMHP as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_HHNPEHMBDKD(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_HHNPEHMBDKD(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_HHNPEHMBDKD(&mut self, v: super::PCCGPNAFMHP::PCCGPNAFMHP) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(v))
    }

    // Mutable pointer to the field.
    pub fn mut_HHNPEHMBDKD(&mut self) -> &mut super::PCCGPNAFMHP::PCCGPNAFMHP {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(super::PCCGPNAFMHP::PCCGPNAFMHP::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_HHNPEHMBDKD(&mut self) -> super::PCCGPNAFMHP::PCCGPNAFMHP {
        if self.has_HHNPEHMBDKD() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(v)) => v,
                _ => panic!(),
            }
        } else {
            super::PCCGPNAFMHP::PCCGPNAFMHP::new()
        }
    }

    // .LFONAPFHAOB HHNHGJMOGDD = 1216;

    pub fn HHNHGJMOGDD(&self) -> &super::LFONAPFHAOB::LFONAPFHAOB {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(ref v)) => v,
            _ => <super::LFONAPFHAOB::LFONAPFHAOB as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_HHNHGJMOGDD(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_HHNHGJMOGDD(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_HHNHGJMOGDD(&mut self, v: super::LFONAPFHAOB::LFONAPFHAOB) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(v))
    }

    // Mutable pointer to the field.
    pub fn mut_HHNHGJMOGDD(&mut self) -> &mut super::LFONAPFHAOB::LFONAPFHAOB {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(super::LFONAPFHAOB::LFONAPFHAOB::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_HHNHGJMOGDD(&mut self) -> super::LFONAPFHAOB::LFONAPFHAOB {
        if self.has_HHNHGJMOGDD() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(v)) => v,
                _ => panic!(),
            }
        } else {
            super::LFONAPFHAOB::LFONAPFHAOB::new()
        }
    }

    // .FNNFHNKHIDD CFDIPFKBFJB = 1464;

    pub fn CFDIPFKBFJB(&self) -> &super::FNNFHNKHIDD::FNNFHNKHIDD {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(ref v)) => v,
            _ => <super::FNNFHNKHIDD::FNNFHNKHIDD as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_CFDIPFKBFJB(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_CFDIPFKBFJB(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_CFDIPFKBFJB(&mut self, v: super::FNNFHNKHIDD::FNNFHNKHIDD) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(v))
    }

    // Mutable pointer to the field.
    pub fn mut_CFDIPFKBFJB(&mut self) -> &mut super::FNNFHNKHIDD::FNNFHNKHIDD {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(super::FNNFHNKHIDD::FNNFHNKHIDD::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_CFDIPFKBFJB(&mut self) -> super::FNNFHNKHIDD::FNNFHNKHIDD {
        if self.has_CFDIPFKBFJB() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(v)) => v,
                _ => panic!(),
            }
        } else {
            super::FNNFHNKHIDD::FNNFHNKHIDD::new()
        }
    }

    // .IDOJADMFGKF NFBJINKLLLK = 681;

    pub fn NFBJINKLLLK(&self) -> &super::IDOJADMFGKF::IDOJADMFGKF {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NFBJINKLLLK(ref v)) => v,
            _ => <super::IDOJADMFGKF::IDOJADMFGKF as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_NFBJINKLLLK(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_NFBJINKLLLK(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NFBJINKLLLK(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_NFBJINKLLLK(&mut self, v: super::IDOJADMFGKF::IDOJADMFGKF) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NFBJINKLLLK(v))
    }

    // Mutable pointer to the field.
    pub fn mut_NFBJINKLLLK(&mut self) -> &mut super::IDOJADMFGKF::IDOJADMFGKF {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NFBJINKLLLK(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NFBJINKLLLK(super::IDOJADMFGKF::IDOJADMFGKF::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NFBJINKLLLK(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_NFBJINKLLLK(&mut self) -> super::IDOJADMFGKF::IDOJADMFGKF {
        if self.has_NFBJINKLLLK() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NFBJINKLLLK(v)) => v,
                _ => panic!(),
            }
        } else {
            super::IDOJADMFGKF::IDOJADMFGKF::new()
        }
    }

    // .EJEFKJGAKOO LAJGNNBOLDG = 334;

    pub fn LAJGNNBOLDG(&self) -> &super::EJEFKJGAKOO::EJEFKJGAKOO {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(ref v)) => v,
            _ => <super::EJEFKJGAKOO::EJEFKJGAKOO as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_LAJGNNBOLDG(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_LAJGNNBOLDG(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_LAJGNNBOLDG(&mut self, v: super::EJEFKJGAKOO::EJEFKJGAKOO) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(v))
    }

    // Mutable pointer to the field.
    pub fn mut_LAJGNNBOLDG(&mut self) -> &mut super::EJEFKJGAKOO::EJEFKJGAKOO {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(super::EJEFKJGAKOO::EJEFKJGAKOO::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_LAJGNNBOLDG(&mut self) -> super::EJEFKJGAKOO::EJEFKJGAKOO {
        if self.has_LAJGNNBOLDG() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(v)) => v,
                _ => panic!(),
            }
        } else {
            super::EJEFKJGAKOO::EJEFKJGAKOO::new()
        }
    }

    // .FKILNIGOKBF LFIDNOAECMN = 54;

    pub fn LFIDNOAECMN(&self) -> &super::FKILNIGOKBF::FKILNIGOKBF {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LFIDNOAECMN(ref v)) => v,
            _ => <super::FKILNIGOKBF::FKILNIGOKBF as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_LFIDNOAECMN(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_LFIDNOAECMN(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LFIDNOAECMN(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_LFIDNOAECMN(&mut self, v: super::FKILNIGOKBF::FKILNIGOKBF) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LFIDNOAECMN(v))
    }

    // Mutable pointer to the field.
    pub fn mut_LFIDNOAECMN(&mut self) -> &mut super::FKILNIGOKBF::FKILNIGOKBF {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LFIDNOAECMN(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LFIDNOAECMN(super::FKILNIGOKBF::FKILNIGOKBF::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LFIDNOAECMN(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_LFIDNOAECMN(&mut self) -> super::FKILNIGOKBF::FKILNIGOKBF {
        if self.has_LFIDNOAECMN() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LFIDNOAECMN(v)) => v,
                _ => panic!(),
            }
        } else {
            super::FKILNIGOKBF::FKILNIGOKBF::new()
        }
    }

    // .KCCPHHGCPMP IOHJGOENAPF = 1337;

    pub fn IOHJGOENAPF(&self) -> &super::KCCPHHGCPMP::KCCPHHGCPMP {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IOHJGOENAPF(ref v)) => v,
            _ => <super::KCCPHHGCPMP::KCCPHHGCPMP as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_IOHJGOENAPF(&mut self) {
        self.FGLIODAJFML = ::std::option::Option::None;
    }

    pub fn has_IOHJGOENAPF(&self) -> bool {
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IOHJGOENAPF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_IOHJGOENAPF(&mut self, v: super::KCCPHHGCPMP::KCCPHHGCPMP) {
        self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IOHJGOENAPF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_IOHJGOENAPF(&mut self) -> &mut super::KCCPHHGCPMP::KCCPHHGCPMP {
        if let ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IOHJGOENAPF(_)) = self.FGLIODAJFML {
        } else {
            self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IOHJGOENAPF(super::KCCPHHGCPMP::KCCPHHGCPMP::new()));
        }
        match self.FGLIODAJFML {
            ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IOHJGOENAPF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_IOHJGOENAPF(&mut self) -> super::KCCPHHGCPMP::KCCPHHGCPMP {
        if self.has_IOHJGOENAPF() {
            match self.FGLIODAJFML.take() {
                ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IOHJGOENAPF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::KCCPHHGCPMP::KCCPHHGCPMP::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(22);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "queue_position",
            |m: &AFPDIFAPAEA| { &m.queue_position },
            |m: &mut AFPDIFAPAEA| { &mut m.queue_position },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::LAPOAFHDNCM::LAPOAFHDNCM>(
            "MFFCPLBNHCF",
            AFPDIFAPAEA::has_MFFCPLBNHCF,
            AFPDIFAPAEA::MFFCPLBNHCF,
            AFPDIFAPAEA::mut_MFFCPLBNHCF,
            AFPDIFAPAEA::set_MFFCPLBNHCF,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::EPLJJNHCJIF::EPLJJNHCJIF>(
            "DCPHLHNLNKF",
            AFPDIFAPAEA::has_DCPHLHNLNKF,
            AFPDIFAPAEA::DCPHLHNLNKF,
            AFPDIFAPAEA::mut_DCPHLHNLNKF,
            AFPDIFAPAEA::set_DCPHLHNLNKF,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::CJPOMFIDLOA::CJPOMFIDLOA>(
            "IBCHMBNIPLK",
            AFPDIFAPAEA::has_IBCHMBNIPLK,
            AFPDIFAPAEA::IBCHMBNIPLK,
            AFPDIFAPAEA::mut_IBCHMBNIPLK,
            AFPDIFAPAEA::set_IBCHMBNIPLK,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::GIOLAAKLDED::GIOLAAKLDED>(
            "DAJDBBEPMMA",
            AFPDIFAPAEA::has_DAJDBBEPMMA,
            AFPDIFAPAEA::DAJDBBEPMMA,
            AFPDIFAPAEA::mut_DAJDBBEPMMA,
            AFPDIFAPAEA::set_DAJDBBEPMMA,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::GKLDOELMEIN::GKLDOELMEIN>(
            "PKHJLKNGCGH",
            AFPDIFAPAEA::has_PKHJLKNGCGH,
            AFPDIFAPAEA::PKHJLKNGCGH,
            AFPDIFAPAEA::mut_PKHJLKNGCGH,
            AFPDIFAPAEA::set_PKHJLKNGCGH,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::OHAINOHGKCM::OHAINOHGKCM>(
            "BAKAKODKECM",
            AFPDIFAPAEA::has_BAKAKODKECM,
            AFPDIFAPAEA::BAKAKODKECM,
            AFPDIFAPAEA::mut_BAKAKODKECM,
            AFPDIFAPAEA::set_BAKAKODKECM,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::NIDJPBLNDLH::NIDJPBLNDLH>(
            "JLPOPEAJHMF",
            AFPDIFAPAEA::has_JLPOPEAJHMF,
            AFPDIFAPAEA::JLPOPEAJHMF,
            AFPDIFAPAEA::mut_JLPOPEAJHMF,
            AFPDIFAPAEA::set_JLPOPEAJHMF,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::NNFPCAPDENH::NNFPCAPDENH>(
            "KEBDKGKEJDD",
            AFPDIFAPAEA::has_KEBDKGKEJDD,
            AFPDIFAPAEA::KEBDKGKEJDD,
            AFPDIFAPAEA::mut_KEBDKGKEJDD,
            AFPDIFAPAEA::set_KEBDKGKEJDD,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::AJDFPFHBFJM::AJDFPFHBFJM>(
            "NNDGEJFLGGF",
            AFPDIFAPAEA::has_NNDGEJFLGGF,
            AFPDIFAPAEA::NNDGEJFLGGF,
            AFPDIFAPAEA::mut_NNDGEJFLGGF,
            AFPDIFAPAEA::set_NNDGEJFLGGF,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::NEMAKFJPGDF::NEMAKFJPGDF>(
            "LGNPHHBGKFH",
            AFPDIFAPAEA::has_LGNPHHBGKFH,
            AFPDIFAPAEA::LGNPHHBGKFH,
            AFPDIFAPAEA::mut_LGNPHHBGKFH,
            AFPDIFAPAEA::set_LGNPHHBGKFH,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::HMNMJKCHABE::HMNMJKCHABE>(
            "FIKAGBAEOAP",
            AFPDIFAPAEA::has_FIKAGBAEOAP,
            AFPDIFAPAEA::FIKAGBAEOAP,
            AFPDIFAPAEA::mut_FIKAGBAEOAP,
            AFPDIFAPAEA::set_FIKAGBAEOAP,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::DFMGEJCCBPD::DFMGEJCCBPD>(
            "IACBCOBMGJB",
            AFPDIFAPAEA::has_IACBCOBMGJB,
            AFPDIFAPAEA::IACBCOBMGJB,
            AFPDIFAPAEA::mut_IACBCOBMGJB,
            AFPDIFAPAEA::set_IACBCOBMGJB,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::PDKGKIDCBKA::PDKGKIDCBKA>(
            "HOKCPPPLJIO",
            AFPDIFAPAEA::has_HOKCPPPLJIO,
            AFPDIFAPAEA::HOKCPPPLJIO,
            AFPDIFAPAEA::mut_HOKCPPPLJIO,
            AFPDIFAPAEA::set_HOKCPPPLJIO,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::DGILDLDMGEI::DGILDLDMGEI>(
            "EMMPHLKJAJN",
            AFPDIFAPAEA::has_EMMPHLKJAJN,
            AFPDIFAPAEA::EMMPHLKJAJN,
            AFPDIFAPAEA::mut_EMMPHLKJAJN,
            AFPDIFAPAEA::set_EMMPHLKJAJN,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::PCCGPNAFMHP::PCCGPNAFMHP>(
            "HHNPEHMBDKD",
            AFPDIFAPAEA::has_HHNPEHMBDKD,
            AFPDIFAPAEA::HHNPEHMBDKD,
            AFPDIFAPAEA::mut_HHNPEHMBDKD,
            AFPDIFAPAEA::set_HHNPEHMBDKD,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::LFONAPFHAOB::LFONAPFHAOB>(
            "HHNHGJMOGDD",
            AFPDIFAPAEA::has_HHNHGJMOGDD,
            AFPDIFAPAEA::HHNHGJMOGDD,
            AFPDIFAPAEA::mut_HHNHGJMOGDD,
            AFPDIFAPAEA::set_HHNHGJMOGDD,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::FNNFHNKHIDD::FNNFHNKHIDD>(
            "CFDIPFKBFJB",
            AFPDIFAPAEA::has_CFDIPFKBFJB,
            AFPDIFAPAEA::CFDIPFKBFJB,
            AFPDIFAPAEA::mut_CFDIPFKBFJB,
            AFPDIFAPAEA::set_CFDIPFKBFJB,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::IDOJADMFGKF::IDOJADMFGKF>(
            "NFBJINKLLLK",
            AFPDIFAPAEA::has_NFBJINKLLLK,
            AFPDIFAPAEA::NFBJINKLLLK,
            AFPDIFAPAEA::mut_NFBJINKLLLK,
            AFPDIFAPAEA::set_NFBJINKLLLK,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::EJEFKJGAKOO::EJEFKJGAKOO>(
            "LAJGNNBOLDG",
            AFPDIFAPAEA::has_LAJGNNBOLDG,
            AFPDIFAPAEA::LAJGNNBOLDG,
            AFPDIFAPAEA::mut_LAJGNNBOLDG,
            AFPDIFAPAEA::set_LAJGNNBOLDG,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::FKILNIGOKBF::FKILNIGOKBF>(
            "LFIDNOAECMN",
            AFPDIFAPAEA::has_LFIDNOAECMN,
            AFPDIFAPAEA::LFIDNOAECMN,
            AFPDIFAPAEA::mut_LFIDNOAECMN,
            AFPDIFAPAEA::set_LFIDNOAECMN,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::KCCPHHGCPMP::KCCPHHGCPMP>(
            "IOHJGOENAPF",
            AFPDIFAPAEA::has_IOHJGOENAPF,
            AFPDIFAPAEA::IOHJGOENAPF,
            AFPDIFAPAEA::mut_IOHJGOENAPF,
            AFPDIFAPAEA::set_IOHJGOENAPF,
        ));
        oneofs.push(afpdifapaea::FGLIODAJFML::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AFPDIFAPAEA>(
            "AFPDIFAPAEA",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AFPDIFAPAEA {
    const NAME: &'static str = "AFPDIFAPAEA";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                64 => {
                    self.queue_position = is.read_uint32()?;
                },
                11722 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(is.read_message()?));
                },
                14370 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(is.read_message()?));
                },
                15970 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(is.read_message()?));
                },
                15682 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(is.read_message()?));
                },
                10522 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(is.read_message()?));
                },
                12426 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::BAKAKODKECM(is.read_message()?));
                },
                2178 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(is.read_message()?));
                },
                16074 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(is.read_message()?));
                },
                3570 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(is.read_message()?));
                },
                1194 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(is.read_message()?));
                },
                10050 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(is.read_message()?));
                },
                5954 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IACBCOBMGJB(is.read_message()?));
                },
                13938 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(is.read_message()?));
                },
                4394 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(is.read_message()?));
                },
                8298 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(is.read_message()?));
                },
                9730 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(is.read_message()?));
                },
                11714 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(is.read_message()?));
                },
                5450 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::NFBJINKLLLK(is.read_message()?));
                },
                2674 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(is.read_message()?));
                },
                434 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::LFIDNOAECMN(is.read_message()?));
                },
                10698 => {
                    self.FGLIODAJFML = ::std::option::Option::Some(afpdifapaea::FGLIODAJFML::IOHJGOENAPF(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.queue_position != 0 {
            my_size += ::protobuf::rt::uint32_size(8, self.queue_position);
        }
        if let ::std::option::Option::Some(ref v) = self.FGLIODAJFML {
            match v {
                &afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::BAKAKODKECM(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::IACBCOBMGJB(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::NFBJINKLLLK(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::LFIDNOAECMN(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &afpdifapaea::FGLIODAJFML::IOHJGOENAPF(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.queue_position != 0 {
            os.write_uint32(8, self.queue_position)?;
        }
        if let ::std::option::Option::Some(ref v) = self.FGLIODAJFML {
            match v {
                &afpdifapaea::FGLIODAJFML::MFFCPLBNHCF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1465, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::DCPHLHNLNKF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1796, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::IBCHMBNIPLK(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1996, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::DAJDBBEPMMA(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1960, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::PKHJLKNGCGH(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1315, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::BAKAKODKECM(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1553, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::JLPOPEAJHMF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(272, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::KEBDKGKEJDD(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2009, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::NNDGEJFLGGF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(446, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::LGNPHHBGKFH(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(149, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::FIKAGBAEOAP(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1256, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::IACBCOBMGJB(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(744, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::HOKCPPPLJIO(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1742, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::EMMPHLKJAJN(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(549, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::HHNPEHMBDKD(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1037, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::HHNHGJMOGDD(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1216, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::CFDIPFKBFJB(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1464, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::NFBJINKLLLK(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(681, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::LAJGNNBOLDG(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(334, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::LFIDNOAECMN(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(54, v, os)?;
                },
                &afpdifapaea::FGLIODAJFML::IOHJGOENAPF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1337, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AFPDIFAPAEA {
        AFPDIFAPAEA::new()
    }

    fn clear(&mut self) {
        self.queue_position = 0;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.FGLIODAJFML = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AFPDIFAPAEA {
        static instance: AFPDIFAPAEA = AFPDIFAPAEA {
            queue_position: 0,
            FGLIODAJFML: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AFPDIFAPAEA {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AFPDIFAPAEA").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AFPDIFAPAEA {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AFPDIFAPAEA {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `AFPDIFAPAEA`
pub mod afpdifapaea {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:AFPDIFAPAEA.FGLIODAJFML)
    pub enum FGLIODAJFML {
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.MFFCPLBNHCF)
        MFFCPLBNHCF(super::super::LAPOAFHDNCM::LAPOAFHDNCM),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.DCPHLHNLNKF)
        DCPHLHNLNKF(super::super::EPLJJNHCJIF::EPLJJNHCJIF),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.IBCHMBNIPLK)
        IBCHMBNIPLK(super::super::CJPOMFIDLOA::CJPOMFIDLOA),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.DAJDBBEPMMA)
        DAJDBBEPMMA(super::super::GIOLAAKLDED::GIOLAAKLDED),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.PKHJLKNGCGH)
        PKHJLKNGCGH(super::super::GKLDOELMEIN::GKLDOELMEIN),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.BAKAKODKECM)
        BAKAKODKECM(super::super::OHAINOHGKCM::OHAINOHGKCM),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.JLPOPEAJHMF)
        JLPOPEAJHMF(super::super::NIDJPBLNDLH::NIDJPBLNDLH),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.KEBDKGKEJDD)
        KEBDKGKEJDD(super::super::NNFPCAPDENH::NNFPCAPDENH),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.NNDGEJFLGGF)
        NNDGEJFLGGF(super::super::AJDFPFHBFJM::AJDFPFHBFJM),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.LGNPHHBGKFH)
        LGNPHHBGKFH(super::super::NEMAKFJPGDF::NEMAKFJPGDF),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.FIKAGBAEOAP)
        FIKAGBAEOAP(super::super::HMNMJKCHABE::HMNMJKCHABE),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.IACBCOBMGJB)
        IACBCOBMGJB(super::super::DFMGEJCCBPD::DFMGEJCCBPD),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.HOKCPPPLJIO)
        HOKCPPPLJIO(super::super::PDKGKIDCBKA::PDKGKIDCBKA),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.EMMPHLKJAJN)
        EMMPHLKJAJN(super::super::DGILDLDMGEI::DGILDLDMGEI),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.HHNPEHMBDKD)
        HHNPEHMBDKD(super::super::PCCGPNAFMHP::PCCGPNAFMHP),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.HHNHGJMOGDD)
        HHNHGJMOGDD(super::super::LFONAPFHAOB::LFONAPFHAOB),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.CFDIPFKBFJB)
        CFDIPFKBFJB(super::super::FNNFHNKHIDD::FNNFHNKHIDD),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.NFBJINKLLLK)
        NFBJINKLLLK(super::super::IDOJADMFGKF::IDOJADMFGKF),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.LAJGNNBOLDG)
        LAJGNNBOLDG(super::super::EJEFKJGAKOO::EJEFKJGAKOO),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.LFIDNOAECMN)
        LFIDNOAECMN(super::super::FKILNIGOKBF::FKILNIGOKBF),
        // @@protoc_insertion_point(oneof_field:AFPDIFAPAEA.IOHJGOENAPF)
        IOHJGOENAPF(super::super::KCCPHHGCPMP::KCCPHHGCPMP),
    }

    impl ::protobuf::Oneof for FGLIODAJFML {
    }

    impl ::protobuf::OneofFull for FGLIODAJFML {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::AFPDIFAPAEA as ::protobuf::MessageFull>::descriptor().oneof_by_name("FGLIODAJFML").unwrap()).clone()
        }
    }

    impl FGLIODAJFML {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<FGLIODAJFML>("FGLIODAJFML")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11AFPDIFAPAEA.proto\x1a\x11AJDFPFHBFJM.proto\x1a\x11CJPOMFIDLOA.prot\
    o\x1a\x11DFMGEJCCBPD.proto\x1a\x11DGILDLDMGEI.proto\x1a\x11EJEFKJGAKOO.p\
    roto\x1a\x11EPLJJNHCJIF.proto\x1a\x11FKILNIGOKBF.proto\x1a\x11FNNFHNKHID\
    D.proto\x1a\x11GIOLAAKLDED.proto\x1a\x11GKLDOELMEIN.proto\x1a\x11HMNMJKC\
    HABE.proto\x1a\x11IDOJADMFGKF.proto\x1a\x11KCCPHHGCPMP.proto\x1a\x11LAPO\
    AFHDNCM.proto\x1a\x11LFONAPFHAOB.proto\x1a\x11NEMAKFJPGDF.proto\x1a\x11N\
    IDJPBLNDLH.proto\x1a\x11NNFPCAPDENH.proto\x1a\x11OHAINOHGKCM.proto\x1a\
    \x11PCCGPNAFMHP.proto\x1a\x11PDKGKIDCBKA.proto\"\xf1\x08\n\x0bAFPDIFAPAE\
    A\x12%\n\x0equeue_position\x18\x08\x20\x01(\rR\rqueuePosition\x121\n\x0b\
    MFFCPLBNHCF\x18\xb9\x0b\x20\x01(\x0b2\x0c.LAPOAFHDNCMH\0R\x0bMFFCPLBNHCF\
    \x121\n\x0bDCPHLHNLNKF\x18\x84\x0e\x20\x01(\x0b2\x0c.EPLJJNHCJIFH\0R\x0b\
    DCPHLHNLNKF\x121\n\x0bIBCHMBNIPLK\x18\xcc\x0f\x20\x01(\x0b2\x0c.CJPOMFID\
    LOAH\0R\x0bIBCHMBNIPLK\x121\n\x0bDAJDBBEPMMA\x18\xa8\x0f\x20\x01(\x0b2\
    \x0c.GIOLAAKLDEDH\0R\x0bDAJDBBEPMMA\x121\n\x0bPKHJLKNGCGH\x18\xa3\n\x20\
    \x01(\x0b2\x0c.GKLDOELMEINH\0R\x0bPKHJLKNGCGH\x121\n\x0bBAKAKODKECM\x18\
    \x91\x0c\x20\x01(\x0b2\x0c.OHAINOHGKCMH\0R\x0bBAKAKODKECM\x121\n\x0bJLPO\
    PEAJHMF\x18\x90\x02\x20\x01(\x0b2\x0c.NIDJPBLNDLHH\0R\x0bJLPOPEAJHMF\x12\
    1\n\x0bKEBDKGKEJDD\x18\xd9\x0f\x20\x01(\x0b2\x0c.NNFPCAPDENHH\0R\x0bKEBD\
    KGKEJDD\x121\n\x0bNNDGEJFLGGF\x18\xbe\x03\x20\x01(\x0b2\x0c.AJDFPFHBFJMH\
    \0R\x0bNNDGEJFLGGF\x121\n\x0bLGNPHHBGKFH\x18\x95\x01\x20\x01(\x0b2\x0c.N\
    EMAKFJPGDFH\0R\x0bLGNPHHBGKFH\x121\n\x0bFIKAGBAEOAP\x18\xe8\t\x20\x01(\
    \x0b2\x0c.HMNMJKCHABEH\0R\x0bFIKAGBAEOAP\x121\n\x0bIACBCOBMGJB\x18\xe8\
    \x05\x20\x01(\x0b2\x0c.DFMGEJCCBPDH\0R\x0bIACBCOBMGJB\x121\n\x0bHOKCPPPL\
    JIO\x18\xce\r\x20\x01(\x0b2\x0c.PDKGKIDCBKAH\0R\x0bHOKCPPPLJIO\x121\n\
    \x0bEMMPHLKJAJN\x18\xa5\x04\x20\x01(\x0b2\x0c.DGILDLDMGEIH\0R\x0bEMMPHLK\
    JAJN\x121\n\x0bHHNPEHMBDKD\x18\x8d\x08\x20\x01(\x0b2\x0c.PCCGPNAFMHPH\0R\
    \x0bHHNPEHMBDKD\x121\n\x0bHHNHGJMOGDD\x18\xc0\t\x20\x01(\x0b2\x0c.LFONAP\
    FHAOBH\0R\x0bHHNHGJMOGDD\x121\n\x0bCFDIPFKBFJB\x18\xb8\x0b\x20\x01(\x0b2\
    \x0c.FNNFHNKHIDDH\0R\x0bCFDIPFKBFJB\x121\n\x0bNFBJINKLLLK\x18\xa9\x05\
    \x20\x01(\x0b2\x0c.IDOJADMFGKFH\0R\x0bNFBJINKLLLK\x121\n\x0bLAJGNNBOLDG\
    \x18\xce\x02\x20\x01(\x0b2\x0c.EJEFKJGAKOOH\0R\x0bLAJGNNBOLDG\x120\n\x0b\
    LFIDNOAECMN\x186\x20\x01(\x0b2\x0c.FKILNIGOKBFH\0R\x0bLFIDNOAECMN\x121\n\
    \x0bIOHJGOENAPF\x18\xb9\n\x20\x01(\x0b2\x0c.KCCPHHGCPMPH\0R\x0bIOHJGOENA\
    PFB\r\n\x0bFGLIODAJFMLb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(21);
            deps.push(super::AJDFPFHBFJM::file_descriptor().clone());
            deps.push(super::CJPOMFIDLOA::file_descriptor().clone());
            deps.push(super::DFMGEJCCBPD::file_descriptor().clone());
            deps.push(super::DGILDLDMGEI::file_descriptor().clone());
            deps.push(super::EJEFKJGAKOO::file_descriptor().clone());
            deps.push(super::EPLJJNHCJIF::file_descriptor().clone());
            deps.push(super::FKILNIGOKBF::file_descriptor().clone());
            deps.push(super::FNNFHNKHIDD::file_descriptor().clone());
            deps.push(super::GIOLAAKLDED::file_descriptor().clone());
            deps.push(super::GKLDOELMEIN::file_descriptor().clone());
            deps.push(super::HMNMJKCHABE::file_descriptor().clone());
            deps.push(super::IDOJADMFGKF::file_descriptor().clone());
            deps.push(super::KCCPHHGCPMP::file_descriptor().clone());
            deps.push(super::LAPOAFHDNCM::file_descriptor().clone());
            deps.push(super::LFONAPFHAOB::file_descriptor().clone());
            deps.push(super::NEMAKFJPGDF::file_descriptor().clone());
            deps.push(super::NIDJPBLNDLH::file_descriptor().clone());
            deps.push(super::NNFPCAPDENH::file_descriptor().clone());
            deps.push(super::OHAINOHGKCM::file_descriptor().clone());
            deps.push(super::PCCGPNAFMHP::file_descriptor().clone());
            deps.push(super::PDKGKIDCBKA::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(AFPDIFAPAEA::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
