// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CurTierceChallenge.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:CurTierceChallenge)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CurTierceChallenge {
    // message fields
    // @@protoc_insertion_point(field:CurTierceChallenge.lineup_list)
    pub lineup_list: ::std::vec::Vec<super::LineupInfo::LineupInfo>,
    // @@protoc_insertion_point(field:CurTierceChallenge.stage_index)
    pub stage_index: u32,
    // @@protoc_insertion_point(field:CurTierceChallenge.IIHFEDLHOPI)
    pub IIHFEDLHOPI: ::protobuf::MessageField<super::PEOKJEOOOJD::PEOKJEOOOJD>,
    // @@protoc_insertion_point(field:CurTierceChallenge.MPKMIKBFEHG)
    pub MPKMIKBFEHG: bool,
    // @@protoc_insertion_point(field:CurTierceChallenge.challenge_id)
    pub challenge_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:CurTierceChallenge.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CurTierceChallenge {
    fn default() -> &'a CurTierceChallenge {
        <CurTierceChallenge as ::protobuf::Message>::default_instance()
    }
}

impl CurTierceChallenge {
    pub fn new() -> CurTierceChallenge {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "lineup_list",
            |m: &CurTierceChallenge| { &m.lineup_list },
            |m: &mut CurTierceChallenge| { &mut m.lineup_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "stage_index",
            |m: &CurTierceChallenge| { &m.stage_index },
            |m: &mut CurTierceChallenge| { &mut m.stage_index },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::PEOKJEOOOJD::PEOKJEOOOJD>(
            "IIHFEDLHOPI",
            |m: &CurTierceChallenge| { &m.IIHFEDLHOPI },
            |m: &mut CurTierceChallenge| { &mut m.IIHFEDLHOPI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MPKMIKBFEHG",
            |m: &CurTierceChallenge| { &m.MPKMIKBFEHG },
            |m: &mut CurTierceChallenge| { &mut m.MPKMIKBFEHG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "challenge_id",
            |m: &CurTierceChallenge| { &m.challenge_id },
            |m: &mut CurTierceChallenge| { &mut m.challenge_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CurTierceChallenge>(
            "CurTierceChallenge",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CurTierceChallenge {
    const NAME: &'static str = "CurTierceChallenge";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.lineup_list.push(is.read_message()?);
                },
                24 => {
                    self.stage_index = is.read_uint32()?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.IIHFEDLHOPI)?;
                },
                80 => {
                    self.MPKMIKBFEHG = is.read_bool()?;
                },
                104 => {
                    self.challenge_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.lineup_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.stage_index != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.stage_index);
        }
        if let Some(v) = self.IIHFEDLHOPI.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.MPKMIKBFEHG != false {
            my_size += 1 + 1;
        }
        if self.challenge_id != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.challenge_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.lineup_list {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if self.stage_index != 0 {
            os.write_uint32(3, self.stage_index)?;
        }
        if let Some(v) = self.IIHFEDLHOPI.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if self.MPKMIKBFEHG != false {
            os.write_bool(10, self.MPKMIKBFEHG)?;
        }
        if self.challenge_id != 0 {
            os.write_uint32(13, self.challenge_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CurTierceChallenge {
        CurTierceChallenge::new()
    }

    fn clear(&mut self) {
        self.lineup_list.clear();
        self.stage_index = 0;
        self.IIHFEDLHOPI.clear();
        self.MPKMIKBFEHG = false;
        self.challenge_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CurTierceChallenge {
        static instance: CurTierceChallenge = CurTierceChallenge {
            lineup_list: ::std::vec::Vec::new(),
            stage_index: 0,
            IIHFEDLHOPI: ::protobuf::MessageField::none(),
            MPKMIKBFEHG: false,
            challenge_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CurTierceChallenge {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CurTierceChallenge").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CurTierceChallenge {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CurTierceChallenge {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18CurTierceChallenge.proto\x1a\x10LineupInfo.proto\x1a\x11PEOKJEOOOJ\
    D.proto\"\xd8\x01\n\x12CurTierceChallenge\x12,\n\x0blineup_list\x18\x01\
    \x20\x03(\x0b2\x0b.LineupInfoR\nlineupList\x12\x1f\n\x0bstage_index\x18\
    \x03\x20\x01(\rR\nstageIndex\x12.\n\x0bIIHFEDLHOPI\x18\x07\x20\x01(\x0b2\
    \x0c.PEOKJEOOOJDR\x0bIIHFEDLHOPI\x12\x20\n\x0bMPKMIKBFEHG\x18\n\x20\x01(\
    \x08R\x0bMPKMIKBFEHG\x12!\n\x0cchallenge_id\x18\r\x20\x01(\rR\x0bchallen\
    geIdb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::LineupInfo::file_descriptor().clone());
            deps.push(super::PEOKJEOOOJD::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(CurTierceChallenge::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
