// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `FAKGHKIKHAP.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:FAKGHKIKHAP)
pub enum FAKGHKIKHAP {
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_NLCDGIPGFDJ)
    FAKGHKIKHAP_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_MNFHLEPEKJK)
    FAKGHKIKHAP_MNFHLEPEKJK = 3932,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_OMGGNOBKEOD)
    FAKGHKIKHAP_OMGGNOBKEOD = 3961,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_PFLBJLOHCLJ)
    FAKGHKIKHAP_PFLBJLOHCLJ = 3913,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_KLLEAKMDKKB)
    FAKGHKIKHAP_KLLEAKMDKKB = 3981,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_GPGPNBKBFHJ)
    FAKGHKIKHAP_GPGPNBKBFHJ = 3945,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_IFFHJNLJHKJ)
    FAKGHKIKHAP_IFFHJNLJHKJ = 3919,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_AHFODNLGILO)
    FAKGHKIKHAP_AHFODNLGILO = 3996,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_PEKJALMHPBI)
    FAKGHKIKHAP_PEKJALMHPBI = 3929,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_GFFEPIMMIMP)
    FAKGHKIKHAP_GFFEPIMMIMP = 3924,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_CEGHENGKHFK)
    FAKGHKIKHAP_CEGHENGKHFK = 3954,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_IDDAOKOGBLH)
    FAKGHKIKHAP_IDDAOKOGBLH = 3946,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_KFOAFFPIMNF)
    FAKGHKIKHAP_KFOAFFPIMNF = 3918,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_BHBEJBBHAON)
    FAKGHKIKHAP_BHBEJBBHAON = 3983,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_KKAIBLABMNO)
    FAKGHKIKHAP_KKAIBLABMNO = 3944,
    // @@protoc_insertion_point(enum_value:FAKGHKIKHAP.FAKGHKIKHAP_GFIFMJFAEJN)
    FAKGHKIKHAP_GFIFMJFAEJN = 3977,
}

impl ::protobuf::Enum for FAKGHKIKHAP {
    const NAME: &'static str = "FAKGHKIKHAP";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FAKGHKIKHAP> {
        match value {
            0 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_NLCDGIPGFDJ),
            3932 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_MNFHLEPEKJK),
            3961 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_OMGGNOBKEOD),
            3913 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_PFLBJLOHCLJ),
            3981 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_KLLEAKMDKKB),
            3945 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_GPGPNBKBFHJ),
            3919 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_IFFHJNLJHKJ),
            3996 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_AHFODNLGILO),
            3929 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_PEKJALMHPBI),
            3924 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_GFFEPIMMIMP),
            3954 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_CEGHENGKHFK),
            3946 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_IDDAOKOGBLH),
            3918 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_KFOAFFPIMNF),
            3983 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_BHBEJBBHAON),
            3944 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_KKAIBLABMNO),
            3977 => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_GFIFMJFAEJN),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<FAKGHKIKHAP> {
        match str {
            "FAKGHKIKHAP_NLCDGIPGFDJ" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_NLCDGIPGFDJ),
            "FAKGHKIKHAP_MNFHLEPEKJK" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_MNFHLEPEKJK),
            "FAKGHKIKHAP_OMGGNOBKEOD" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_OMGGNOBKEOD),
            "FAKGHKIKHAP_PFLBJLOHCLJ" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_PFLBJLOHCLJ),
            "FAKGHKIKHAP_KLLEAKMDKKB" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_KLLEAKMDKKB),
            "FAKGHKIKHAP_GPGPNBKBFHJ" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_GPGPNBKBFHJ),
            "FAKGHKIKHAP_IFFHJNLJHKJ" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_IFFHJNLJHKJ),
            "FAKGHKIKHAP_AHFODNLGILO" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_AHFODNLGILO),
            "FAKGHKIKHAP_PEKJALMHPBI" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_PEKJALMHPBI),
            "FAKGHKIKHAP_GFFEPIMMIMP" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_GFFEPIMMIMP),
            "FAKGHKIKHAP_CEGHENGKHFK" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_CEGHENGKHFK),
            "FAKGHKIKHAP_IDDAOKOGBLH" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_IDDAOKOGBLH),
            "FAKGHKIKHAP_KFOAFFPIMNF" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_KFOAFFPIMNF),
            "FAKGHKIKHAP_BHBEJBBHAON" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_BHBEJBBHAON),
            "FAKGHKIKHAP_KKAIBLABMNO" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_KKAIBLABMNO),
            "FAKGHKIKHAP_GFIFMJFAEJN" => ::std::option::Option::Some(FAKGHKIKHAP::FAKGHKIKHAP_GFIFMJFAEJN),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [FAKGHKIKHAP] = &[
        FAKGHKIKHAP::FAKGHKIKHAP_NLCDGIPGFDJ,
        FAKGHKIKHAP::FAKGHKIKHAP_MNFHLEPEKJK,
        FAKGHKIKHAP::FAKGHKIKHAP_OMGGNOBKEOD,
        FAKGHKIKHAP::FAKGHKIKHAP_PFLBJLOHCLJ,
        FAKGHKIKHAP::FAKGHKIKHAP_KLLEAKMDKKB,
        FAKGHKIKHAP::FAKGHKIKHAP_GPGPNBKBFHJ,
        FAKGHKIKHAP::FAKGHKIKHAP_IFFHJNLJHKJ,
        FAKGHKIKHAP::FAKGHKIKHAP_AHFODNLGILO,
        FAKGHKIKHAP::FAKGHKIKHAP_PEKJALMHPBI,
        FAKGHKIKHAP::FAKGHKIKHAP_GFFEPIMMIMP,
        FAKGHKIKHAP::FAKGHKIKHAP_CEGHENGKHFK,
        FAKGHKIKHAP::FAKGHKIKHAP_IDDAOKOGBLH,
        FAKGHKIKHAP::FAKGHKIKHAP_KFOAFFPIMNF,
        FAKGHKIKHAP::FAKGHKIKHAP_BHBEJBBHAON,
        FAKGHKIKHAP::FAKGHKIKHAP_KKAIBLABMNO,
        FAKGHKIKHAP::FAKGHKIKHAP_GFIFMJFAEJN,
    ];
}

impl ::protobuf::EnumFull for FAKGHKIKHAP {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("FAKGHKIKHAP").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            FAKGHKIKHAP::FAKGHKIKHAP_NLCDGIPGFDJ => 0,
            FAKGHKIKHAP::FAKGHKIKHAP_MNFHLEPEKJK => 1,
            FAKGHKIKHAP::FAKGHKIKHAP_OMGGNOBKEOD => 2,
            FAKGHKIKHAP::FAKGHKIKHAP_PFLBJLOHCLJ => 3,
            FAKGHKIKHAP::FAKGHKIKHAP_KLLEAKMDKKB => 4,
            FAKGHKIKHAP::FAKGHKIKHAP_GPGPNBKBFHJ => 5,
            FAKGHKIKHAP::FAKGHKIKHAP_IFFHJNLJHKJ => 6,
            FAKGHKIKHAP::FAKGHKIKHAP_AHFODNLGILO => 7,
            FAKGHKIKHAP::FAKGHKIKHAP_PEKJALMHPBI => 8,
            FAKGHKIKHAP::FAKGHKIKHAP_GFFEPIMMIMP => 9,
            FAKGHKIKHAP::FAKGHKIKHAP_CEGHENGKHFK => 10,
            FAKGHKIKHAP::FAKGHKIKHAP_IDDAOKOGBLH => 11,
            FAKGHKIKHAP::FAKGHKIKHAP_KFOAFFPIMNF => 12,
            FAKGHKIKHAP::FAKGHKIKHAP_BHBEJBBHAON => 13,
            FAKGHKIKHAP::FAKGHKIKHAP_KKAIBLABMNO => 14,
            FAKGHKIKHAP::FAKGHKIKHAP_GFIFMJFAEJN => 15,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for FAKGHKIKHAP {
    fn default() -> Self {
        FAKGHKIKHAP::FAKGHKIKHAP_NLCDGIPGFDJ
    }
}

impl FAKGHKIKHAP {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<FAKGHKIKHAP>("FAKGHKIKHAP")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11FAKGHKIKHAP.proto*\xec\x03\n\x0bFAKGHKIKHAP\x12\x1b\n\x17FAKGHKIKH\
    AP_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17FAKGHKIKHAP_MNFHLEPEKJK\x10\xdc\x1e\
    \x12\x1c\n\x17FAKGHKIKHAP_OMGGNOBKEOD\x10\xf9\x1e\x12\x1c\n\x17FAKGHKIKH\
    AP_PFLBJLOHCLJ\x10\xc9\x1e\x12\x1c\n\x17FAKGHKIKHAP_KLLEAKMDKKB\x10\x8d\
    \x1f\x12\x1c\n\x17FAKGHKIKHAP_GPGPNBKBFHJ\x10\xe9\x1e\x12\x1c\n\x17FAKGH\
    KIKHAP_IFFHJNLJHKJ\x10\xcf\x1e\x12\x1c\n\x17FAKGHKIKHAP_AHFODNLGILO\x10\
    \x9c\x1f\x12\x1c\n\x17FAKGHKIKHAP_PEKJALMHPBI\x10\xd9\x1e\x12\x1c\n\x17F\
    AKGHKIKHAP_GFFEPIMMIMP\x10\xd4\x1e\x12\x1c\n\x17FAKGHKIKHAP_CEGHENGKHFK\
    \x10\xf2\x1e\x12\x1c\n\x17FAKGHKIKHAP_IDDAOKOGBLH\x10\xea\x1e\x12\x1c\n\
    \x17FAKGHKIKHAP_KFOAFFPIMNF\x10\xce\x1e\x12\x1c\n\x17FAKGHKIKHAP_BHBEJBB\
    HAON\x10\x8f\x1f\x12\x1c\n\x17FAKGHKIKHAP_KKAIBLABMNO\x10\xe8\x1e\x12\
    \x1c\n\x17FAKGHKIKHAP_GFIFMJFAEJN\x10\x89\x1fb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(FAKGHKIKHAP::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
