// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `FINKPKBICHJ.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:FINKPKBICHJ)
pub enum FINKPKBICHJ {
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_NLCDGIPGFDJ)
    FINKPKBICHJ_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_GEGKJDDPFAM)
    FINKPKBICHJ_GEGKJDDPFAM = 8293,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_KPFDKHBIHMI)
    FINKPKBICHJ_KPFDKHBIHMI = 8312,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_EJMGBFBCBGB)
    FINKPKBICHJ_EJMGBFBCBGB = 8304,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_NENAKHJIKFP)
    FINKPKBICHJ_NENAKHJIKFP = 8330,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_MNDHGELMIFN)
    FINKPKBICHJ_MNDHGELMIFN = 8305,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_IBEEAPKNNOO)
    FINKPKBICHJ_IBEEAPKNNOO = 8295,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_GIDHIGAJBKH)
    FINKPKBICHJ_GIDHIGAJBKH = 8302,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_OBCFGEAIGAN)
    FINKPKBICHJ_OBCFGEAIGAN = 8323,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_HEIDCFGIGFA)
    FINKPKBICHJ_HEIDCFGIGFA = 8339,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_GEJPJANNNMB)
    FINKPKBICHJ_GEJPJANNNMB = 8327,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_OJOPKFIPKOA)
    FINKPKBICHJ_OJOPKFIPKOA = 8326,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_KJCFACGAADE)
    FINKPKBICHJ_KJCFACGAADE = 8337,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_OPNFLKEKCPJ)
    FINKPKBICHJ_OPNFLKEKCPJ = 8317,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_IIDKHMCKJOE)
    FINKPKBICHJ_IIDKHMCKJOE = 8300,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_EIEEIHMKDHF)
    FINKPKBICHJ_EIEEIHMKDHF = 8299,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_CEMGNGMKDNK)
    FINKPKBICHJ_CEMGNGMKDNK = 8321,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_MDEAKEPLECG)
    FINKPKBICHJ_MDEAKEPLECG = 8301,
    // @@protoc_insertion_point(enum_value:FINKPKBICHJ.FINKPKBICHJ_KDLCECCBFMO)
    FINKPKBICHJ_KDLCECCBFMO = 8296,
}

impl ::protobuf::Enum for FINKPKBICHJ {
    const NAME: &'static str = "FINKPKBICHJ";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FINKPKBICHJ> {
        match value {
            0 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_NLCDGIPGFDJ),
            8293 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_GEGKJDDPFAM),
            8312 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_KPFDKHBIHMI),
            8304 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_EJMGBFBCBGB),
            8330 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_NENAKHJIKFP),
            8305 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_MNDHGELMIFN),
            8295 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_IBEEAPKNNOO),
            8302 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_GIDHIGAJBKH),
            8323 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_OBCFGEAIGAN),
            8339 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_HEIDCFGIGFA),
            8327 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_GEJPJANNNMB),
            8326 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_OJOPKFIPKOA),
            8337 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_KJCFACGAADE),
            8317 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_OPNFLKEKCPJ),
            8300 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_IIDKHMCKJOE),
            8299 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_EIEEIHMKDHF),
            8321 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_CEMGNGMKDNK),
            8301 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_MDEAKEPLECG),
            8296 => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_KDLCECCBFMO),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<FINKPKBICHJ> {
        match str {
            "FINKPKBICHJ_NLCDGIPGFDJ" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_NLCDGIPGFDJ),
            "FINKPKBICHJ_GEGKJDDPFAM" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_GEGKJDDPFAM),
            "FINKPKBICHJ_KPFDKHBIHMI" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_KPFDKHBIHMI),
            "FINKPKBICHJ_EJMGBFBCBGB" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_EJMGBFBCBGB),
            "FINKPKBICHJ_NENAKHJIKFP" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_NENAKHJIKFP),
            "FINKPKBICHJ_MNDHGELMIFN" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_MNDHGELMIFN),
            "FINKPKBICHJ_IBEEAPKNNOO" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_IBEEAPKNNOO),
            "FINKPKBICHJ_GIDHIGAJBKH" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_GIDHIGAJBKH),
            "FINKPKBICHJ_OBCFGEAIGAN" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_OBCFGEAIGAN),
            "FINKPKBICHJ_HEIDCFGIGFA" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_HEIDCFGIGFA),
            "FINKPKBICHJ_GEJPJANNNMB" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_GEJPJANNNMB),
            "FINKPKBICHJ_OJOPKFIPKOA" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_OJOPKFIPKOA),
            "FINKPKBICHJ_KJCFACGAADE" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_KJCFACGAADE),
            "FINKPKBICHJ_OPNFLKEKCPJ" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_OPNFLKEKCPJ),
            "FINKPKBICHJ_IIDKHMCKJOE" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_IIDKHMCKJOE),
            "FINKPKBICHJ_EIEEIHMKDHF" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_EIEEIHMKDHF),
            "FINKPKBICHJ_CEMGNGMKDNK" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_CEMGNGMKDNK),
            "FINKPKBICHJ_MDEAKEPLECG" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_MDEAKEPLECG),
            "FINKPKBICHJ_KDLCECCBFMO" => ::std::option::Option::Some(FINKPKBICHJ::FINKPKBICHJ_KDLCECCBFMO),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [FINKPKBICHJ] = &[
        FINKPKBICHJ::FINKPKBICHJ_NLCDGIPGFDJ,
        FINKPKBICHJ::FINKPKBICHJ_GEGKJDDPFAM,
        FINKPKBICHJ::FINKPKBICHJ_KPFDKHBIHMI,
        FINKPKBICHJ::FINKPKBICHJ_EJMGBFBCBGB,
        FINKPKBICHJ::FINKPKBICHJ_NENAKHJIKFP,
        FINKPKBICHJ::FINKPKBICHJ_MNDHGELMIFN,
        FINKPKBICHJ::FINKPKBICHJ_IBEEAPKNNOO,
        FINKPKBICHJ::FINKPKBICHJ_GIDHIGAJBKH,
        FINKPKBICHJ::FINKPKBICHJ_OBCFGEAIGAN,
        FINKPKBICHJ::FINKPKBICHJ_HEIDCFGIGFA,
        FINKPKBICHJ::FINKPKBICHJ_GEJPJANNNMB,
        FINKPKBICHJ::FINKPKBICHJ_OJOPKFIPKOA,
        FINKPKBICHJ::FINKPKBICHJ_KJCFACGAADE,
        FINKPKBICHJ::FINKPKBICHJ_OPNFLKEKCPJ,
        FINKPKBICHJ::FINKPKBICHJ_IIDKHMCKJOE,
        FINKPKBICHJ::FINKPKBICHJ_EIEEIHMKDHF,
        FINKPKBICHJ::FINKPKBICHJ_CEMGNGMKDNK,
        FINKPKBICHJ::FINKPKBICHJ_MDEAKEPLECG,
        FINKPKBICHJ::FINKPKBICHJ_KDLCECCBFMO,
    ];
}

impl ::protobuf::EnumFull for FINKPKBICHJ {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("FINKPKBICHJ").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            FINKPKBICHJ::FINKPKBICHJ_NLCDGIPGFDJ => 0,
            FINKPKBICHJ::FINKPKBICHJ_GEGKJDDPFAM => 1,
            FINKPKBICHJ::FINKPKBICHJ_KPFDKHBIHMI => 2,
            FINKPKBICHJ::FINKPKBICHJ_EJMGBFBCBGB => 3,
            FINKPKBICHJ::FINKPKBICHJ_NENAKHJIKFP => 4,
            FINKPKBICHJ::FINKPKBICHJ_MNDHGELMIFN => 5,
            FINKPKBICHJ::FINKPKBICHJ_IBEEAPKNNOO => 6,
            FINKPKBICHJ::FINKPKBICHJ_GIDHIGAJBKH => 7,
            FINKPKBICHJ::FINKPKBICHJ_OBCFGEAIGAN => 8,
            FINKPKBICHJ::FINKPKBICHJ_HEIDCFGIGFA => 9,
            FINKPKBICHJ::FINKPKBICHJ_GEJPJANNNMB => 10,
            FINKPKBICHJ::FINKPKBICHJ_OJOPKFIPKOA => 11,
            FINKPKBICHJ::FINKPKBICHJ_KJCFACGAADE => 12,
            FINKPKBICHJ::FINKPKBICHJ_OPNFLKEKCPJ => 13,
            FINKPKBICHJ::FINKPKBICHJ_IIDKHMCKJOE => 14,
            FINKPKBICHJ::FINKPKBICHJ_EIEEIHMKDHF => 15,
            FINKPKBICHJ::FINKPKBICHJ_CEMGNGMKDNK => 16,
            FINKPKBICHJ::FINKPKBICHJ_MDEAKEPLECG => 17,
            FINKPKBICHJ::FINKPKBICHJ_KDLCECCBFMO => 18,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for FINKPKBICHJ {
    fn default() -> Self {
        FINKPKBICHJ::FINKPKBICHJ_NLCDGIPGFDJ
    }
}

impl FINKPKBICHJ {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<FINKPKBICHJ>("FINKPKBICHJ")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11FINKPKBICHJ.proto*\xc6\x04\n\x0bFINKPKBICHJ\x12\x1b\n\x17FINKPKBIC\
    HJ_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17FINKPKBICHJ_GEGKJDDPFAM\x10\xe5@\x12\
    \x1c\n\x17FINKPKBICHJ_KPFDKHBIHMI\x10\xf8@\x12\x1c\n\x17FINKPKBICHJ_EJMG\
    BFBCBGB\x10\xf0@\x12\x1c\n\x17FINKPKBICHJ_NENAKHJIKFP\x10\x8aA\x12\x1c\n\
    \x17FINKPKBICHJ_MNDHGELMIFN\x10\xf1@\x12\x1c\n\x17FINKPKBICHJ_IBEEAPKNNO\
    O\x10\xe7@\x12\x1c\n\x17FINKPKBICHJ_GIDHIGAJBKH\x10\xee@\x12\x1c\n\x17FI\
    NKPKBICHJ_OBCFGEAIGAN\x10\x83A\x12\x1c\n\x17FINKPKBICHJ_HEIDCFGIGFA\x10\
    \x93A\x12\x1c\n\x17FINKPKBICHJ_GEJPJANNNMB\x10\x87A\x12\x1c\n\x17FINKPKB\
    ICHJ_OJOPKFIPKOA\x10\x86A\x12\x1c\n\x17FINKPKBICHJ_KJCFACGAADE\x10\x91A\
    \x12\x1c\n\x17FINKPKBICHJ_OPNFLKEKCPJ\x10\xfd@\x12\x1c\n\x17FINKPKBICHJ_\
    IIDKHMCKJOE\x10\xec@\x12\x1c\n\x17FINKPKBICHJ_EIEEIHMKDHF\x10\xeb@\x12\
    \x1c\n\x17FINKPKBICHJ_CEMGNGMKDNK\x10\x81A\x12\x1c\n\x17FINKPKBICHJ_MDEA\
    KEPLECG\x10\xed@\x12\x1c\n\x17FINKPKBICHJ_KDLCECCBFMO\x10\xe8@b\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(FINKPKBICHJ::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
