// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_1095f21f.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_1095f21f)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_1095f21f {
    // message fields
    // @@protoc_insertion_point(field:H_1095f21f.PFMDKHIDDLB)
    pub PFMDKHIDDLB: ::std::vec::Vec<super::H_e616bfbd::H_e616bfbd>,
    // @@protoc_insertion_point(field:H_1095f21f.H_7e8b12bb)
    pub H_7e8b12bb: ::std::vec::Vec<super::H_8b50de87::H_8b50de87>,
    // special fields
    // @@protoc_insertion_point(special_field:H_1095f21f.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_1095f21f {
    fn default() -> &'a H_1095f21f {
        <H_1095f21f as ::protobuf::Message>::default_instance()
    }
}

impl H_1095f21f {
    pub fn new() -> H_1095f21f {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "PFMDKHIDDLB",
            |m: &H_1095f21f| { &m.PFMDKHIDDLB },
            |m: &mut H_1095f21f| { &mut m.PFMDKHIDDLB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "H_7e8b12bb",
            |m: &H_1095f21f| { &m.H_7e8b12bb },
            |m: &mut H_1095f21f| { &mut m.H_7e8b12bb },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_1095f21f>(
            "H_1095f21f",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_1095f21f {
    const NAME: &'static str = "H_1095f21f";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                98 => {
                    self.PFMDKHIDDLB.push(is.read_message()?);
                },
                106 => {
                    self.H_7e8b12bb.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.PFMDKHIDDLB {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.H_7e8b12bb {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.PFMDKHIDDLB {
            ::protobuf::rt::write_message_field_with_cached_size(12, v, os)?;
        };
        for v in &self.H_7e8b12bb {
            ::protobuf::rt::write_message_field_with_cached_size(13, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_1095f21f {
        H_1095f21f::new()
    }

    fn clear(&mut self) {
        self.PFMDKHIDDLB.clear();
        self.H_7e8b12bb.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_1095f21f {
        static instance: H_1095f21f = H_1095f21f {
            PFMDKHIDDLB: ::std::vec::Vec::new(),
            H_7e8b12bb: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for H_1095f21f {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_1095f21f").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_1095f21f {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_1095f21f {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_1095f21f.proto\x1a\x10H_8b50de87.proto\x1a\x10H_e616bfbd.proto\"\
    g\n\nH_1095f21f\x12-\n\x0bPFMDKHIDDLB\x18\x0c\x20\x03(\x0b2\x0b.H_e616bf\
    bdR\x0bPFMDKHIDDLB\x12*\n\nH_7e8b12bb\x18\r\x20\x03(\x0b2\x0b.H_8b50de87\
    R\tH7e8b12bbb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::H_8b50de87::file_descriptor().clone());
            deps.push(super::H_e616bfbd::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_1095f21f::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
