// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_1b540a39.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_1b540a39)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_1b540a39 {
    // message fields
    // @@protoc_insertion_point(field:H_1b540a39.LHGIFDNPIDE)
    pub LHGIFDNPIDE: bool,
    // @@protoc_insertion_point(field:H_1b540a39.KDKPDJNMMCM)
    pub KDKPDJNMMCM: u32,
    // message oneof groups
    pub AELHFLGJMJN: ::std::option::Option<h_1b540a39::AELHFLGJMJN>,
    // special fields
    // @@protoc_insertion_point(special_field:H_1b540a39.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_1b540a39 {
    fn default() -> &'a H_1b540a39 {
        <H_1b540a39 as ::protobuf::Message>::default_instance()
    }
}

impl H_1b540a39 {
    pub fn new() -> H_1b540a39 {
        ::std::default::Default::default()
    }

    // .NJBGFHDPFNO BDPIMPJOJBK = 1344;

    pub fn BDPIMPJOJBK(&self) -> &super::NJBGFHDPFNO::NJBGFHDPFNO {
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(ref v)) => v,
            _ => <super::NJBGFHDPFNO::NJBGFHDPFNO as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_BDPIMPJOJBK(&mut self) {
        self.AELHFLGJMJN = ::std::option::Option::None;
    }

    pub fn has_BDPIMPJOJBK(&self) -> bool {
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_BDPIMPJOJBK(&mut self, v: super::NJBGFHDPFNO::NJBGFHDPFNO) {
        self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(v))
    }

    // Mutable pointer to the field.
    pub fn mut_BDPIMPJOJBK(&mut self) -> &mut super::NJBGFHDPFNO::NJBGFHDPFNO {
        if let ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(_)) = self.AELHFLGJMJN {
        } else {
            self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(super::NJBGFHDPFNO::NJBGFHDPFNO::new()));
        }
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_BDPIMPJOJBK(&mut self) -> super::NJBGFHDPFNO::NJBGFHDPFNO {
        if self.has_BDPIMPJOJBK() {
            match self.AELHFLGJMJN.take() {
                ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(v)) => v,
                _ => panic!(),
            }
        } else {
            super::NJBGFHDPFNO::NJBGFHDPFNO::new()
        }
    }

    // .ELJOHIOHPMJ LLIBLKCJEMI = 419;

    pub fn LLIBLKCJEMI(&self) -> &super::ELJOHIOHPMJ::ELJOHIOHPMJ {
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(ref v)) => v,
            _ => <super::ELJOHIOHPMJ::ELJOHIOHPMJ as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_LLIBLKCJEMI(&mut self) {
        self.AELHFLGJMJN = ::std::option::Option::None;
    }

    pub fn has_LLIBLKCJEMI(&self) -> bool {
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_LLIBLKCJEMI(&mut self, v: super::ELJOHIOHPMJ::ELJOHIOHPMJ) {
        self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(v))
    }

    // Mutable pointer to the field.
    pub fn mut_LLIBLKCJEMI(&mut self) -> &mut super::ELJOHIOHPMJ::ELJOHIOHPMJ {
        if let ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(_)) = self.AELHFLGJMJN {
        } else {
            self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(super::ELJOHIOHPMJ::ELJOHIOHPMJ::new()));
        }
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_LLIBLKCJEMI(&mut self) -> super::ELJOHIOHPMJ::ELJOHIOHPMJ {
        if self.has_LLIBLKCJEMI() {
            match self.AELHFLGJMJN.take() {
                ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(v)) => v,
                _ => panic!(),
            }
        } else {
            super::ELJOHIOHPMJ::ELJOHIOHPMJ::new()
        }
    }

    // .CCKPBIKOIBB INBCCAIFHNL = 2012;

    pub fn INBCCAIFHNL(&self) -> &super::CCKPBIKOIBB::CCKPBIKOIBB {
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(ref v)) => v,
            _ => <super::CCKPBIKOIBB::CCKPBIKOIBB as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_INBCCAIFHNL(&mut self) {
        self.AELHFLGJMJN = ::std::option::Option::None;
    }

    pub fn has_INBCCAIFHNL(&self) -> bool {
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_INBCCAIFHNL(&mut self, v: super::CCKPBIKOIBB::CCKPBIKOIBB) {
        self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(v))
    }

    // Mutable pointer to the field.
    pub fn mut_INBCCAIFHNL(&mut self) -> &mut super::CCKPBIKOIBB::CCKPBIKOIBB {
        if let ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(_)) = self.AELHFLGJMJN {
        } else {
            self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(super::CCKPBIKOIBB::CCKPBIKOIBB::new()));
        }
        match self.AELHFLGJMJN {
            ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_INBCCAIFHNL(&mut self) -> super::CCKPBIKOIBB::CCKPBIKOIBB {
        if self.has_INBCCAIFHNL() {
            match self.AELHFLGJMJN.take() {
                ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(v)) => v,
                _ => panic!(),
            }
        } else {
            super::CCKPBIKOIBB::CCKPBIKOIBB::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "LHGIFDNPIDE",
            |m: &H_1b540a39| { &m.LHGIFDNPIDE },
            |m: &mut H_1b540a39| { &mut m.LHGIFDNPIDE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KDKPDJNMMCM",
            |m: &H_1b540a39| { &m.KDKPDJNMMCM },
            |m: &mut H_1b540a39| { &mut m.KDKPDJNMMCM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::NJBGFHDPFNO::NJBGFHDPFNO>(
            "BDPIMPJOJBK",
            H_1b540a39::has_BDPIMPJOJBK,
            H_1b540a39::BDPIMPJOJBK,
            H_1b540a39::mut_BDPIMPJOJBK,
            H_1b540a39::set_BDPIMPJOJBK,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::ELJOHIOHPMJ::ELJOHIOHPMJ>(
            "LLIBLKCJEMI",
            H_1b540a39::has_LLIBLKCJEMI,
            H_1b540a39::LLIBLKCJEMI,
            H_1b540a39::mut_LLIBLKCJEMI,
            H_1b540a39::set_LLIBLKCJEMI,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::CCKPBIKOIBB::CCKPBIKOIBB>(
            "INBCCAIFHNL",
            H_1b540a39::has_INBCCAIFHNL,
            H_1b540a39::INBCCAIFHNL,
            H_1b540a39::mut_INBCCAIFHNL,
            H_1b540a39::set_INBCCAIFHNL,
        ));
        oneofs.push(h_1b540a39::AELHFLGJMJN::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_1b540a39>(
            "H_1b540a39",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_1b540a39 {
    const NAME: &'static str = "H_1b540a39";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                24 => {
                    self.LHGIFDNPIDE = is.read_bool()?;
                },
                72 => {
                    self.KDKPDJNMMCM = is.read_uint32()?;
                },
                10754 => {
                    self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(is.read_message()?));
                },
                3354 => {
                    self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(is.read_message()?));
                },
                16098 => {
                    self.AELHFLGJMJN = ::std::option::Option::Some(h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.LHGIFDNPIDE != false {
            my_size += 1 + 1;
        }
        if self.KDKPDJNMMCM != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.KDKPDJNMMCM);
        }
        if let ::std::option::Option::Some(ref v) = self.AELHFLGJMJN {
            match v {
                &h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.LHGIFDNPIDE != false {
            os.write_bool(3, self.LHGIFDNPIDE)?;
        }
        if self.KDKPDJNMMCM != 0 {
            os.write_uint32(9, self.KDKPDJNMMCM)?;
        }
        if let ::std::option::Option::Some(ref v) = self.AELHFLGJMJN {
            match v {
                &h_1b540a39::AELHFLGJMJN::BDPIMPJOJBK(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1344, v, os)?;
                },
                &h_1b540a39::AELHFLGJMJN::LLIBLKCJEMI(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(419, v, os)?;
                },
                &h_1b540a39::AELHFLGJMJN::INBCCAIFHNL(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2012, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_1b540a39 {
        H_1b540a39::new()
    }

    fn clear(&mut self) {
        self.LHGIFDNPIDE = false;
        self.KDKPDJNMMCM = 0;
        self.AELHFLGJMJN = ::std::option::Option::None;
        self.AELHFLGJMJN = ::std::option::Option::None;
        self.AELHFLGJMJN = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_1b540a39 {
        static instance: H_1b540a39 = H_1b540a39 {
            LHGIFDNPIDE: false,
            KDKPDJNMMCM: 0,
            AELHFLGJMJN: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for H_1b540a39 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_1b540a39").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_1b540a39 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_1b540a39 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `H_1b540a39`
pub mod h_1b540a39 {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:H_1b540a39.AELHFLGJMJN)
    pub enum AELHFLGJMJN {
        // @@protoc_insertion_point(oneof_field:H_1b540a39.BDPIMPJOJBK)
        BDPIMPJOJBK(super::super::NJBGFHDPFNO::NJBGFHDPFNO),
        // @@protoc_insertion_point(oneof_field:H_1b540a39.LLIBLKCJEMI)
        LLIBLKCJEMI(super::super::ELJOHIOHPMJ::ELJOHIOHPMJ),
        // @@protoc_insertion_point(oneof_field:H_1b540a39.INBCCAIFHNL)
        INBCCAIFHNL(super::super::CCKPBIKOIBB::CCKPBIKOIBB),
    }

    impl ::protobuf::Oneof for AELHFLGJMJN {
    }

    impl ::protobuf::OneofFull for AELHFLGJMJN {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::H_1b540a39 as ::protobuf::MessageFull>::descriptor().oneof_by_name("AELHFLGJMJN").unwrap()).clone()
        }
    }

    impl AELHFLGJMJN {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<AELHFLGJMJN>("AELHFLGJMJN")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_1b540a39.proto\x1a\x11CCKPBIKOIBB.proto\x1a\x11ELJOHIOHPMJ.proto\
    \x1a\x11NJBGFHDPFNO.proto\"\xf8\x01\n\nH_1b540a39\x12\x20\n\x0bLHGIFDNPI\
    DE\x18\x03\x20\x01(\x08R\x0bLHGIFDNPIDE\x12\x20\n\x0bKDKPDJNMMCM\x18\t\
    \x20\x01(\rR\x0bKDKPDJNMMCM\x121\n\x0bBDPIMPJOJBK\x18\xc0\n\x20\x01(\x0b\
    2\x0c.NJBGFHDPFNOH\0R\x0bBDPIMPJOJBK\x121\n\x0bLLIBLKCJEMI\x18\xa3\x03\
    \x20\x01(\x0b2\x0c.ELJOHIOHPMJH\0R\x0bLLIBLKCJEMI\x121\n\x0bINBCCAIFHNL\
    \x18\xdc\x0f\x20\x01(\x0b2\x0c.CCKPBIKOIBBH\0R\x0bINBCCAIFHNLB\r\n\x0bAE\
    LHFLGJMJNb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::CCKPBIKOIBB::file_descriptor().clone());
            deps.push(super::ELJOHIOHPMJ::file_descriptor().clone());
            deps.push(super::NJBGFHDPFNO::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_1b540a39::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
