// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_292b7d8b.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_292b7d8b)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_292b7d8b {
    // message fields
    // @@protoc_insertion_point(field:H_292b7d8b.OGLOCDMNNIM)
    pub OGLOCDMNNIM: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.EMOHLJHPOPC)
    pub EMOHLJHPOPC: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.section_id)
    pub section_id: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.DMNILJEGICO)
    pub DMNILJEGICO: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.DCAHJELNJNP)
    pub DCAHJELNJNP: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.NKBIDLBLONC)
    pub NKBIDLBLONC: ::protobuf::MessageField<super::H_4142a2dd::H_4142a2dd>,
    // @@protoc_insertion_point(field:H_292b7d8b.JPKHBELGHCG)
    pub JPKHBELGHCG: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.HFLPDCJDIAC)
    pub HFLPDCJDIAC: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.CBHJKFNCDAD)
    pub CBHJKFNCDAD: bool,
    // @@protoc_insertion_point(field:H_292b7d8b.AFFFCONCDMG)
    pub AFFFCONCDMG: ::std::collections::HashMap<u32, super::H_cb5e278e::H_cb5e278e>,
    // @@protoc_insertion_point(field:H_292b7d8b.OAHFCPPIMLF)
    pub OAHFCPPIMLF: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.LKCJAPIGEND)
    pub LKCJAPIGEND: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.OCCOHKIMGCN)
    pub OCCOHKIMGCN: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.PAGPKOKMDBK)
    pub PAGPKOKMDBK: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.ODJEBDNBLLC)
    pub ODJEBDNBLLC: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.CLFNPMGHMFC)
    pub CLFNPMGHMFC: u32,
    // @@protoc_insertion_point(field:H_292b7d8b.HMKOKACNHJH)
    pub HMKOKACNHJH: ::std::vec::Vec<super::H_baca218b::H_baca218b>,
    // @@protoc_insertion_point(field:H_292b7d8b.AEOCOGHMEBG)
    pub AEOCOGHMEBG: ::protobuf::MessageField<super::GEEMFDBDMDH::GEEMFDBDMDH>,
    // special fields
    // @@protoc_insertion_point(special_field:H_292b7d8b.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_292b7d8b {
    fn default() -> &'a H_292b7d8b {
        <H_292b7d8b as ::protobuf::Message>::default_instance()
    }
}

impl H_292b7d8b {
    pub fn new() -> H_292b7d8b {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(18);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "OGLOCDMNNIM",
            |m: &H_292b7d8b| { &m.OGLOCDMNNIM },
            |m: &mut H_292b7d8b| { &mut m.OGLOCDMNNIM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EMOHLJHPOPC",
            |m: &H_292b7d8b| { &m.EMOHLJHPOPC },
            |m: &mut H_292b7d8b| { &mut m.EMOHLJHPOPC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "section_id",
            |m: &H_292b7d8b| { &m.section_id },
            |m: &mut H_292b7d8b| { &mut m.section_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "DMNILJEGICO",
            |m: &H_292b7d8b| { &m.DMNILJEGICO },
            |m: &mut H_292b7d8b| { &mut m.DMNILJEGICO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "DCAHJELNJNP",
            |m: &H_292b7d8b| { &m.DCAHJELNJNP },
            |m: &mut H_292b7d8b| { &mut m.DCAHJELNJNP },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::H_4142a2dd::H_4142a2dd>(
            "NKBIDLBLONC",
            |m: &H_292b7d8b| { &m.NKBIDLBLONC },
            |m: &mut H_292b7d8b| { &mut m.NKBIDLBLONC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JPKHBELGHCG",
            |m: &H_292b7d8b| { &m.JPKHBELGHCG },
            |m: &mut H_292b7d8b| { &mut m.JPKHBELGHCG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "HFLPDCJDIAC",
            |m: &H_292b7d8b| { &m.HFLPDCJDIAC },
            |m: &mut H_292b7d8b| { &mut m.HFLPDCJDIAC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CBHJKFNCDAD",
            |m: &H_292b7d8b| { &m.CBHJKFNCDAD },
            |m: &mut H_292b7d8b| { &mut m.CBHJKFNCDAD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "AFFFCONCDMG",
            |m: &H_292b7d8b| { &m.AFFFCONCDMG },
            |m: &mut H_292b7d8b| { &mut m.AFFFCONCDMG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "OAHFCPPIMLF",
            |m: &H_292b7d8b| { &m.OAHFCPPIMLF },
            |m: &mut H_292b7d8b| { &mut m.OAHFCPPIMLF },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "LKCJAPIGEND",
            |m: &H_292b7d8b| { &m.LKCJAPIGEND },
            |m: &mut H_292b7d8b| { &mut m.LKCJAPIGEND },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "OCCOHKIMGCN",
            |m: &H_292b7d8b| { &m.OCCOHKIMGCN },
            |m: &mut H_292b7d8b| { &mut m.OCCOHKIMGCN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "PAGPKOKMDBK",
            |m: &H_292b7d8b| { &m.PAGPKOKMDBK },
            |m: &mut H_292b7d8b| { &mut m.PAGPKOKMDBK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ODJEBDNBLLC",
            |m: &H_292b7d8b| { &m.ODJEBDNBLLC },
            |m: &mut H_292b7d8b| { &mut m.ODJEBDNBLLC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CLFNPMGHMFC",
            |m: &H_292b7d8b| { &m.CLFNPMGHMFC },
            |m: &mut H_292b7d8b| { &mut m.CLFNPMGHMFC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "HMKOKACNHJH",
            |m: &H_292b7d8b| { &m.HMKOKACNHJH },
            |m: &mut H_292b7d8b| { &mut m.HMKOKACNHJH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::GEEMFDBDMDH::GEEMFDBDMDH>(
            "AEOCOGHMEBG",
            |m: &H_292b7d8b| { &m.AEOCOGHMEBG },
            |m: &mut H_292b7d8b| { &mut m.AEOCOGHMEBG },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_292b7d8b>(
            "H_292b7d8b",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_292b7d8b {
    const NAME: &'static str = "H_292b7d8b";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.OGLOCDMNNIM = is.read_uint32()?;
                },
                24 => {
                    self.EMOHLJHPOPC = is.read_uint32()?;
                },
                32 => {
                    self.section_id = is.read_uint32()?;
                },
                40 => {
                    self.DMNILJEGICO = is.read_uint32()?;
                },
                64 => {
                    self.DCAHJELNJNP = is.read_uint32()?;
                },
                74 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.NKBIDLBLONC)?;
                },
                88 => {
                    self.JPKHBELGHCG = is.read_uint32()?;
                },
                96 => {
                    self.HFLPDCJDIAC = is.read_uint32()?;
                },
                112 => {
                    self.CBHJKFNCDAD = is.read_bool()?;
                },
                122 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            8 => key = is.read_uint32()?,
                            18 => value = is.read_message()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.AFFFCONCDMG.insert(key, value);
                },
                2760 => {
                    self.OAHFCPPIMLF = is.read_uint32()?;
                },
                3440 => {
                    self.LKCJAPIGEND = is.read_uint32()?;
                },
                4288 => {
                    self.OCCOHKIMGCN = is.read_uint32()?;
                },
                5144 => {
                    self.PAGPKOKMDBK = is.read_uint32()?;
                },
                10952 => {
                    self.ODJEBDNBLLC = is.read_uint32()?;
                },
                11352 => {
                    self.CLFNPMGHMFC = is.read_uint32()?;
                },
                14778 => {
                    self.HMKOKACNHJH.push(is.read_message()?);
                },
                15402 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.AEOCOGHMEBG)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.OGLOCDMNNIM != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.OGLOCDMNNIM);
        }
        if self.EMOHLJHPOPC != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.EMOHLJHPOPC);
        }
        if self.section_id != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.section_id);
        }
        if self.DMNILJEGICO != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.DMNILJEGICO);
        }
        if self.DCAHJELNJNP != 0 {
            my_size += ::protobuf::rt::uint32_size(8, self.DCAHJELNJNP);
        }
        if let Some(v) = self.NKBIDLBLONC.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.JPKHBELGHCG != 0 {
            my_size += ::protobuf::rt::uint32_size(11, self.JPKHBELGHCG);
        }
        if self.HFLPDCJDIAC != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.HFLPDCJDIAC);
        }
        if self.CBHJKFNCDAD != false {
            my_size += 1 + 1;
        }
        for (k, v) in &self.AFFFCONCDMG {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::uint32_size(1, *k);
            let len = v.compute_size();
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        if self.OAHFCPPIMLF != 0 {
            my_size += ::protobuf::rt::uint32_size(345, self.OAHFCPPIMLF);
        }
        if self.LKCJAPIGEND != 0 {
            my_size += ::protobuf::rt::uint32_size(430, self.LKCJAPIGEND);
        }
        if self.OCCOHKIMGCN != 0 {
            my_size += ::protobuf::rt::uint32_size(536, self.OCCOHKIMGCN);
        }
        if self.PAGPKOKMDBK != 0 {
            my_size += ::protobuf::rt::uint32_size(643, self.PAGPKOKMDBK);
        }
        if self.ODJEBDNBLLC != 0 {
            my_size += ::protobuf::rt::uint32_size(1369, self.ODJEBDNBLLC);
        }
        if self.CLFNPMGHMFC != 0 {
            my_size += ::protobuf::rt::uint32_size(1419, self.CLFNPMGHMFC);
        }
        for value in &self.HMKOKACNHJH {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.AEOCOGHMEBG.as_ref() {
            let len = v.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.OGLOCDMNNIM != 0 {
            os.write_uint32(1, self.OGLOCDMNNIM)?;
        }
        if self.EMOHLJHPOPC != 0 {
            os.write_uint32(3, self.EMOHLJHPOPC)?;
        }
        if self.section_id != 0 {
            os.write_uint32(4, self.section_id)?;
        }
        if self.DMNILJEGICO != 0 {
            os.write_uint32(5, self.DMNILJEGICO)?;
        }
        if self.DCAHJELNJNP != 0 {
            os.write_uint32(8, self.DCAHJELNJNP)?;
        }
        if let Some(v) = self.NKBIDLBLONC.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        }
        if self.JPKHBELGHCG != 0 {
            os.write_uint32(11, self.JPKHBELGHCG)?;
        }
        if self.HFLPDCJDIAC != 0 {
            os.write_uint32(12, self.HFLPDCJDIAC)?;
        }
        if self.CBHJKFNCDAD != false {
            os.write_bool(14, self.CBHJKFNCDAD)?;
        }
        for (k, v) in &self.AFFFCONCDMG {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::uint32_size(1, *k);
            let len = v.cached_size() as u64;
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            os.write_raw_varint32(122)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_uint32(1, *k)?;
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.OAHFCPPIMLF != 0 {
            os.write_uint32(345, self.OAHFCPPIMLF)?;
        }
        if self.LKCJAPIGEND != 0 {
            os.write_uint32(430, self.LKCJAPIGEND)?;
        }
        if self.OCCOHKIMGCN != 0 {
            os.write_uint32(536, self.OCCOHKIMGCN)?;
        }
        if self.PAGPKOKMDBK != 0 {
            os.write_uint32(643, self.PAGPKOKMDBK)?;
        }
        if self.ODJEBDNBLLC != 0 {
            os.write_uint32(1369, self.ODJEBDNBLLC)?;
        }
        if self.CLFNPMGHMFC != 0 {
            os.write_uint32(1419, self.CLFNPMGHMFC)?;
        }
        for v in &self.HMKOKACNHJH {
            ::protobuf::rt::write_message_field_with_cached_size(1847, v, os)?;
        };
        if let Some(v) = self.AEOCOGHMEBG.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1925, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_292b7d8b {
        H_292b7d8b::new()
    }

    fn clear(&mut self) {
        self.OGLOCDMNNIM = 0;
        self.EMOHLJHPOPC = 0;
        self.section_id = 0;
        self.DMNILJEGICO = 0;
        self.DCAHJELNJNP = 0;
        self.NKBIDLBLONC.clear();
        self.JPKHBELGHCG = 0;
        self.HFLPDCJDIAC = 0;
        self.CBHJKFNCDAD = false;
        self.AFFFCONCDMG.clear();
        self.OAHFCPPIMLF = 0;
        self.LKCJAPIGEND = 0;
        self.OCCOHKIMGCN = 0;
        self.PAGPKOKMDBK = 0;
        self.ODJEBDNBLLC = 0;
        self.CLFNPMGHMFC = 0;
        self.HMKOKACNHJH.clear();
        self.AEOCOGHMEBG.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_292b7d8b {
        static instance: ::protobuf::rt::Lazy<H_292b7d8b> = ::protobuf::rt::Lazy::new();
        instance.get(H_292b7d8b::new)
    }
}

impl ::protobuf::MessageFull for H_292b7d8b {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_292b7d8b").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_292b7d8b {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_292b7d8b {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_292b7d8b.proto\x1a\x11GEEMFDBDMDH.proto\x1a\x10H_4142a2dd.proto\
    \x1a\x10H_baca218b.proto\x1a\x10H_cb5e278e.proto\"\x88\x06\n\nH_292b7d8b\
    \x12\x20\n\x0bOGLOCDMNNIM\x18\x01\x20\x01(\rR\x0bOGLOCDMNNIM\x12\x20\n\
    \x0bEMOHLJHPOPC\x18\x03\x20\x01(\rR\x0bEMOHLJHPOPC\x12\x1d\n\nsection_id\
    \x18\x04\x20\x01(\rR\tsectionId\x12\x20\n\x0bDMNILJEGICO\x18\x05\x20\x01\
    (\rR\x0bDMNILJEGICO\x12\x20\n\x0bDCAHJELNJNP\x18\x08\x20\x01(\rR\x0bDCAH\
    JELNJNP\x12-\n\x0bNKBIDLBLONC\x18\t\x20\x01(\x0b2\x0b.H_4142a2ddR\x0bNKB\
    IDLBLONC\x12\x20\n\x0bJPKHBELGHCG\x18\x0b\x20\x01(\rR\x0bJPKHBELGHCG\x12\
    \x20\n\x0bHFLPDCJDIAC\x18\x0c\x20\x01(\rR\x0bHFLPDCJDIAC\x12\x20\n\x0bCB\
    HJKFNCDAD\x18\x0e\x20\x01(\x08R\x0bCBHJKFNCDAD\x12>\n\x0bAFFFCONCDMG\x18\
    \x0f\x20\x03(\x0b2\x1c.H_292b7d8b.AFFFCONCDMGEntryR\x0bAFFFCONCDMG\x12!\
    \n\x0bOAHFCPPIMLF\x18\xd9\x02\x20\x01(\rR\x0bOAHFCPPIMLF\x12!\n\x0bLKCJA\
    PIGEND\x18\xae\x03\x20\x01(\rR\x0bLKCJAPIGEND\x12!\n\x0bOCCOHKIMGCN\x18\
    \x98\x04\x20\x01(\rR\x0bOCCOHKIMGCN\x12!\n\x0bPAGPKOKMDBK\x18\x83\x05\
    \x20\x01(\rR\x0bPAGPKOKMDBK\x12!\n\x0bODJEBDNBLLC\x18\xd9\n\x20\x01(\rR\
    \x0bODJEBDNBLLC\x12!\n\x0bCLFNPMGHMFC\x18\x8b\x0b\x20\x01(\rR\x0bCLFNPMG\
    HMFC\x12.\n\x0bHMKOKACNHJH\x18\xb7\x0e\x20\x03(\x0b2\x0b.H_baca218bR\x0b\
    HMKOKACNHJH\x12/\n\x0bAEOCOGHMEBG\x18\x85\x0f\x20\x01(\x0b2\x0c.GEEMFDBD\
    MDHR\x0bAEOCOGHMEBG\x1aK\n\x10AFFFCONCDMGEntry\x12\x10\n\x03key\x18\x01\
    \x20\x01(\rR\x03key\x12!\n\x05value\x18\x02\x20\x01(\x0b2\x0b.H_cb5e278e\
    R\x05value:\x028\x01b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(4);
            deps.push(super::GEEMFDBDMDH::file_descriptor().clone());
            deps.push(super::H_4142a2dd::file_descriptor().clone());
            deps.push(super::H_baca218b::file_descriptor().clone());
            deps.push(super::H_cb5e278e::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_292b7d8b::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
