// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_49e0c291.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_49e0c291)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_49e0c291 {
    // message fields
    // @@protoc_insertion_point(field:H_49e0c291.PKELAIPIHMF)
    pub PKELAIPIHMF: ::protobuf::MessageField<super::CKPOBLIFMGN::CKPOBLIFMGN>,
    // @@protoc_insertion_point(field:H_49e0c291.HFPEJIDDDJG)
    pub HFPEJIDDDJG: ::protobuf::MessageField<super::H_379cf494::H_379cf494>,
    // special fields
    // @@protoc_insertion_point(special_field:H_49e0c291.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_49e0c291 {
    fn default() -> &'a H_49e0c291 {
        <H_49e0c291 as ::protobuf::Message>::default_instance()
    }
}

impl H_49e0c291 {
    pub fn new() -> H_49e0c291 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::CKPOBLIFMGN::CKPOBLIFMGN>(
            "PKELAIPIHMF",
            |m: &H_49e0c291| { &m.PKELAIPIHMF },
            |m: &mut H_49e0c291| { &mut m.PKELAIPIHMF },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::H_379cf494::H_379cf494>(
            "HFPEJIDDDJG",
            |m: &H_49e0c291| { &m.HFPEJIDDDJG },
            |m: &mut H_49e0c291| { &mut m.HFPEJIDDDJG },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_49e0c291>(
            "H_49e0c291",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_49e0c291 {
    const NAME: &'static str = "H_49e0c291";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.PKELAIPIHMF)?;
                },
                114 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.HFPEJIDDDJG)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.PKELAIPIHMF.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.HFPEJIDDDJG.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.PKELAIPIHMF.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if let Some(v) = self.HFPEJIDDDJG.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(14, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_49e0c291 {
        H_49e0c291::new()
    }

    fn clear(&mut self) {
        self.PKELAIPIHMF.clear();
        self.HFPEJIDDDJG.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_49e0c291 {
        static instance: H_49e0c291 = H_49e0c291 {
            PKELAIPIHMF: ::protobuf::MessageField::none(),
            HFPEJIDDDJG: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for H_49e0c291 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_49e0c291").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_49e0c291 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_49e0c291 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_49e0c291.proto\x1a\x11CKPOBLIFMGN.proto\x1a\x10H_379cf494.proto\
    \"k\n\nH_49e0c291\x12.\n\x0bPKELAIPIHMF\x18\x06\x20\x01(\x0b2\x0c.CKPOBL\
    IFMGNR\x0bPKELAIPIHMF\x12-\n\x0bHFPEJIDDDJG\x18\x0e\x20\x01(\x0b2\x0b.H_\
    379cf494R\x0bHFPEJIDDDJGb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::CKPOBLIFMGN::file_descriptor().clone());
            deps.push(super::H_379cf494::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_49e0c291::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
