// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_53156b9a.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_53156b9a)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_53156b9a {
    // message fields
    // @@protoc_insertion_point(field:H_53156b9a.effect_id)
    pub effect_id: u32,
    // message oneof groups
    pub NEBNJDMFELO: ::std::option::Option<h_53156b9a::NEBNJDMFELO>,
    // special fields
    // @@protoc_insertion_point(special_field:H_53156b9a.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_53156b9a {
    fn default() -> &'a H_53156b9a {
        <H_53156b9a as ::protobuf::Message>::default_instance()
    }
}

impl H_53156b9a {
    pub fn new() -> H_53156b9a {
        ::std::default::Default::default()
    }

    // uint32 trait_core_role = 1825;

    pub fn trait_core_role(&self) -> u32 {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::TraitCoreRole(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_trait_core_role(&mut self) {
        self.NEBNJDMFELO = ::std::option::Option::None;
    }

    pub fn has_trait_core_role(&self) -> bool {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::TraitCoreRole(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_trait_core_role(&mut self, v: u32) {
        self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::TraitCoreRole(v))
    }

    // .NBPEJFHIKJL avatar_core_info = 277;

    pub fn avatar_core_info(&self) -> &super::NBPEJFHIKJL::NBPEJFHIKJL {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(ref v)) => v,
            _ => <super::NBPEJFHIKJL::NBPEJFHIKJL as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_avatar_core_info(&mut self) {
        self.NEBNJDMFELO = ::std::option::Option::None;
    }

    pub fn has_avatar_core_info(&self) -> bool {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_avatar_core_info(&mut self, v: super::NBPEJFHIKJL::NBPEJFHIKJL) {
        self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(v))
    }

    // Mutable pointer to the field.
    pub fn mut_avatar_core_info(&mut self) -> &mut super::NBPEJFHIKJL::NBPEJFHIKJL {
        if let ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(_)) = self.NEBNJDMFELO {
        } else {
            self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(super::NBPEJFHIKJL::NBPEJFHIKJL::new()));
        }
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_avatar_core_info(&mut self) -> super::NBPEJFHIKJL::NBPEJFHIKJL {
        if self.has_avatar_core_info() {
            match self.NEBNJDMFELO.take() {
                ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(v)) => v,
                _ => panic!(),
            }
        } else {
            super::NBPEJFHIKJL::NBPEJFHIKJL::new()
        }
    }

    // uint32 ECEMNCJBFOP = 1958;

    pub fn ECEMNCJBFOP(&self) -> u32 {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::ECEMNCJBFOP(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_ECEMNCJBFOP(&mut self) {
        self.NEBNJDMFELO = ::std::option::Option::None;
    }

    pub fn has_ECEMNCJBFOP(&self) -> bool {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::ECEMNCJBFOP(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_ECEMNCJBFOP(&mut self, v: u32) {
        self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::ECEMNCJBFOP(v))
    }

    // .CHKCPJLBOGE JLCLHAKNMLL = 564;

    pub fn JLCLHAKNMLL(&self) -> &super::CHKCPJLBOGE::CHKCPJLBOGE {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(ref v)) => v,
            _ => <super::CHKCPJLBOGE::CHKCPJLBOGE as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_JLCLHAKNMLL(&mut self) {
        self.NEBNJDMFELO = ::std::option::Option::None;
    }

    pub fn has_JLCLHAKNMLL(&self) -> bool {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_JLCLHAKNMLL(&mut self, v: super::CHKCPJLBOGE::CHKCPJLBOGE) {
        self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(v))
    }

    // Mutable pointer to the field.
    pub fn mut_JLCLHAKNMLL(&mut self) -> &mut super::CHKCPJLBOGE::CHKCPJLBOGE {
        if let ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(_)) = self.NEBNJDMFELO {
        } else {
            self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(super::CHKCPJLBOGE::CHKCPJLBOGE::new()));
        }
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_JLCLHAKNMLL(&mut self) -> super::CHKCPJLBOGE::CHKCPJLBOGE {
        if self.has_JLCLHAKNMLL() {
            match self.NEBNJDMFELO.take() {
                ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(v)) => v,
                _ => panic!(),
            }
        } else {
            super::CHKCPJLBOGE::CHKCPJLBOGE::new()
        }
    }

    // .BJFLPMNPFFK MPHGIPCONLF = 964;

    pub fn MPHGIPCONLF(&self) -> &super::BJFLPMNPFFK::BJFLPMNPFFK {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(ref v)) => v,
            _ => <super::BJFLPMNPFFK::BJFLPMNPFFK as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_MPHGIPCONLF(&mut self) {
        self.NEBNJDMFELO = ::std::option::Option::None;
    }

    pub fn has_MPHGIPCONLF(&self) -> bool {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_MPHGIPCONLF(&mut self, v: super::BJFLPMNPFFK::BJFLPMNPFFK) {
        self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_MPHGIPCONLF(&mut self) -> &mut super::BJFLPMNPFFK::BJFLPMNPFFK {
        if let ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(_)) = self.NEBNJDMFELO {
        } else {
            self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(super::BJFLPMNPFFK::BJFLPMNPFFK::new()));
        }
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_MPHGIPCONLF(&mut self) -> super::BJFLPMNPFFK::BJFLPMNPFFK {
        if self.has_MPHGIPCONLF() {
            match self.NEBNJDMFELO.take() {
                ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::BJFLPMNPFFK::BJFLPMNPFFK::new()
        }
    }

    // .HJCFNEPJKDM KJFIOEPKOBM = 311;

    pub fn KJFIOEPKOBM(&self) -> &super::HJCFNEPJKDM::HJCFNEPJKDM {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(ref v)) => v,
            _ => <super::HJCFNEPJKDM::HJCFNEPJKDM as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_KJFIOEPKOBM(&mut self) {
        self.NEBNJDMFELO = ::std::option::Option::None;
    }

    pub fn has_KJFIOEPKOBM(&self) -> bool {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_KJFIOEPKOBM(&mut self, v: super::HJCFNEPJKDM::HJCFNEPJKDM) {
        self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(v))
    }

    // Mutable pointer to the field.
    pub fn mut_KJFIOEPKOBM(&mut self) -> &mut super::HJCFNEPJKDM::HJCFNEPJKDM {
        if let ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(_)) = self.NEBNJDMFELO {
        } else {
            self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(super::HJCFNEPJKDM::HJCFNEPJKDM::new()));
        }
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_KJFIOEPKOBM(&mut self) -> super::HJCFNEPJKDM::HJCFNEPJKDM {
        if self.has_KJFIOEPKOBM() {
            match self.NEBNJDMFELO.take() {
                ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(v)) => v,
                _ => panic!(),
            }
        } else {
            super::HJCFNEPJKDM::HJCFNEPJKDM::new()
        }
    }

    // .LDMNIHIFDFG KOEPOCADLDI = 195;

    pub fn KOEPOCADLDI(&self) -> &super::LDMNIHIFDFG::LDMNIHIFDFG {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(ref v)) => v,
            _ => <super::LDMNIHIFDFG::LDMNIHIFDFG as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_KOEPOCADLDI(&mut self) {
        self.NEBNJDMFELO = ::std::option::Option::None;
    }

    pub fn has_KOEPOCADLDI(&self) -> bool {
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_KOEPOCADLDI(&mut self, v: super::LDMNIHIFDFG::LDMNIHIFDFG) {
        self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(v))
    }

    // Mutable pointer to the field.
    pub fn mut_KOEPOCADLDI(&mut self) -> &mut super::LDMNIHIFDFG::LDMNIHIFDFG {
        if let ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(_)) = self.NEBNJDMFELO {
        } else {
            self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(super::LDMNIHIFDFG::LDMNIHIFDFG::new()));
        }
        match self.NEBNJDMFELO {
            ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_KOEPOCADLDI(&mut self) -> super::LDMNIHIFDFG::LDMNIHIFDFG {
        if self.has_KOEPOCADLDI() {
            match self.NEBNJDMFELO.take() {
                ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(v)) => v,
                _ => panic!(),
            }
        } else {
            super::LDMNIHIFDFG::LDMNIHIFDFG::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "effect_id",
            |m: &H_53156b9a| { &m.effect_id },
            |m: &mut H_53156b9a| { &mut m.effect_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "trait_core_role",
            H_53156b9a::has_trait_core_role,
            H_53156b9a::trait_core_role,
            H_53156b9a::set_trait_core_role,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::NBPEJFHIKJL::NBPEJFHIKJL>(
            "avatar_core_info",
            H_53156b9a::has_avatar_core_info,
            H_53156b9a::avatar_core_info,
            H_53156b9a::mut_avatar_core_info,
            H_53156b9a::set_avatar_core_info,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "ECEMNCJBFOP",
            H_53156b9a::has_ECEMNCJBFOP,
            H_53156b9a::ECEMNCJBFOP,
            H_53156b9a::set_ECEMNCJBFOP,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::CHKCPJLBOGE::CHKCPJLBOGE>(
            "JLCLHAKNMLL",
            H_53156b9a::has_JLCLHAKNMLL,
            H_53156b9a::JLCLHAKNMLL,
            H_53156b9a::mut_JLCLHAKNMLL,
            H_53156b9a::set_JLCLHAKNMLL,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::BJFLPMNPFFK::BJFLPMNPFFK>(
            "MPHGIPCONLF",
            H_53156b9a::has_MPHGIPCONLF,
            H_53156b9a::MPHGIPCONLF,
            H_53156b9a::mut_MPHGIPCONLF,
            H_53156b9a::set_MPHGIPCONLF,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::HJCFNEPJKDM::HJCFNEPJKDM>(
            "KJFIOEPKOBM",
            H_53156b9a::has_KJFIOEPKOBM,
            H_53156b9a::KJFIOEPKOBM,
            H_53156b9a::mut_KJFIOEPKOBM,
            H_53156b9a::set_KJFIOEPKOBM,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::LDMNIHIFDFG::LDMNIHIFDFG>(
            "KOEPOCADLDI",
            H_53156b9a::has_KOEPOCADLDI,
            H_53156b9a::KOEPOCADLDI,
            H_53156b9a::mut_KOEPOCADLDI,
            H_53156b9a::set_KOEPOCADLDI,
        ));
        oneofs.push(h_53156b9a::NEBNJDMFELO::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_53156b9a>(
            "H_53156b9a",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_53156b9a {
    const NAME: &'static str = "H_53156b9a";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                16 => {
                    self.effect_id = is.read_uint32()?;
                },
                14600 => {
                    self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::TraitCoreRole(is.read_uint32()?));
                },
                2218 => {
                    self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(is.read_message()?));
                },
                15664 => {
                    self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::ECEMNCJBFOP(is.read_uint32()?));
                },
                4514 => {
                    self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(is.read_message()?));
                },
                7714 => {
                    self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(is.read_message()?));
                },
                2490 => {
                    self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(is.read_message()?));
                },
                1562 => {
                    self.NEBNJDMFELO = ::std::option::Option::Some(h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.effect_id != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.effect_id);
        }
        if let ::std::option::Option::Some(ref v) = self.NEBNJDMFELO {
            match v {
                &h_53156b9a::NEBNJDMFELO::TraitCoreRole(v) => {
                    my_size += ::protobuf::rt::uint32_size(1825, v);
                },
                &h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &h_53156b9a::NEBNJDMFELO::ECEMNCJBFOP(v) => {
                    my_size += ::protobuf::rt::uint32_size(1958, v);
                },
                &h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.effect_id != 0 {
            os.write_uint32(2, self.effect_id)?;
        }
        if let ::std::option::Option::Some(ref v) = self.NEBNJDMFELO {
            match v {
                &h_53156b9a::NEBNJDMFELO::TraitCoreRole(v) => {
                    os.write_uint32(1825, v)?;
                },
                &h_53156b9a::NEBNJDMFELO::AvatarCoreInfo(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(277, v, os)?;
                },
                &h_53156b9a::NEBNJDMFELO::ECEMNCJBFOP(v) => {
                    os.write_uint32(1958, v)?;
                },
                &h_53156b9a::NEBNJDMFELO::JLCLHAKNMLL(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(564, v, os)?;
                },
                &h_53156b9a::NEBNJDMFELO::MPHGIPCONLF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(964, v, os)?;
                },
                &h_53156b9a::NEBNJDMFELO::KJFIOEPKOBM(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(311, v, os)?;
                },
                &h_53156b9a::NEBNJDMFELO::KOEPOCADLDI(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(195, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_53156b9a {
        H_53156b9a::new()
    }

    fn clear(&mut self) {
        self.effect_id = 0;
        self.NEBNJDMFELO = ::std::option::Option::None;
        self.NEBNJDMFELO = ::std::option::Option::None;
        self.NEBNJDMFELO = ::std::option::Option::None;
        self.NEBNJDMFELO = ::std::option::Option::None;
        self.NEBNJDMFELO = ::std::option::Option::None;
        self.NEBNJDMFELO = ::std::option::Option::None;
        self.NEBNJDMFELO = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_53156b9a {
        static instance: H_53156b9a = H_53156b9a {
            effect_id: 0,
            NEBNJDMFELO: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for H_53156b9a {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_53156b9a").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_53156b9a {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_53156b9a {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `H_53156b9a`
pub mod h_53156b9a {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:H_53156b9a.NEBNJDMFELO)
    pub enum NEBNJDMFELO {
        // @@protoc_insertion_point(oneof_field:H_53156b9a.trait_core_role)
        TraitCoreRole(u32),
        // @@protoc_insertion_point(oneof_field:H_53156b9a.avatar_core_info)
        AvatarCoreInfo(super::super::NBPEJFHIKJL::NBPEJFHIKJL),
        // @@protoc_insertion_point(oneof_field:H_53156b9a.ECEMNCJBFOP)
        ECEMNCJBFOP(u32),
        // @@protoc_insertion_point(oneof_field:H_53156b9a.JLCLHAKNMLL)
        JLCLHAKNMLL(super::super::CHKCPJLBOGE::CHKCPJLBOGE),
        // @@protoc_insertion_point(oneof_field:H_53156b9a.MPHGIPCONLF)
        MPHGIPCONLF(super::super::BJFLPMNPFFK::BJFLPMNPFFK),
        // @@protoc_insertion_point(oneof_field:H_53156b9a.KJFIOEPKOBM)
        KJFIOEPKOBM(super::super::HJCFNEPJKDM::HJCFNEPJKDM),
        // @@protoc_insertion_point(oneof_field:H_53156b9a.KOEPOCADLDI)
        KOEPOCADLDI(super::super::LDMNIHIFDFG::LDMNIHIFDFG),
    }

    impl ::protobuf::Oneof for NEBNJDMFELO {
    }

    impl ::protobuf::OneofFull for NEBNJDMFELO {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::H_53156b9a as ::protobuf::MessageFull>::descriptor().oneof_by_name("NEBNJDMFELO").unwrap()).clone()
        }
    }

    impl NEBNJDMFELO {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<NEBNJDMFELO>("NEBNJDMFELO")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_53156b9a.proto\x1a\x11BJFLPMNPFFK.proto\x1a\x11CHKCPJLBOGE.proto\
    \x1a\x11HJCFNEPJKDM.proto\x1a\x11LDMNIHIFDFG.proto\x1a\x11NBPEJFHIKJL.pr\
    oto\"\x8f\x03\n\nH_53156b9a\x12\x1b\n\teffect_id\x18\x02\x20\x01(\rR\x08\
    effectId\x12)\n\x0ftrait_core_role\x18\xa1\x0e\x20\x01(\rH\0R\rtraitCore\
    Role\x129\n\x10avatar_core_info\x18\x95\x02\x20\x01(\x0b2\x0c.NBPEJFHIKJ\
    LH\0R\x0eavatarCoreInfo\x12#\n\x0bECEMNCJBFOP\x18\xa6\x0f\x20\x01(\rH\0R\
    \x0bECEMNCJBFOP\x121\n\x0bJLCLHAKNMLL\x18\xb4\x04\x20\x01(\x0b2\x0c.CHKC\
    PJLBOGEH\0R\x0bJLCLHAKNMLL\x121\n\x0bMPHGIPCONLF\x18\xc4\x07\x20\x01(\
    \x0b2\x0c.BJFLPMNPFFKH\0R\x0bMPHGIPCONLF\x121\n\x0bKJFIOEPKOBM\x18\xb7\
    \x02\x20\x01(\x0b2\x0c.HJCFNEPJKDMH\0R\x0bKJFIOEPKOBM\x121\n\x0bKOEPOCAD\
    LDI\x18\xc3\x01\x20\x01(\x0b2\x0c.LDMNIHIFDFGH\0R\x0bKOEPOCADLDIB\r\n\
    \x0bNEBNJDMFELOb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(5);
            deps.push(super::BJFLPMNPFFK::file_descriptor().clone());
            deps.push(super::CHKCPJLBOGE::file_descriptor().clone());
            deps.push(super::HJCFNEPJKDM::file_descriptor().clone());
            deps.push(super::LDMNIHIFDFG::file_descriptor().clone());
            deps.push(super::NBPEJFHIKJL::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_53156b9a::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
