// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_66161552.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_66161552)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_66161552 {
    // message fields
    // @@protoc_insertion_point(field:H_66161552.PJBIPMKACOF)
    pub PJBIPMKACOF: ::protobuf::MessageField<super::H_5ecffc59::H_5ecffc59>,
    // @@protoc_insertion_point(field:H_66161552.EJHDGLHCNLH)
    pub EJHDGLHCNLH: ::protobuf::MessageField<super::H_322fddbd::H_322fddbd>,
    // @@protoc_insertion_point(field:H_66161552.DNEGDNEBJMB)
    pub DNEGDNEBJMB: ::protobuf::MessageField<super::H_89a57c54::H_89a57c54>,
    // @@protoc_insertion_point(field:H_66161552.JLFANEOAHOC)
    pub JLFANEOAHOC: ::protobuf::MessageField<super::H_74c875f4::H_74c875f4>,
    // @@protoc_insertion_point(field:H_66161552.NIOAIKLPACM)
    pub NIOAIKLPACM: ::protobuf::MessageField<super::H_16dc6d4f::H_16dc6d4f>,
    // special fields
    // @@protoc_insertion_point(special_field:H_66161552.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_66161552 {
    fn default() -> &'a H_66161552 {
        <H_66161552 as ::protobuf::Message>::default_instance()
    }
}

impl H_66161552 {
    pub fn new() -> H_66161552 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::H_5ecffc59::H_5ecffc59>(
            "PJBIPMKACOF",
            |m: &H_66161552| { &m.PJBIPMKACOF },
            |m: &mut H_66161552| { &mut m.PJBIPMKACOF },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::H_322fddbd::H_322fddbd>(
            "EJHDGLHCNLH",
            |m: &H_66161552| { &m.EJHDGLHCNLH },
            |m: &mut H_66161552| { &mut m.EJHDGLHCNLH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::H_89a57c54::H_89a57c54>(
            "DNEGDNEBJMB",
            |m: &H_66161552| { &m.DNEGDNEBJMB },
            |m: &mut H_66161552| { &mut m.DNEGDNEBJMB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::H_74c875f4::H_74c875f4>(
            "JLFANEOAHOC",
            |m: &H_66161552| { &m.JLFANEOAHOC },
            |m: &mut H_66161552| { &mut m.JLFANEOAHOC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::H_16dc6d4f::H_16dc6d4f>(
            "NIOAIKLPACM",
            |m: &H_66161552| { &m.NIOAIKLPACM },
            |m: &mut H_66161552| { &mut m.NIOAIKLPACM },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_66161552>(
            "H_66161552",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_66161552 {
    const NAME: &'static str = "H_66161552";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.PJBIPMKACOF)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.EJHDGLHCNLH)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.DNEGDNEBJMB)?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.JLFANEOAHOC)?;
                },
                122 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.NIOAIKLPACM)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.PJBIPMKACOF.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.EJHDGLHCNLH.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.DNEGDNEBJMB.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.JLFANEOAHOC.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.NIOAIKLPACM.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.PJBIPMKACOF.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.EJHDGLHCNLH.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.DNEGDNEBJMB.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if let Some(v) = self.JLFANEOAHOC.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        if let Some(v) = self.NIOAIKLPACM.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(15, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_66161552 {
        H_66161552::new()
    }

    fn clear(&mut self) {
        self.PJBIPMKACOF.clear();
        self.EJHDGLHCNLH.clear();
        self.DNEGDNEBJMB.clear();
        self.JLFANEOAHOC.clear();
        self.NIOAIKLPACM.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_66161552 {
        static instance: H_66161552 = H_66161552 {
            PJBIPMKACOF: ::protobuf::MessageField::none(),
            EJHDGLHCNLH: ::protobuf::MessageField::none(),
            DNEGDNEBJMB: ::protobuf::MessageField::none(),
            JLFANEOAHOC: ::protobuf::MessageField::none(),
            NIOAIKLPACM: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for H_66161552 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_66161552").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_66161552 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_66161552 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_66161552.proto\x1a\x10H_16dc6d4f.proto\x1a\x10H_322fddbd.proto\
    \x1a\x10H_5ecffc59.proto\x1a\x10H_74c875f4.proto\x1a\x10H_89a57c54.proto\
    \"\xf7\x01\n\nH_66161552\x12-\n\x0bPJBIPMKACOF\x18\x02\x20\x01(\x0b2\x0b\
    .H_5ecffc59R\x0bPJBIPMKACOF\x12-\n\x0bEJHDGLHCNLH\x18\x03\x20\x01(\x0b2\
    \x0b.H_322fddbdR\x0bEJHDGLHCNLH\x12-\n\x0bDNEGDNEBJMB\x18\x08\x20\x01(\
    \x0b2\x0b.H_89a57c54R\x0bDNEGDNEBJMB\x12-\n\x0bJLFANEOAHOC\x18\n\x20\x01\
    (\x0b2\x0b.H_74c875f4R\x0bJLFANEOAHOC\x12-\n\x0bNIOAIKLPACM\x18\x0f\x20\
    \x01(\x0b2\x0b.H_16dc6d4fR\x0bNIOAIKLPACMb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(5);
            deps.push(super::H_16dc6d4f::file_descriptor().clone());
            deps.push(super::H_322fddbd::file_descriptor().clone());
            deps.push(super::H_5ecffc59::file_descriptor().clone());
            deps.push(super::H_74c875f4::file_descriptor().clone());
            deps.push(super::H_89a57c54::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_66161552::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
