// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_74c875f4.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_74c875f4)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_74c875f4 {
    // message fields
    // @@protoc_insertion_point(field:H_74c875f4.DDIFKADGIBO)
    pub DDIFKADGIBO: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:H_74c875f4.JICIBCFDHIH)
    pub JICIBCFDHIH: ::std::vec::Vec<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:H_74c875f4.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_74c875f4 {
    fn default() -> &'a H_74c875f4 {
        <H_74c875f4 as ::protobuf::Message>::default_instance()
    }
}

impl H_74c875f4 {
    pub fn new() -> H_74c875f4 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "DDIFKADGIBO",
            |m: &H_74c875f4| { &m.DDIFKADGIBO },
            |m: &mut H_74c875f4| { &mut m.DDIFKADGIBO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "JICIBCFDHIH",
            |m: &H_74c875f4| { &m.JICIBCFDHIH },
            |m: &mut H_74c875f4| { &mut m.JICIBCFDHIH },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_74c875f4>(
            "H_74c875f4",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_74c875f4 {
    const NAME: &'static str = "H_74c875f4";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    is.read_repeated_packed_uint32_into(&mut self.DDIFKADGIBO)?;
                },
                8 => {
                    self.DDIFKADGIBO.push(is.read_uint32()?);
                },
                106 => {
                    is.read_repeated_packed_uint32_into(&mut self.JICIBCFDHIH)?;
                },
                104 => {
                    self.JICIBCFDHIH.push(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint32_size(1, &self.DDIFKADGIBO);
        my_size += ::protobuf::rt::vec_packed_uint32_size(13, &self.JICIBCFDHIH);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint32(1, &self.DDIFKADGIBO)?;
        os.write_repeated_packed_uint32(13, &self.JICIBCFDHIH)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_74c875f4 {
        H_74c875f4::new()
    }

    fn clear(&mut self) {
        self.DDIFKADGIBO.clear();
        self.JICIBCFDHIH.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_74c875f4 {
        static instance: H_74c875f4 = H_74c875f4 {
            DDIFKADGIBO: ::std::vec::Vec::new(),
            JICIBCFDHIH: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for H_74c875f4 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_74c875f4").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_74c875f4 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_74c875f4 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_74c875f4.proto\"P\n\nH_74c875f4\x12\x20\n\x0bDDIFKADGIBO\x18\x01\
    \x20\x03(\rR\x0bDDIFKADGIBO\x12\x20\n\x0bJICIBCFDHIH\x18\r\x20\x03(\rR\
    \x0bJICIBCFDHIHb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_74c875f4::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
