// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_812844e8.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_812844e8)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_812844e8 {
    // message fields
    // @@protoc_insertion_point(field:H_812844e8.FLHOPMMEGAI)
    pub FLHOPMMEGAI: u32,
    // @@protoc_insertion_point(field:H_812844e8.GEBGGMAGDJB)
    pub GEBGGMAGDJB: u32,
    // @@protoc_insertion_point(field:H_812844e8.CDANKDNACJP)
    pub CDANKDNACJP: u32,
    // @@protoc_insertion_point(field:H_812844e8.EDHKHJAPMKA)
    pub EDHKHJAPMKA: u32,
    // @@protoc_insertion_point(field:H_812844e8.KEJGCDOGEDD)
    pub KEJGCDOGEDD: u32,
    // @@protoc_insertion_point(field:H_812844e8.NMCKJPEMACM)
    pub NMCKJPEMACM: u32,
    // @@protoc_insertion_point(field:H_812844e8.MNNKKEPCPPL)
    pub MNNKKEPCPPL: u32,
    // @@protoc_insertion_point(field:H_812844e8.BFLLJJBHLDF)
    pub BFLLJJBHLDF: ::protobuf::MessageField<super::H_57693b8d::H_57693b8d>,
    // @@protoc_insertion_point(field:H_812844e8.CGKNDIJMOCJ)
    pub CGKNDIJMOCJ: u32,
    // special fields
    // @@protoc_insertion_point(special_field:H_812844e8.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_812844e8 {
    fn default() -> &'a H_812844e8 {
        <H_812844e8 as ::protobuf::Message>::default_instance()
    }
}

impl H_812844e8 {
    pub fn new() -> H_812844e8 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(9);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "FLHOPMMEGAI",
            |m: &H_812844e8| { &m.FLHOPMMEGAI },
            |m: &mut H_812844e8| { &mut m.FLHOPMMEGAI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GEBGGMAGDJB",
            |m: &H_812844e8| { &m.GEBGGMAGDJB },
            |m: &mut H_812844e8| { &mut m.GEBGGMAGDJB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CDANKDNACJP",
            |m: &H_812844e8| { &m.CDANKDNACJP },
            |m: &mut H_812844e8| { &mut m.CDANKDNACJP },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EDHKHJAPMKA",
            |m: &H_812844e8| { &m.EDHKHJAPMKA },
            |m: &mut H_812844e8| { &mut m.EDHKHJAPMKA },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KEJGCDOGEDD",
            |m: &H_812844e8| { &m.KEJGCDOGEDD },
            |m: &mut H_812844e8| { &mut m.KEJGCDOGEDD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NMCKJPEMACM",
            |m: &H_812844e8| { &m.NMCKJPEMACM },
            |m: &mut H_812844e8| { &mut m.NMCKJPEMACM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MNNKKEPCPPL",
            |m: &H_812844e8| { &m.MNNKKEPCPPL },
            |m: &mut H_812844e8| { &mut m.MNNKKEPCPPL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::H_57693b8d::H_57693b8d>(
            "BFLLJJBHLDF",
            |m: &H_812844e8| { &m.BFLLJJBHLDF },
            |m: &mut H_812844e8| { &mut m.BFLLJJBHLDF },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CGKNDIJMOCJ",
            |m: &H_812844e8| { &m.CGKNDIJMOCJ },
            |m: &mut H_812844e8| { &mut m.CGKNDIJMOCJ },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_812844e8>(
            "H_812844e8",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_812844e8 {
    const NAME: &'static str = "H_812844e8";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.FLHOPMMEGAI = is.read_uint32()?;
                },
                64 => {
                    self.GEBGGMAGDJB = is.read_uint32()?;
                },
                72 => {
                    self.CDANKDNACJP = is.read_uint32()?;
                },
                96 => {
                    self.EDHKHJAPMKA = is.read_uint32()?;
                },
                112 => {
                    self.KEJGCDOGEDD = is.read_uint32()?;
                },
                120 => {
                    self.NMCKJPEMACM = is.read_uint32()?;
                },
                3704 => {
                    self.MNNKKEPCPPL = is.read_uint32()?;
                },
                6378 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.BFLLJJBHLDF)?;
                },
                11512 => {
                    self.CGKNDIJMOCJ = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.FLHOPMMEGAI != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.FLHOPMMEGAI);
        }
        if self.GEBGGMAGDJB != 0 {
            my_size += ::protobuf::rt::uint32_size(8, self.GEBGGMAGDJB);
        }
        if self.CDANKDNACJP != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.CDANKDNACJP);
        }
        if self.EDHKHJAPMKA != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.EDHKHJAPMKA);
        }
        if self.KEJGCDOGEDD != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.KEJGCDOGEDD);
        }
        if self.NMCKJPEMACM != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.NMCKJPEMACM);
        }
        if self.MNNKKEPCPPL != 0 {
            my_size += ::protobuf::rt::uint32_size(463, self.MNNKKEPCPPL);
        }
        if let Some(v) = self.BFLLJJBHLDF.as_ref() {
            let len = v.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.CGKNDIJMOCJ != 0 {
            my_size += ::protobuf::rt::uint32_size(1439, self.CGKNDIJMOCJ);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.FLHOPMMEGAI != 0 {
            os.write_uint32(1, self.FLHOPMMEGAI)?;
        }
        if self.GEBGGMAGDJB != 0 {
            os.write_uint32(8, self.GEBGGMAGDJB)?;
        }
        if self.CDANKDNACJP != 0 {
            os.write_uint32(9, self.CDANKDNACJP)?;
        }
        if self.EDHKHJAPMKA != 0 {
            os.write_uint32(12, self.EDHKHJAPMKA)?;
        }
        if self.KEJGCDOGEDD != 0 {
            os.write_uint32(14, self.KEJGCDOGEDD)?;
        }
        if self.NMCKJPEMACM != 0 {
            os.write_uint32(15, self.NMCKJPEMACM)?;
        }
        if self.MNNKKEPCPPL != 0 {
            os.write_uint32(463, self.MNNKKEPCPPL)?;
        }
        if let Some(v) = self.BFLLJJBHLDF.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(797, v, os)?;
        }
        if self.CGKNDIJMOCJ != 0 {
            os.write_uint32(1439, self.CGKNDIJMOCJ)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_812844e8 {
        H_812844e8::new()
    }

    fn clear(&mut self) {
        self.FLHOPMMEGAI = 0;
        self.GEBGGMAGDJB = 0;
        self.CDANKDNACJP = 0;
        self.EDHKHJAPMKA = 0;
        self.KEJGCDOGEDD = 0;
        self.NMCKJPEMACM = 0;
        self.MNNKKEPCPPL = 0;
        self.BFLLJJBHLDF.clear();
        self.CGKNDIJMOCJ = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_812844e8 {
        static instance: H_812844e8 = H_812844e8 {
            FLHOPMMEGAI: 0,
            GEBGGMAGDJB: 0,
            CDANKDNACJP: 0,
            EDHKHJAPMKA: 0,
            KEJGCDOGEDD: 0,
            NMCKJPEMACM: 0,
            MNNKKEPCPPL: 0,
            BFLLJJBHLDF: ::protobuf::MessageField::none(),
            CGKNDIJMOCJ: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for H_812844e8 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_812844e8").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_812844e8 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_812844e8 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_812844e8.proto\x1a\x10H_57693b8d.proto\"\xce\x02\n\nH_812844e8\
    \x12\x20\n\x0bFLHOPMMEGAI\x18\x01\x20\x01(\rR\x0bFLHOPMMEGAI\x12\x20\n\
    \x0bGEBGGMAGDJB\x18\x08\x20\x01(\rR\x0bGEBGGMAGDJB\x12\x20\n\x0bCDANKDNA\
    CJP\x18\t\x20\x01(\rR\x0bCDANKDNACJP\x12\x20\n\x0bEDHKHJAPMKA\x18\x0c\
    \x20\x01(\rR\x0bEDHKHJAPMKA\x12\x20\n\x0bKEJGCDOGEDD\x18\x0e\x20\x01(\rR\
    \x0bKEJGCDOGEDD\x12\x20\n\x0bNMCKJPEMACM\x18\x0f\x20\x01(\rR\x0bNMCKJPEM\
    ACM\x12!\n\x0bMNNKKEPCPPL\x18\xcf\x03\x20\x01(\rR\x0bMNNKKEPCPPL\x12.\n\
    \x0bBFLLJJBHLDF\x18\x9d\x06\x20\x01(\x0b2\x0b.H_57693b8dR\x0bBFLLJJBHLDF\
    \x12!\n\x0bCGKNDIJMOCJ\x18\x9f\x0b\x20\x01(\rR\x0bCGKNDIJMOCJb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::H_57693b8d::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_812844e8::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
