// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `H_ad30b0a1.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:H_ad30b0a1)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct H_ad30b0a1 {
    // message fields
    // @@protoc_insertion_point(field:H_ad30b0a1.CKJAKKNOHEK)
    pub CKJAKKNOHEK: ::std::vec::Vec<super::MBPDIPLJMKN::MBPDIPLJMKN>,
    // @@protoc_insertion_point(field:H_ad30b0a1.unique_id)
    pub unique_id: u32,
    // @@protoc_insertion_point(field:H_ad30b0a1.pos_index)
    pub pos_index: u32,
    // @@protoc_insertion_point(field:H_ad30b0a1.LCLPEJHEAID)
    pub LCLPEJHEAID: u32,
    // special fields
    // @@protoc_insertion_point(special_field:H_ad30b0a1.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a H_ad30b0a1 {
    fn default() -> &'a H_ad30b0a1 {
        <H_ad30b0a1 as ::protobuf::Message>::default_instance()
    }
}

impl H_ad30b0a1 {
    pub fn new() -> H_ad30b0a1 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "CKJAKKNOHEK",
            |m: &H_ad30b0a1| { &m.CKJAKKNOHEK },
            |m: &mut H_ad30b0a1| { &mut m.CKJAKKNOHEK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "unique_id",
            |m: &H_ad30b0a1| { &m.unique_id },
            |m: &mut H_ad30b0a1| { &mut m.unique_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "pos_index",
            |m: &H_ad30b0a1| { &m.pos_index },
            |m: &mut H_ad30b0a1| { &mut m.pos_index },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "LCLPEJHEAID",
            |m: &H_ad30b0a1| { &m.LCLPEJHEAID },
            |m: &mut H_ad30b0a1| { &mut m.LCLPEJHEAID },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<H_ad30b0a1>(
            "H_ad30b0a1",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for H_ad30b0a1 {
    const NAME: &'static str = "H_ad30b0a1";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                26 => {
                    self.CKJAKKNOHEK.push(is.read_message()?);
                },
                72 => {
                    self.unique_id = is.read_uint32()?;
                },
                80 => {
                    self.pos_index = is.read_uint32()?;
                },
                104 => {
                    self.LCLPEJHEAID = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.CKJAKKNOHEK {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.unique_id != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.unique_id);
        }
        if self.pos_index != 0 {
            my_size += ::protobuf::rt::uint32_size(10, self.pos_index);
        }
        if self.LCLPEJHEAID != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.LCLPEJHEAID);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.CKJAKKNOHEK {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        if self.unique_id != 0 {
            os.write_uint32(9, self.unique_id)?;
        }
        if self.pos_index != 0 {
            os.write_uint32(10, self.pos_index)?;
        }
        if self.LCLPEJHEAID != 0 {
            os.write_uint32(13, self.LCLPEJHEAID)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> H_ad30b0a1 {
        H_ad30b0a1::new()
    }

    fn clear(&mut self) {
        self.CKJAKKNOHEK.clear();
        self.unique_id = 0;
        self.pos_index = 0;
        self.LCLPEJHEAID = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static H_ad30b0a1 {
        static instance: H_ad30b0a1 = H_ad30b0a1 {
            CKJAKKNOHEK: ::std::vec::Vec::new(),
            unique_id: 0,
            pos_index: 0,
            LCLPEJHEAID: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for H_ad30b0a1 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("H_ad30b0a1").unwrap()).clone()
    }
}

impl ::std::fmt::Display for H_ad30b0a1 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for H_ad30b0a1 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10H_ad30b0a1.proto\x1a\x11MBPDIPLJMKN.proto\"\x98\x01\n\nH_ad30b0a1\
    \x12.\n\x0bCKJAKKNOHEK\x18\x03\x20\x03(\x0b2\x0c.MBPDIPLJMKNR\x0bCKJAKKN\
    OHEK\x12\x1b\n\tunique_id\x18\t\x20\x01(\rR\x08uniqueId\x12\x1b\n\tpos_i\
    ndex\x18\n\x20\x01(\rR\x08posIndex\x12\x20\n\x0bLCLPEJHEAID\x18\r\x20\
    \x01(\rR\x0bLCLPEJHEAIDb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::MBPDIPLJMKN::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(H_ad30b0a1::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
