// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `HPGIGMPBIBO.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:HPGIGMPBIBO)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HPGIGMPBIBO {
    // message fields
    // @@protoc_insertion_point(field:HPGIGMPBIBO.BKIIJELPNPL)
    pub BKIIJELPNPL: ::std::string::String,
    // @@protoc_insertion_point(field:HPGIGMPBIBO.HPGJPOFOOPM)
    pub HPGJPOFOOPM: u32,
    // @@protoc_insertion_point(field:HPGIGMPBIBO.retcode)
    pub retcode: u32,
    // @@protoc_insertion_point(field:HPGIGMPBIBO.AJHCNDDFMJO)
    pub AJHCNDDFMJO: ::std::string::String,
    // @@protoc_insertion_point(field:HPGIGMPBIBO.FGNFDGAKKAP)
    pub FGNFDGAKKAP: u64,
    // special fields
    // @@protoc_insertion_point(special_field:HPGIGMPBIBO.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HPGIGMPBIBO {
    fn default() -> &'a HPGIGMPBIBO {
        <HPGIGMPBIBO as ::protobuf::Message>::default_instance()
    }
}

impl HPGIGMPBIBO {
    pub fn new() -> HPGIGMPBIBO {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "BKIIJELPNPL",
            |m: &HPGIGMPBIBO| { &m.BKIIJELPNPL },
            |m: &mut HPGIGMPBIBO| { &mut m.BKIIJELPNPL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "HPGJPOFOOPM",
            |m: &HPGIGMPBIBO| { &m.HPGJPOFOOPM },
            |m: &mut HPGIGMPBIBO| { &mut m.HPGJPOFOOPM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retcode",
            |m: &HPGIGMPBIBO| { &m.retcode },
            |m: &mut HPGIGMPBIBO| { &mut m.retcode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AJHCNDDFMJO",
            |m: &HPGIGMPBIBO| { &m.AJHCNDDFMJO },
            |m: &mut HPGIGMPBIBO| { &mut m.AJHCNDDFMJO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "FGNFDGAKKAP",
            |m: &HPGIGMPBIBO| { &m.FGNFDGAKKAP },
            |m: &mut HPGIGMPBIBO| { &mut m.FGNFDGAKKAP },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<HPGIGMPBIBO>(
            "HPGIGMPBIBO",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for HPGIGMPBIBO {
    const NAME: &'static str = "HPGIGMPBIBO";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.BKIIJELPNPL = is.read_string()?;
                },
                16 => {
                    self.HPGJPOFOOPM = is.read_uint32()?;
                },
                32 => {
                    self.retcode = is.read_uint32()?;
                },
                90 => {
                    self.AJHCNDDFMJO = is.read_string()?;
                },
                120 => {
                    self.FGNFDGAKKAP = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.BKIIJELPNPL.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.BKIIJELPNPL);
        }
        if self.HPGJPOFOOPM != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.HPGJPOFOOPM);
        }
        if self.retcode != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.retcode);
        }
        if !self.AJHCNDDFMJO.is_empty() {
            my_size += ::protobuf::rt::string_size(11, &self.AJHCNDDFMJO);
        }
        if self.FGNFDGAKKAP != 0 {
            my_size += ::protobuf::rt::uint64_size(15, self.FGNFDGAKKAP);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.BKIIJELPNPL.is_empty() {
            os.write_string(1, &self.BKIIJELPNPL)?;
        }
        if self.HPGJPOFOOPM != 0 {
            os.write_uint32(2, self.HPGJPOFOOPM)?;
        }
        if self.retcode != 0 {
            os.write_uint32(4, self.retcode)?;
        }
        if !self.AJHCNDDFMJO.is_empty() {
            os.write_string(11, &self.AJHCNDDFMJO)?;
        }
        if self.FGNFDGAKKAP != 0 {
            os.write_uint64(15, self.FGNFDGAKKAP)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HPGIGMPBIBO {
        HPGIGMPBIBO::new()
    }

    fn clear(&mut self) {
        self.BKIIJELPNPL.clear();
        self.HPGJPOFOOPM = 0;
        self.retcode = 0;
        self.AJHCNDDFMJO.clear();
        self.FGNFDGAKKAP = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HPGIGMPBIBO {
        static instance: HPGIGMPBIBO = HPGIGMPBIBO {
            BKIIJELPNPL: ::std::string::String::new(),
            HPGJPOFOOPM: 0,
            retcode: 0,
            AJHCNDDFMJO: ::std::string::String::new(),
            FGNFDGAKKAP: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for HPGIGMPBIBO {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("HPGIGMPBIBO").unwrap()).clone()
    }
}

impl ::std::fmt::Display for HPGIGMPBIBO {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HPGIGMPBIBO {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11HPGIGMPBIBO.proto\"\xaf\x01\n\x0bHPGIGMPBIBO\x12\x20\n\x0bBKIIJELP\
    NPL\x18\x01\x20\x01(\tR\x0bBKIIJELPNPL\x12\x20\n\x0bHPGJPOFOOPM\x18\x02\
    \x20\x01(\rR\x0bHPGJPOFOOPM\x12\x18\n\x07retcode\x18\x04\x20\x01(\rR\x07\
    retcode\x12\x20\n\x0bAJHCNDDFMJO\x18\x0b\x20\x01(\tR\x0bAJHCNDDFMJO\x12\
    \x20\n\x0bFGNFDGAKKAP\x18\x0f\x20\x01(\x04R\x0bFGNFDGAKKAPb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(HPGIGMPBIBO::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
