// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `IKJDKNKJBGI.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:IKJDKNKJBGI)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct IKJDKNKJBGI {
    // message fields
    // @@protoc_insertion_point(field:IKJDKNKJBGI.GILJLEOAOMA)
    pub GILJLEOAOMA: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:IKJDKNKJBGI.event_id)
    pub event_id: u32,
    // @@protoc_insertion_point(field:IKJDKNKJBGI.type)
    pub type_: ::protobuf::EnumOrUnknown<super::FightFestType::FightFestType>,
    // @@protoc_insertion_point(field:IKJDKNKJBGI.id)
    pub id: u32,
    // @@protoc_insertion_point(field:IKJDKNKJBGI.avatar_list)
    pub avatar_list: ::std::vec::Vec<super::EPCNGNEEMBI::EPCNGNEEMBI>,
    // special fields
    // @@protoc_insertion_point(special_field:IKJDKNKJBGI.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a IKJDKNKJBGI {
    fn default() -> &'a IKJDKNKJBGI {
        <IKJDKNKJBGI as ::protobuf::Message>::default_instance()
    }
}

impl IKJDKNKJBGI {
    pub fn new() -> IKJDKNKJBGI {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "GILJLEOAOMA",
            |m: &IKJDKNKJBGI| { &m.GILJLEOAOMA },
            |m: &mut IKJDKNKJBGI| { &mut m.GILJLEOAOMA },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "event_id",
            |m: &IKJDKNKJBGI| { &m.event_id },
            |m: &mut IKJDKNKJBGI| { &mut m.event_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &IKJDKNKJBGI| { &m.type_ },
            |m: &mut IKJDKNKJBGI| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &IKJDKNKJBGI| { &m.id },
            |m: &mut IKJDKNKJBGI| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "avatar_list",
            |m: &IKJDKNKJBGI| { &m.avatar_list },
            |m: &mut IKJDKNKJBGI| { &mut m.avatar_list },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<IKJDKNKJBGI>(
            "IKJDKNKJBGI",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for IKJDKNKJBGI {
    const NAME: &'static str = "IKJDKNKJBGI";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                26 => {
                    is.read_repeated_packed_uint32_into(&mut self.GILJLEOAOMA)?;
                },
                24 => {
                    self.GILJLEOAOMA.push(is.read_uint32()?);
                },
                32 => {
                    self.event_id = is.read_uint32()?;
                },
                64 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                72 => {
                    self.id = is.read_uint32()?;
                },
                98 => {
                    self.avatar_list.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint32_size(3, &self.GILJLEOAOMA);
        if self.event_id != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.event_id);
        }
        if self.type_ != ::protobuf::EnumOrUnknown::new(super::FightFestType::FightFestType::FightFestType_None) {
            my_size += ::protobuf::rt::int32_size(8, self.type_.value());
        }
        if self.id != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.id);
        }
        for value in &self.avatar_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint32(3, &self.GILJLEOAOMA)?;
        if self.event_id != 0 {
            os.write_uint32(4, self.event_id)?;
        }
        if self.type_ != ::protobuf::EnumOrUnknown::new(super::FightFestType::FightFestType::FightFestType_None) {
            os.write_enum(8, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if self.id != 0 {
            os.write_uint32(9, self.id)?;
        }
        for v in &self.avatar_list {
            ::protobuf::rt::write_message_field_with_cached_size(12, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> IKJDKNKJBGI {
        IKJDKNKJBGI::new()
    }

    fn clear(&mut self) {
        self.GILJLEOAOMA.clear();
        self.event_id = 0;
        self.type_ = ::protobuf::EnumOrUnknown::new(super::FightFestType::FightFestType::FightFestType_None);
        self.id = 0;
        self.avatar_list.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static IKJDKNKJBGI {
        static instance: IKJDKNKJBGI = IKJDKNKJBGI {
            GILJLEOAOMA: ::std::vec::Vec::new(),
            event_id: 0,
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            id: 0,
            avatar_list: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for IKJDKNKJBGI {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("IKJDKNKJBGI").unwrap()).clone()
    }
}

impl ::std::fmt::Display for IKJDKNKJBGI {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for IKJDKNKJBGI {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11IKJDKNKJBGI.proto\x1a\x11EPCNGNEEMBI.proto\x1a\x13FightFestType.pr\
    oto\"\xad\x01\n\x0bIKJDKNKJBGI\x12\x20\n\x0bGILJLEOAOMA\x18\x03\x20\x03(\
    \rR\x0bGILJLEOAOMA\x12\x19\n\x08event_id\x18\x04\x20\x01(\rR\x07eventId\
    \x12\"\n\x04type\x18\x08\x20\x01(\x0e2\x0e.FightFestTypeR\x04type\x12\
    \x0e\n\x02id\x18\t\x20\x01(\rR\x02id\x12-\n\x0bavatar_list\x18\x0c\x20\
    \x03(\x0b2\x0c.EPCNGNEEMBIR\navatarListb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::EPCNGNEEMBI::file_descriptor().clone());
            deps.push(super::FightFestType::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(IKJDKNKJBGI::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
