// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ILHGAACMJHM.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:ILHGAACMJHM)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ILHGAACMJHM {
    // message fields
    // @@protoc_insertion_point(field:ILHGAACMJHM.KODOOHHPIKN)
    pub KODOOHHPIKN: u32,
    // @@protoc_insertion_point(field:ILHGAACMJHM.FMMICIHEOCM)
    pub FMMICIHEOCM: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:ILHGAACMJHM.GCKFOOIEHHA)
    pub GCKFOOIEHHA: u32,
    // special fields
    // @@protoc_insertion_point(special_field:ILHGAACMJHM.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ILHGAACMJHM {
    fn default() -> &'a ILHGAACMJHM {
        <ILHGAACMJHM as ::protobuf::Message>::default_instance()
    }
}

impl ILHGAACMJHM {
    pub fn new() -> ILHGAACMJHM {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KODOOHHPIKN",
            |m: &ILHGAACMJHM| { &m.KODOOHHPIKN },
            |m: &mut ILHGAACMJHM| { &mut m.KODOOHHPIKN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "FMMICIHEOCM",
            |m: &ILHGAACMJHM| { &m.FMMICIHEOCM },
            |m: &mut ILHGAACMJHM| { &mut m.FMMICIHEOCM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GCKFOOIEHHA",
            |m: &ILHGAACMJHM| { &m.GCKFOOIEHHA },
            |m: &mut ILHGAACMJHM| { &mut m.GCKFOOIEHHA },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ILHGAACMJHM>(
            "ILHGAACMJHM",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ILHGAACMJHM {
    const NAME: &'static str = "ILHGAACMJHM";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                32 => {
                    self.KODOOHHPIKN = is.read_uint32()?;
                },
                58 => {
                    is.read_repeated_packed_uint32_into(&mut self.FMMICIHEOCM)?;
                },
                56 => {
                    self.FMMICIHEOCM.push(is.read_uint32()?);
                },
                72 => {
                    self.GCKFOOIEHHA = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.KODOOHHPIKN != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.KODOOHHPIKN);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(7, &self.FMMICIHEOCM);
        if self.GCKFOOIEHHA != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.GCKFOOIEHHA);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.KODOOHHPIKN != 0 {
            os.write_uint32(4, self.KODOOHHPIKN)?;
        }
        os.write_repeated_packed_uint32(7, &self.FMMICIHEOCM)?;
        if self.GCKFOOIEHHA != 0 {
            os.write_uint32(9, self.GCKFOOIEHHA)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ILHGAACMJHM {
        ILHGAACMJHM::new()
    }

    fn clear(&mut self) {
        self.KODOOHHPIKN = 0;
        self.FMMICIHEOCM.clear();
        self.GCKFOOIEHHA = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ILHGAACMJHM {
        static instance: ILHGAACMJHM = ILHGAACMJHM {
            KODOOHHPIKN: 0,
            FMMICIHEOCM: ::std::vec::Vec::new(),
            GCKFOOIEHHA: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ILHGAACMJHM {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ILHGAACMJHM").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ILHGAACMJHM {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ILHGAACMJHM {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11ILHGAACMJHM.proto\"s\n\x0bILHGAACMJHM\x12\x20\n\x0bKODOOHHPIKN\x18\
    \x04\x20\x01(\rR\x0bKODOOHHPIKN\x12\x20\n\x0bFMMICIHEOCM\x18\x07\x20\x03\
    (\rR\x0bFMMICIHEOCM\x12\x20\n\x0bGCKFOOIEHHA\x18\t\x20\x01(\rR\x0bGCKFOO\
    IEHHAb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ILHGAACMJHM::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
