// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `JHHIAPCKHNP.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:JHHIAPCKHNP)
pub enum JHHIAPCKHNP {
    // @@protoc_insertion_point(enum_value:JHHIAPCKHNP.JHHIAPCKHNP_NLCDGIPGFDJ)
    JHHIAPCKHNP_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:JHHIAPCKHNP.JHHIAPCKHNP_KFHAMKCADGC)
    JHHIAPCKHNP_KFHAMKCADGC = 3083,
    // @@protoc_insertion_point(enum_value:JHHIAPCKHNP.JHHIAPCKHNP_MIHEMCONFHP)
    JHHIAPCKHNP_MIHEMCONFHP = 3081,
    // @@protoc_insertion_point(enum_value:JHHIAPCKHNP.JHHIAPCKHNP_IHPLLMHHMAB)
    JHHIAPCKHNP_IHPLLMHHMAB = 3024,
    // @@protoc_insertion_point(enum_value:JHHIAPCKHNP.JHHIAPCKHNP_AGLKDJBDJIE)
    JHHIAPCKHNP_AGLKDJBDJIE = 3078,
    // @@protoc_insertion_point(enum_value:JHHIAPCKHNP.JHHIAPCKHNP_ALNLCNAFKNH)
    JHHIAPCKHNP_ALNLCNAFKNH = 3019,
    // @@protoc_insertion_point(enum_value:JHHIAPCKHNP.JHHIAPCKHNP_HFFOHGAKFGJ)
    JHHIAPCKHNP_HFFOHGAKFGJ = 3044,
    // @@protoc_insertion_point(enum_value:JHHIAPCKHNP.JHHIAPCKHNP_KKMEJJDIHJA)
    JHHIAPCKHNP_KKMEJJDIHJA = 3032,
}

impl ::protobuf::Enum for JHHIAPCKHNP {
    const NAME: &'static str = "JHHIAPCKHNP";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<JHHIAPCKHNP> {
        match value {
            0 => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_NLCDGIPGFDJ),
            3083 => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_KFHAMKCADGC),
            3081 => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_MIHEMCONFHP),
            3024 => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_IHPLLMHHMAB),
            3078 => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_AGLKDJBDJIE),
            3019 => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_ALNLCNAFKNH),
            3044 => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_HFFOHGAKFGJ),
            3032 => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_KKMEJJDIHJA),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<JHHIAPCKHNP> {
        match str {
            "JHHIAPCKHNP_NLCDGIPGFDJ" => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_NLCDGIPGFDJ),
            "JHHIAPCKHNP_KFHAMKCADGC" => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_KFHAMKCADGC),
            "JHHIAPCKHNP_MIHEMCONFHP" => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_MIHEMCONFHP),
            "JHHIAPCKHNP_IHPLLMHHMAB" => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_IHPLLMHHMAB),
            "JHHIAPCKHNP_AGLKDJBDJIE" => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_AGLKDJBDJIE),
            "JHHIAPCKHNP_ALNLCNAFKNH" => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_ALNLCNAFKNH),
            "JHHIAPCKHNP_HFFOHGAKFGJ" => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_HFFOHGAKFGJ),
            "JHHIAPCKHNP_KKMEJJDIHJA" => ::std::option::Option::Some(JHHIAPCKHNP::JHHIAPCKHNP_KKMEJJDIHJA),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [JHHIAPCKHNP] = &[
        JHHIAPCKHNP::JHHIAPCKHNP_NLCDGIPGFDJ,
        JHHIAPCKHNP::JHHIAPCKHNP_KFHAMKCADGC,
        JHHIAPCKHNP::JHHIAPCKHNP_MIHEMCONFHP,
        JHHIAPCKHNP::JHHIAPCKHNP_IHPLLMHHMAB,
        JHHIAPCKHNP::JHHIAPCKHNP_AGLKDJBDJIE,
        JHHIAPCKHNP::JHHIAPCKHNP_ALNLCNAFKNH,
        JHHIAPCKHNP::JHHIAPCKHNP_HFFOHGAKFGJ,
        JHHIAPCKHNP::JHHIAPCKHNP_KKMEJJDIHJA,
    ];
}

impl ::protobuf::EnumFull for JHHIAPCKHNP {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("JHHIAPCKHNP").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            JHHIAPCKHNP::JHHIAPCKHNP_NLCDGIPGFDJ => 0,
            JHHIAPCKHNP::JHHIAPCKHNP_KFHAMKCADGC => 1,
            JHHIAPCKHNP::JHHIAPCKHNP_MIHEMCONFHP => 2,
            JHHIAPCKHNP::JHHIAPCKHNP_IHPLLMHHMAB => 3,
            JHHIAPCKHNP::JHHIAPCKHNP_AGLKDJBDJIE => 4,
            JHHIAPCKHNP::JHHIAPCKHNP_ALNLCNAFKNH => 5,
            JHHIAPCKHNP::JHHIAPCKHNP_HFFOHGAKFGJ => 6,
            JHHIAPCKHNP::JHHIAPCKHNP_KKMEJJDIHJA => 7,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for JHHIAPCKHNP {
    fn default() -> Self {
        JHHIAPCKHNP::JHHIAPCKHNP_NLCDGIPGFDJ
    }
}

impl JHHIAPCKHNP {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<JHHIAPCKHNP>("JHHIAPCKHNP")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11JHHIAPCKHNP.proto*\xfc\x01\n\x0bJHHIAPCKHNP\x12\x1b\n\x17JHHIAPCKH\
    NP_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17JHHIAPCKHNP_KFHAMKCADGC\x10\x8b\x18\
    \x12\x1c\n\x17JHHIAPCKHNP_MIHEMCONFHP\x10\x89\x18\x12\x1c\n\x17JHHIAPCKH\
    NP_IHPLLMHHMAB\x10\xd0\x17\x12\x1c\n\x17JHHIAPCKHNP_AGLKDJBDJIE\x10\x86\
    \x18\x12\x1c\n\x17JHHIAPCKHNP_ALNLCNAFKNH\x10\xcb\x17\x12\x1c\n\x17JHHIA\
    PCKHNP_HFFOHGAKFGJ\x10\xe4\x17\x12\x1c\n\x17JHHIAPCKHNP_KKMEJJDIHJA\x10\
    \xd8\x17b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(JHHIAPCKHNP::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
