// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `JKJGPOOLLKF.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:JKJGPOOLLKF)
pub enum JKJGPOOLLKF {
    // @@protoc_insertion_point(enum_value:JKJGPOOLLKF.JKJGPOOLLKF_NLCDGIPGFDJ)
    JKJGPOOLLKF_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:JKJGPOOLLKF.JKJGPOOLLKF_EPPMKBDPDBM)
    JKJGPOOLLKF_EPPMKBDPDBM = 5378,
    // @@protoc_insertion_point(enum_value:JKJGPOOLLKF.JKJGPOOLLKF_KKEHIBPDIEF)
    JKJGPOOLLKF_KKEHIBPDIEF = 5381,
    // @@protoc_insertion_point(enum_value:JKJGPOOLLKF.JKJGPOOLLKF_GALJIBIENIB)
    JKJGPOOLLKF_GALJIBIENIB = 5329,
    // @@protoc_insertion_point(enum_value:JKJGPOOLLKF.JKJGPOOLLKF_PLELMMJJOLM)
    JKJGPOOLLKF_PLELMMJJOLM = 5324,
    // @@protoc_insertion_point(enum_value:JKJGPOOLLKF.JKJGPOOLLKF_ECBIHKFNGGM)
    JKJGPOOLLKF_ECBIHKFNGGM = 5361,
    // @@protoc_insertion_point(enum_value:JKJGPOOLLKF.JKJGPOOLLKF_LHGHFLGEBBN)
    JKJGPOOLLKF_LHGHFLGEBBN = 5344,
}

impl ::protobuf::Enum for JKJGPOOLLKF {
    const NAME: &'static str = "JKJGPOOLLKF";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<JKJGPOOLLKF> {
        match value {
            0 => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_NLCDGIPGFDJ),
            5378 => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_EPPMKBDPDBM),
            5381 => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_KKEHIBPDIEF),
            5329 => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_GALJIBIENIB),
            5324 => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_PLELMMJJOLM),
            5361 => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_ECBIHKFNGGM),
            5344 => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_LHGHFLGEBBN),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<JKJGPOOLLKF> {
        match str {
            "JKJGPOOLLKF_NLCDGIPGFDJ" => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_NLCDGIPGFDJ),
            "JKJGPOOLLKF_EPPMKBDPDBM" => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_EPPMKBDPDBM),
            "JKJGPOOLLKF_KKEHIBPDIEF" => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_KKEHIBPDIEF),
            "JKJGPOOLLKF_GALJIBIENIB" => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_GALJIBIENIB),
            "JKJGPOOLLKF_PLELMMJJOLM" => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_PLELMMJJOLM),
            "JKJGPOOLLKF_ECBIHKFNGGM" => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_ECBIHKFNGGM),
            "JKJGPOOLLKF_LHGHFLGEBBN" => ::std::option::Option::Some(JKJGPOOLLKF::JKJGPOOLLKF_LHGHFLGEBBN),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [JKJGPOOLLKF] = &[
        JKJGPOOLLKF::JKJGPOOLLKF_NLCDGIPGFDJ,
        JKJGPOOLLKF::JKJGPOOLLKF_EPPMKBDPDBM,
        JKJGPOOLLKF::JKJGPOOLLKF_KKEHIBPDIEF,
        JKJGPOOLLKF::JKJGPOOLLKF_GALJIBIENIB,
        JKJGPOOLLKF::JKJGPOOLLKF_PLELMMJJOLM,
        JKJGPOOLLKF::JKJGPOOLLKF_ECBIHKFNGGM,
        JKJGPOOLLKF::JKJGPOOLLKF_LHGHFLGEBBN,
    ];
}

impl ::protobuf::EnumFull for JKJGPOOLLKF {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("JKJGPOOLLKF").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            JKJGPOOLLKF::JKJGPOOLLKF_NLCDGIPGFDJ => 0,
            JKJGPOOLLKF::JKJGPOOLLKF_EPPMKBDPDBM => 1,
            JKJGPOOLLKF::JKJGPOOLLKF_KKEHIBPDIEF => 2,
            JKJGPOOLLKF::JKJGPOOLLKF_GALJIBIENIB => 3,
            JKJGPOOLLKF::JKJGPOOLLKF_PLELMMJJOLM => 4,
            JKJGPOOLLKF::JKJGPOOLLKF_ECBIHKFNGGM => 5,
            JKJGPOOLLKF::JKJGPOOLLKF_LHGHFLGEBBN => 6,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for JKJGPOOLLKF {
    fn default() -> Self {
        JKJGPOOLLKF::JKJGPOOLLKF_NLCDGIPGFDJ
    }
}

impl JKJGPOOLLKF {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<JKJGPOOLLKF>("JKJGPOOLLKF")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11JKJGPOOLLKF.proto*\xde\x01\n\x0bJKJGPOOLLKF\x12\x1b\n\x17JKJGPOOLL\
    KF_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17JKJGPOOLLKF_EPPMKBDPDBM\x10\x82*\x12\
    \x1c\n\x17JKJGPOOLLKF_KKEHIBPDIEF\x10\x85*\x12\x1c\n\x17JKJGPOOLLKF_GALJ\
    IBIENIB\x10\xd1)\x12\x1c\n\x17JKJGPOOLLKF_PLELMMJJOLM\x10\xcc)\x12\x1c\n\
    \x17JKJGPOOLLKF_ECBIHKFNGGM\x10\xf1)\x12\x1c\n\x17JKJGPOOLLKF_LHGHFLGEBB\
    N\x10\xe0)b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(JKJGPOOLLKF::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
