// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `JOCFCCGIPEA.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:JOCFCCGIPEA)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct JOCFCCGIPEA {
    // message fields
    // @@protoc_insertion_point(field:JOCFCCGIPEA.queue_position)
    pub queue_position: u32,
    // message oneof groups
    pub KILBFAAFDPD: ::std::option::Option<jocfccgipea::KILBFAAFDPD>,
    // special fields
    // @@protoc_insertion_point(special_field:JOCFCCGIPEA.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a JOCFCCGIPEA {
    fn default() -> &'a JOCFCCGIPEA {
        <JOCFCCGIPEA as ::protobuf::Message>::default_instance()
    }
}

impl JOCFCCGIPEA {
    pub fn new() -> JOCFCCGIPEA {
        ::std::default::Default::default()
    }

    // .MDOIMCNFDLC KLONPDNKBJF = 384;

    pub fn KLONPDNKBJF(&self) -> &super::MDOIMCNFDLC::MDOIMCNFDLC {
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(ref v)) => v,
            _ => <super::MDOIMCNFDLC::MDOIMCNFDLC as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_KLONPDNKBJF(&mut self) {
        self.KILBFAAFDPD = ::std::option::Option::None;
    }

    pub fn has_KLONPDNKBJF(&self) -> bool {
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_KLONPDNKBJF(&mut self, v: super::MDOIMCNFDLC::MDOIMCNFDLC) {
        self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(v))
    }

    // Mutable pointer to the field.
    pub fn mut_KLONPDNKBJF(&mut self) -> &mut super::MDOIMCNFDLC::MDOIMCNFDLC {
        if let ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(_)) = self.KILBFAAFDPD {
        } else {
            self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(super::MDOIMCNFDLC::MDOIMCNFDLC::new()));
        }
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_KLONPDNKBJF(&mut self) -> super::MDOIMCNFDLC::MDOIMCNFDLC {
        if self.has_KLONPDNKBJF() {
            match self.KILBFAAFDPD.take() {
                ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(v)) => v,
                _ => panic!(),
            }
        } else {
            super::MDOIMCNFDLC::MDOIMCNFDLC::new()
        }
    }

    // .PFAIANENDEE LGBJDFHBIND = 1683;

    pub fn LGBJDFHBIND(&self) -> &super::PFAIANENDEE::PFAIANENDEE {
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(ref v)) => v,
            _ => <super::PFAIANENDEE::PFAIANENDEE as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_LGBJDFHBIND(&mut self) {
        self.KILBFAAFDPD = ::std::option::Option::None;
    }

    pub fn has_LGBJDFHBIND(&self) -> bool {
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_LGBJDFHBIND(&mut self, v: super::PFAIANENDEE::PFAIANENDEE) {
        self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(v))
    }

    // Mutable pointer to the field.
    pub fn mut_LGBJDFHBIND(&mut self) -> &mut super::PFAIANENDEE::PFAIANENDEE {
        if let ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(_)) = self.KILBFAAFDPD {
        } else {
            self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(super::PFAIANENDEE::PFAIANENDEE::new()));
        }
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_LGBJDFHBIND(&mut self) -> super::PFAIANENDEE::PFAIANENDEE {
        if self.has_LGBJDFHBIND() {
            match self.KILBFAAFDPD.take() {
                ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(v)) => v,
                _ => panic!(),
            }
        } else {
            super::PFAIANENDEE::PFAIANENDEE::new()
        }
    }

    // .CKPNGMLENFA NELLGPKHIKE = 389;

    pub fn NELLGPKHIKE(&self) -> &super::CKPNGMLENFA::CKPNGMLENFA {
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(ref v)) => v,
            _ => <super::CKPNGMLENFA::CKPNGMLENFA as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_NELLGPKHIKE(&mut self) {
        self.KILBFAAFDPD = ::std::option::Option::None;
    }

    pub fn has_NELLGPKHIKE(&self) -> bool {
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_NELLGPKHIKE(&mut self, v: super::CKPNGMLENFA::CKPNGMLENFA) {
        self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(v))
    }

    // Mutable pointer to the field.
    pub fn mut_NELLGPKHIKE(&mut self) -> &mut super::CKPNGMLENFA::CKPNGMLENFA {
        if let ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(_)) = self.KILBFAAFDPD {
        } else {
            self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(super::CKPNGMLENFA::CKPNGMLENFA::new()));
        }
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_NELLGPKHIKE(&mut self) -> super::CKPNGMLENFA::CKPNGMLENFA {
        if self.has_NELLGPKHIKE() {
            match self.KILBFAAFDPD.take() {
                ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(v)) => v,
                _ => panic!(),
            }
        } else {
            super::CKPNGMLENFA::CKPNGMLENFA::new()
        }
    }

    // .MOCNDOCEOJM NMEFKABDHAN = 667;

    pub fn NMEFKABDHAN(&self) -> &super::MOCNDOCEOJM::MOCNDOCEOJM {
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(ref v)) => v,
            _ => <super::MOCNDOCEOJM::MOCNDOCEOJM as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_NMEFKABDHAN(&mut self) {
        self.KILBFAAFDPD = ::std::option::Option::None;
    }

    pub fn has_NMEFKABDHAN(&self) -> bool {
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_NMEFKABDHAN(&mut self, v: super::MOCNDOCEOJM::MOCNDOCEOJM) {
        self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(v))
    }

    // Mutable pointer to the field.
    pub fn mut_NMEFKABDHAN(&mut self) -> &mut super::MOCNDOCEOJM::MOCNDOCEOJM {
        if let ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(_)) = self.KILBFAAFDPD {
        } else {
            self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(super::MOCNDOCEOJM::MOCNDOCEOJM::new()));
        }
        match self.KILBFAAFDPD {
            ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_NMEFKABDHAN(&mut self) -> super::MOCNDOCEOJM::MOCNDOCEOJM {
        if self.has_NMEFKABDHAN() {
            match self.KILBFAAFDPD.take() {
                ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(v)) => v,
                _ => panic!(),
            }
        } else {
            super::MOCNDOCEOJM::MOCNDOCEOJM::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "queue_position",
            |m: &JOCFCCGIPEA| { &m.queue_position },
            |m: &mut JOCFCCGIPEA| { &mut m.queue_position },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::MDOIMCNFDLC::MDOIMCNFDLC>(
            "KLONPDNKBJF",
            JOCFCCGIPEA::has_KLONPDNKBJF,
            JOCFCCGIPEA::KLONPDNKBJF,
            JOCFCCGIPEA::mut_KLONPDNKBJF,
            JOCFCCGIPEA::set_KLONPDNKBJF,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::PFAIANENDEE::PFAIANENDEE>(
            "LGBJDFHBIND",
            JOCFCCGIPEA::has_LGBJDFHBIND,
            JOCFCCGIPEA::LGBJDFHBIND,
            JOCFCCGIPEA::mut_LGBJDFHBIND,
            JOCFCCGIPEA::set_LGBJDFHBIND,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::CKPNGMLENFA::CKPNGMLENFA>(
            "NELLGPKHIKE",
            JOCFCCGIPEA::has_NELLGPKHIKE,
            JOCFCCGIPEA::NELLGPKHIKE,
            JOCFCCGIPEA::mut_NELLGPKHIKE,
            JOCFCCGIPEA::set_NELLGPKHIKE,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::MOCNDOCEOJM::MOCNDOCEOJM>(
            "NMEFKABDHAN",
            JOCFCCGIPEA::has_NMEFKABDHAN,
            JOCFCCGIPEA::NMEFKABDHAN,
            JOCFCCGIPEA::mut_NMEFKABDHAN,
            JOCFCCGIPEA::set_NMEFKABDHAN,
        ));
        oneofs.push(jocfccgipea::KILBFAAFDPD::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<JOCFCCGIPEA>(
            "JOCFCCGIPEA",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for JOCFCCGIPEA {
    const NAME: &'static str = "JOCFCCGIPEA";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                96 => {
                    self.queue_position = is.read_uint32()?;
                },
                3074 => {
                    self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(is.read_message()?));
                },
                13466 => {
                    self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(is.read_message()?));
                },
                3114 => {
                    self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(is.read_message()?));
                },
                5338 => {
                    self.KILBFAAFDPD = ::std::option::Option::Some(jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.queue_position != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.queue_position);
        }
        if let ::std::option::Option::Some(ref v) = self.KILBFAAFDPD {
            match v {
                &jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.queue_position != 0 {
            os.write_uint32(12, self.queue_position)?;
        }
        if let ::std::option::Option::Some(ref v) = self.KILBFAAFDPD {
            match v {
                &jocfccgipea::KILBFAAFDPD::KLONPDNKBJF(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(384, v, os)?;
                },
                &jocfccgipea::KILBFAAFDPD::LGBJDFHBIND(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1683, v, os)?;
                },
                &jocfccgipea::KILBFAAFDPD::NELLGPKHIKE(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(389, v, os)?;
                },
                &jocfccgipea::KILBFAAFDPD::NMEFKABDHAN(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(667, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> JOCFCCGIPEA {
        JOCFCCGIPEA::new()
    }

    fn clear(&mut self) {
        self.queue_position = 0;
        self.KILBFAAFDPD = ::std::option::Option::None;
        self.KILBFAAFDPD = ::std::option::Option::None;
        self.KILBFAAFDPD = ::std::option::Option::None;
        self.KILBFAAFDPD = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static JOCFCCGIPEA {
        static instance: JOCFCCGIPEA = JOCFCCGIPEA {
            queue_position: 0,
            KILBFAAFDPD: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for JOCFCCGIPEA {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("JOCFCCGIPEA").unwrap()).clone()
    }
}

impl ::std::fmt::Display for JOCFCCGIPEA {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for JOCFCCGIPEA {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `JOCFCCGIPEA`
pub mod jocfccgipea {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:JOCFCCGIPEA.KILBFAAFDPD)
    pub enum KILBFAAFDPD {
        // @@protoc_insertion_point(oneof_field:JOCFCCGIPEA.KLONPDNKBJF)
        KLONPDNKBJF(super::super::MDOIMCNFDLC::MDOIMCNFDLC),
        // @@protoc_insertion_point(oneof_field:JOCFCCGIPEA.LGBJDFHBIND)
        LGBJDFHBIND(super::super::PFAIANENDEE::PFAIANENDEE),
        // @@protoc_insertion_point(oneof_field:JOCFCCGIPEA.NELLGPKHIKE)
        NELLGPKHIKE(super::super::CKPNGMLENFA::CKPNGMLENFA),
        // @@protoc_insertion_point(oneof_field:JOCFCCGIPEA.NMEFKABDHAN)
        NMEFKABDHAN(super::super::MOCNDOCEOJM::MOCNDOCEOJM),
    }

    impl ::protobuf::Oneof for KILBFAAFDPD {
    }

    impl ::protobuf::OneofFull for KILBFAAFDPD {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::JOCFCCGIPEA as ::protobuf::MessageFull>::descriptor().oneof_by_name("KILBFAAFDPD").unwrap()).clone()
        }
    }

    impl KILBFAAFDPD {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<KILBFAAFDPD>("KILBFAAFDPD")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11JOCFCCGIPEA.proto\x1a\x11CKPNGMLENFA.proto\x1a\x11MDOIMCNFDLC.prot\
    o\x1a\x11MOCNDOCEOJM.proto\x1a\x11PFAIANENDEE.proto\"\x8f\x02\n\x0bJOCFC\
    CGIPEA\x12%\n\x0equeue_position\x18\x0c\x20\x01(\rR\rqueuePosition\x121\
    \n\x0bKLONPDNKBJF\x18\x80\x03\x20\x01(\x0b2\x0c.MDOIMCNFDLCH\0R\x0bKLONP\
    DNKBJF\x121\n\x0bLGBJDFHBIND\x18\x93\r\x20\x01(\x0b2\x0c.PFAIANENDEEH\0R\
    \x0bLGBJDFHBIND\x121\n\x0bNELLGPKHIKE\x18\x85\x03\x20\x01(\x0b2\x0c.CKPN\
    GMLENFAH\0R\x0bNELLGPKHIKE\x121\n\x0bNMEFKABDHAN\x18\x9b\x05\x20\x01(\
    \x0b2\x0c.MOCNDOCEOJMH\0R\x0bNMEFKABDHANB\r\n\x0bKILBFAAFDPDb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(4);
            deps.push(super::CKPNGMLENFA::file_descriptor().clone());
            deps.push(super::MDOIMCNFDLC::file_descriptor().clone());
            deps.push(super::MOCNDOCEOJM::file_descriptor().clone());
            deps.push(super::PFAIANENDEE::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(JOCFCCGIPEA::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
