// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `KAODLPJMEFE.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:KAODLPJMEFE)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct KAODLPJMEFE {
    // message fields
    // @@protoc_insertion_point(field:KAODLPJMEFE.level)
    pub level: u32,
    // @@protoc_insertion_point(field:KAODLPJMEFE.head_frame_info)
    pub head_frame_info: ::protobuf::MessageField<super::HeadFrameInfo::HeadFrameInfo>,
    // @@protoc_insertion_point(field:KAODLPJMEFE.platform)
    pub platform: ::protobuf::EnumOrUnknown<super::PlatformType::PlatformType>,
    // @@protoc_insertion_point(field:KAODLPJMEFE.platform_nick)
    pub platform_nick: ::std::string::String,
    // @@protoc_insertion_point(field:KAODLPJMEFE.uid)
    pub uid: u32,
    // @@protoc_insertion_point(field:KAODLPJMEFE.remark_name)
    pub remark_name: ::std::string::String,
    // @@protoc_insertion_point(field:KAODLPJMEFE.nickname)
    pub nickname: ::std::string::String,
    // @@protoc_insertion_point(field:KAODLPJMEFE.MIDBIPHKLJO)
    pub MIDBIPHKLJO: u32,
    // @@protoc_insertion_point(field:KAODLPJMEFE.DCOFPHDKNIJ)
    pub DCOFPHDKNIJ: u32,
    // @@protoc_insertion_point(field:KAODLPJMEFE.head_icon)
    pub head_icon: u32,
    // special fields
    // @@protoc_insertion_point(special_field:KAODLPJMEFE.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a KAODLPJMEFE {
    fn default() -> &'a KAODLPJMEFE {
        <KAODLPJMEFE as ::protobuf::Message>::default_instance()
    }
}

impl KAODLPJMEFE {
    pub fn new() -> KAODLPJMEFE {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(10);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "level",
            |m: &KAODLPJMEFE| { &m.level },
            |m: &mut KAODLPJMEFE| { &mut m.level },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::HeadFrameInfo::HeadFrameInfo>(
            "head_frame_info",
            |m: &KAODLPJMEFE| { &m.head_frame_info },
            |m: &mut KAODLPJMEFE| { &mut m.head_frame_info },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "platform",
            |m: &KAODLPJMEFE| { &m.platform },
            |m: &mut KAODLPJMEFE| { &mut m.platform },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "platform_nick",
            |m: &KAODLPJMEFE| { &m.platform_nick },
            |m: &mut KAODLPJMEFE| { &mut m.platform_nick },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "uid",
            |m: &KAODLPJMEFE| { &m.uid },
            |m: &mut KAODLPJMEFE| { &mut m.uid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "remark_name",
            |m: &KAODLPJMEFE| { &m.remark_name },
            |m: &mut KAODLPJMEFE| { &mut m.remark_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "nickname",
            |m: &KAODLPJMEFE| { &m.nickname },
            |m: &mut KAODLPJMEFE| { &mut m.nickname },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MIDBIPHKLJO",
            |m: &KAODLPJMEFE| { &m.MIDBIPHKLJO },
            |m: &mut KAODLPJMEFE| { &mut m.MIDBIPHKLJO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "DCOFPHDKNIJ",
            |m: &KAODLPJMEFE| { &m.DCOFPHDKNIJ },
            |m: &mut KAODLPJMEFE| { &mut m.DCOFPHDKNIJ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "head_icon",
            |m: &KAODLPJMEFE| { &m.head_icon },
            |m: &mut KAODLPJMEFE| { &mut m.head_icon },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<KAODLPJMEFE>(
            "KAODLPJMEFE",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for KAODLPJMEFE {
    const NAME: &'static str = "KAODLPJMEFE";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.level = is.read_uint32()?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.head_frame_info)?;
                },
                56 => {
                    self.platform = is.read_enum_or_unknown()?;
                },
                66 => {
                    self.platform_nick = is.read_string()?;
                },
                72 => {
                    self.uid = is.read_uint32()?;
                },
                90 => {
                    self.remark_name = is.read_string()?;
                },
                98 => {
                    self.nickname = is.read_string()?;
                },
                104 => {
                    self.MIDBIPHKLJO = is.read_uint32()?;
                },
                112 => {
                    self.DCOFPHDKNIJ = is.read_uint32()?;
                },
                120 => {
                    self.head_icon = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.level != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.level);
        }
        if let Some(v) = self.head_frame_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.platform != ::protobuf::EnumOrUnknown::new(super::PlatformType::PlatformType::EDITOR) {
            my_size += ::protobuf::rt::int32_size(7, self.platform.value());
        }
        if !self.platform_nick.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.platform_nick);
        }
        if self.uid != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.uid);
        }
        if !self.remark_name.is_empty() {
            my_size += ::protobuf::rt::string_size(11, &self.remark_name);
        }
        if !self.nickname.is_empty() {
            my_size += ::protobuf::rt::string_size(12, &self.nickname);
        }
        if self.MIDBIPHKLJO != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.MIDBIPHKLJO);
        }
        if self.DCOFPHDKNIJ != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.DCOFPHDKNIJ);
        }
        if self.head_icon != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.head_icon);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.level != 0 {
            os.write_uint32(1, self.level)?;
        }
        if let Some(v) = self.head_frame_info.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if self.platform != ::protobuf::EnumOrUnknown::new(super::PlatformType::PlatformType::EDITOR) {
            os.write_enum(7, ::protobuf::EnumOrUnknown::value(&self.platform))?;
        }
        if !self.platform_nick.is_empty() {
            os.write_string(8, &self.platform_nick)?;
        }
        if self.uid != 0 {
            os.write_uint32(9, self.uid)?;
        }
        if !self.remark_name.is_empty() {
            os.write_string(11, &self.remark_name)?;
        }
        if !self.nickname.is_empty() {
            os.write_string(12, &self.nickname)?;
        }
        if self.MIDBIPHKLJO != 0 {
            os.write_uint32(13, self.MIDBIPHKLJO)?;
        }
        if self.DCOFPHDKNIJ != 0 {
            os.write_uint32(14, self.DCOFPHDKNIJ)?;
        }
        if self.head_icon != 0 {
            os.write_uint32(15, self.head_icon)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> KAODLPJMEFE {
        KAODLPJMEFE::new()
    }

    fn clear(&mut self) {
        self.level = 0;
        self.head_frame_info.clear();
        self.platform = ::protobuf::EnumOrUnknown::new(super::PlatformType::PlatformType::EDITOR);
        self.platform_nick.clear();
        self.uid = 0;
        self.remark_name.clear();
        self.nickname.clear();
        self.MIDBIPHKLJO = 0;
        self.DCOFPHDKNIJ = 0;
        self.head_icon = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static KAODLPJMEFE {
        static instance: KAODLPJMEFE = KAODLPJMEFE {
            level: 0,
            head_frame_info: ::protobuf::MessageField::none(),
            platform: ::protobuf::EnumOrUnknown::from_i32(0),
            platform_nick: ::std::string::String::new(),
            uid: 0,
            remark_name: ::std::string::String::new(),
            nickname: ::std::string::String::new(),
            MIDBIPHKLJO: 0,
            DCOFPHDKNIJ: 0,
            head_icon: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for KAODLPJMEFE {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("KAODLPJMEFE").unwrap()).clone()
    }
}

impl ::std::fmt::Display for KAODLPJMEFE {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KAODLPJMEFE {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11KAODLPJMEFE.proto\x1a\x13HeadFrameInfo.proto\x1a\x12PlatformType.p\
    roto\"\xdb\x02\n\x0bKAODLPJMEFE\x12\x14\n\x05level\x18\x01\x20\x01(\rR\
    \x05level\x126\n\x0fhead_frame_info\x18\x03\x20\x01(\x0b2\x0e.HeadFrameI\
    nfoR\rheadFrameInfo\x12)\n\x08platform\x18\x07\x20\x01(\x0e2\r.PlatformT\
    ypeR\x08platform\x12#\n\rplatform_nick\x18\x08\x20\x01(\tR\x0cplatformNi\
    ck\x12\x10\n\x03uid\x18\t\x20\x01(\rR\x03uid\x12\x1f\n\x0bremark_name\
    \x18\x0b\x20\x01(\tR\nremarkName\x12\x1a\n\x08nickname\x18\x0c\x20\x01(\
    \tR\x08nickname\x12\x20\n\x0bMIDBIPHKLJO\x18\r\x20\x01(\rR\x0bMIDBIPHKLJ\
    O\x12\x20\n\x0bDCOFPHDKNIJ\x18\x0e\x20\x01(\rR\x0bDCOFPHDKNIJ\x12\x1b\n\
    \thead_icon\x18\x0f\x20\x01(\rR\x08headIconb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::HeadFrameInfo::file_descriptor().clone());
            deps.push(super::PlatformType::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(KAODLPJMEFE::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
