// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `KCLDFMNECJB.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:KCLDFMNECJB)
pub enum KCLDFMNECJB {
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_NLCDGIPGFDJ)
    KCLDFMNECJB_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_GAJOJHCNNMO)
    KCLDFMNECJB_GAJOJHCNNMO = 8392,
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_AGOKKBAKEBA)
    KCLDFMNECJB_AGOKKBAKEBA = 8400,
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_EINFPBHAJFJ)
    KCLDFMNECJB_EINFPBHAJFJ = 8383,
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_ADHENKLHBKE)
    KCLDFMNECJB_ADHENKLHBKE = 8394,
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_GMODLOKAHLA)
    KCLDFMNECJB_GMODLOKAHLA = 8395,
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_GMBKGFOIOPI)
    KCLDFMNECJB_GMBKGFOIOPI = 8382,
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_ICJCOBDPNGO)
    KCLDFMNECJB_ICJCOBDPNGO = 8384,
    // @@protoc_insertion_point(enum_value:KCLDFMNECJB.KCLDFMNECJB_PGIBHKCAEAK)
    KCLDFMNECJB_PGIBHKCAEAK = 8385,
}

impl ::protobuf::Enum for KCLDFMNECJB {
    const NAME: &'static str = "KCLDFMNECJB";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<KCLDFMNECJB> {
        match value {
            0 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_NLCDGIPGFDJ),
            8392 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_GAJOJHCNNMO),
            8400 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_AGOKKBAKEBA),
            8383 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_EINFPBHAJFJ),
            8394 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_ADHENKLHBKE),
            8395 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_GMODLOKAHLA),
            8382 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_GMBKGFOIOPI),
            8384 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_ICJCOBDPNGO),
            8385 => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_PGIBHKCAEAK),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<KCLDFMNECJB> {
        match str {
            "KCLDFMNECJB_NLCDGIPGFDJ" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_NLCDGIPGFDJ),
            "KCLDFMNECJB_GAJOJHCNNMO" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_GAJOJHCNNMO),
            "KCLDFMNECJB_AGOKKBAKEBA" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_AGOKKBAKEBA),
            "KCLDFMNECJB_EINFPBHAJFJ" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_EINFPBHAJFJ),
            "KCLDFMNECJB_ADHENKLHBKE" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_ADHENKLHBKE),
            "KCLDFMNECJB_GMODLOKAHLA" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_GMODLOKAHLA),
            "KCLDFMNECJB_GMBKGFOIOPI" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_GMBKGFOIOPI),
            "KCLDFMNECJB_ICJCOBDPNGO" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_ICJCOBDPNGO),
            "KCLDFMNECJB_PGIBHKCAEAK" => ::std::option::Option::Some(KCLDFMNECJB::KCLDFMNECJB_PGIBHKCAEAK),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [KCLDFMNECJB] = &[
        KCLDFMNECJB::KCLDFMNECJB_NLCDGIPGFDJ,
        KCLDFMNECJB::KCLDFMNECJB_GAJOJHCNNMO,
        KCLDFMNECJB::KCLDFMNECJB_AGOKKBAKEBA,
        KCLDFMNECJB::KCLDFMNECJB_EINFPBHAJFJ,
        KCLDFMNECJB::KCLDFMNECJB_ADHENKLHBKE,
        KCLDFMNECJB::KCLDFMNECJB_GMODLOKAHLA,
        KCLDFMNECJB::KCLDFMNECJB_GMBKGFOIOPI,
        KCLDFMNECJB::KCLDFMNECJB_ICJCOBDPNGO,
        KCLDFMNECJB::KCLDFMNECJB_PGIBHKCAEAK,
    ];
}

impl ::protobuf::EnumFull for KCLDFMNECJB {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("KCLDFMNECJB").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            KCLDFMNECJB::KCLDFMNECJB_NLCDGIPGFDJ => 0,
            KCLDFMNECJB::KCLDFMNECJB_GAJOJHCNNMO => 1,
            KCLDFMNECJB::KCLDFMNECJB_AGOKKBAKEBA => 2,
            KCLDFMNECJB::KCLDFMNECJB_EINFPBHAJFJ => 3,
            KCLDFMNECJB::KCLDFMNECJB_ADHENKLHBKE => 4,
            KCLDFMNECJB::KCLDFMNECJB_GMODLOKAHLA => 5,
            KCLDFMNECJB::KCLDFMNECJB_GMBKGFOIOPI => 6,
            KCLDFMNECJB::KCLDFMNECJB_ICJCOBDPNGO => 7,
            KCLDFMNECJB::KCLDFMNECJB_PGIBHKCAEAK => 8,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for KCLDFMNECJB {
    fn default() -> Self {
        KCLDFMNECJB::KCLDFMNECJB_NLCDGIPGFDJ
    }
}

impl KCLDFMNECJB {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<KCLDFMNECJB>("KCLDFMNECJB")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11KCLDFMNECJB.proto*\x9a\x02\n\x0bKCLDFMNECJB\x12\x1b\n\x17KCLDFMNEC\
    JB_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17KCLDFMNECJB_GAJOJHCNNMO\x10\xc8A\x12\
    \x1c\n\x17KCLDFMNECJB_AGOKKBAKEBA\x10\xd0A\x12\x1c\n\x17KCLDFMNECJB_EINF\
    PBHAJFJ\x10\xbfA\x12\x1c\n\x17KCLDFMNECJB_ADHENKLHBKE\x10\xcaA\x12\x1c\n\
    \x17KCLDFMNECJB_GMODLOKAHLA\x10\xcbA\x12\x1c\n\x17KCLDFMNECJB_GMBKGFOIOP\
    I\x10\xbeA\x12\x1c\n\x17KCLDFMNECJB_ICJCOBDPNGO\x10\xc0A\x12\x1c\n\x17KC\
    LDFMNECJB_PGIBHKCAEAK\x10\xc1Ab\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(KCLDFMNECJB::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
