// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `KIDBFKJEJJD.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:KIDBFKJEJJD)
pub enum KIDBFKJEJJD {
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_NLCDGIPGFDJ)
    KIDBFKJEJJD_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_HDDNALCIJDE)
    KIDBFKJEJJD_HDDNALCIJDE = 47,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_PJMINBJDKCC)
    KIDBFKJEJJD_PJMINBJDKCC = 58,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_IPDCEJGOFKI)
    KIDBFKJEJJD_IPDCEJGOFKI = 3,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_DGKKANKIDLG)
    KIDBFKJEJJD_DGKKANKIDLG = 24,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_DOGHFIAJIHP)
    KIDBFKJEJJD_DOGHFIAJIHP = 31,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_DHHMBIGPPFB)
    KIDBFKJEJJD_DHHMBIGPPFB = 37,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_BLPDFGFMCBK)
    KIDBFKJEJJD_BLPDFGFMCBK = 36,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_OFIEPOPANGH)
    KIDBFKJEJJD_OFIEPOPANGH = 15,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_BFMIAMIHIED)
    KIDBFKJEJJD_BFMIAMIHIED = 59,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_JFLKFMHCFFF)
    KIDBFKJEJJD_JFLKFMHCFFF = 22,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_CAEEPLEGLCK)
    KIDBFKJEJJD_CAEEPLEGLCK = 20,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_EEMJCDKIJOP)
    KIDBFKJEJJD_EEMJCDKIJOP = 28,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_POACPAFBFKJ)
    KIDBFKJEJJD_POACPAFBFKJ = 66,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_JIIJIOKAAOH)
    KIDBFKJEJJD_JIIJIOKAAOH = 23,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_IBPHMNFDGCA)
    KIDBFKJEJJD_IBPHMNFDGCA = 96,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_KJLKLPLIFDK)
    KIDBFKJEJJD_KJLKLPLIFDK = 9,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_HLAAGBFPKPH)
    KIDBFKJEJJD_HLAAGBFPKPH = 56,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_GNAOLJNMAFC)
    KIDBFKJEJJD_GNAOLJNMAFC = 25,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_LLGMMAPJDLI)
    KIDBFKJEJJD_LLGMMAPJDLI = 93,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_MKHNJMFNPBB)
    KIDBFKJEJJD_MKHNJMFNPBB = 76,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_FCNEJBELPDL)
    KIDBFKJEJJD_FCNEJBELPDL = 21,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_PPBANCPJPHG)
    KIDBFKJEJJD_PPBANCPJPHG = 18,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_KCCMJKHJMAB)
    KIDBFKJEJJD_KCCMJKHJMAB = 91,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_CLHGHKAAEIJ)
    KIDBFKJEJJD_CLHGHKAAEIJ = 85,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_JBHLDLGENMB)
    KIDBFKJEJJD_JBHLDLGENMB = 32,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_ONNNLNCMMGJ)
    KIDBFKJEJJD_ONNNLNCMMGJ = 78,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_CJOBOBANBOA)
    KIDBFKJEJJD_CJOBOBANBOA = 29,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_PBPJJFPBHHK)
    KIDBFKJEJJD_PBPJJFPBHHK = 81,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_HONJDBCACEB)
    KIDBFKJEJJD_HONJDBCACEB = 55,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_AGHGBNPIOGK)
    KIDBFKJEJJD_AGHGBNPIOGK = 54,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_ECHEKPDIPPA)
    KIDBFKJEJJD_ECHEKPDIPPA = 6,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_HJAIHJAHMKN)
    KIDBFKJEJJD_HJAIHJAHMKN = 75,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_KOKCPOPBBCD)
    KIDBFKJEJJD_KOKCPOPBBCD = 68,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_JGLNKENAIEB)
    KIDBFKJEJJD_JGLNKENAIEB = 62,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_MCOKJKLKHDL)
    KIDBFKJEJJD_MCOKJKLKHDL = 39,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_FPHMFIPGANO)
    KIDBFKJEJJD_FPHMFIPGANO = 5,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_CFMGLJJOJDJ)
    KIDBFKJEJJD_CFMGLJJOJDJ = 63,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_FFLOLBNNBJJ)
    KIDBFKJEJJD_FFLOLBNNBJJ = 10,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_BBECFFBPOGG)
    KIDBFKJEJJD_BBECFFBPOGG = 73,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_ABAKFMHMHPD)
    KIDBFKJEJJD_ABAKFMHMHPD = 95,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_HLKKHFGJEOL)
    KIDBFKJEJJD_HLKKHFGJEOL = 34,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_JPADFDNCDAO)
    KIDBFKJEJJD_JPADFDNCDAO = 50,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_LDFPOBPPCIH)
    KIDBFKJEJJD_LDFPOBPPCIH = 40,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_JHFOOFEBNEL)
    KIDBFKJEJJD_JHFOOFEBNEL = 61,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_PFAAOODLAPI)
    KIDBFKJEJJD_PFAAOODLAPI = 1,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_BCOPKPAPNAI)
    KIDBFKJEJJD_BCOPKPAPNAI = 44,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_OAMNNICMJLH)
    KIDBFKJEJJD_OAMNNICMJLH = 65,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_GONKEIBLBOI)
    KIDBFKJEJJD_GONKEIBLBOI = 11,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_AIHKMIKNPOH)
    KIDBFKJEJJD_AIHKMIKNPOH = 19,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_KLNEFLGGGIL)
    KIDBFKJEJJD_KLNEFLGGGIL = 13,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_MLGEKIJAIBO)
    KIDBFKJEJJD_MLGEKIJAIBO = 4,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_CLOMOECMLPH)
    KIDBFKJEJJD_CLOMOECMLPH = 70,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_KGCPBEOGMOP)
    KIDBFKJEJJD_KGCPBEOGMOP = 99,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_BLLKMJKMNIG)
    KIDBFKJEJJD_BLLKMJKMNIG = 41,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_DOPJENGCOAN)
    KIDBFKJEJJD_DOPJENGCOAN = 69,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_CBPDMEEEOJP)
    KIDBFKJEJJD_CBPDMEEEOJP = 8,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_COENAOLHFEL)
    KIDBFKJEJJD_COENAOLHFEL = 57,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_PCMLAHACMPO)
    KIDBFKJEJJD_PCMLAHACMPO = 71,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_AFKIMICKEDM)
    KIDBFKJEJJD_AFKIMICKEDM = 46,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_LAKJLNGMLPC)
    KIDBFKJEJJD_LAKJLNGMLPC = 30,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_KPALKJHKPED)
    KIDBFKJEJJD_KPALKJHKPED = 26,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_LHBKEJCGNCF)
    KIDBFKJEJJD_LHBKEJCGNCF = 98,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_GKDOBOKBGPK)
    KIDBFKJEJJD_GKDOBOKBGPK = 14,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_OPFIKLLIHBH)
    KIDBFKJEJJD_OPFIKLLIHBH = 7,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_IKANNBLIACL)
    KIDBFKJEJJD_IKANNBLIACL = 52,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_MCFLGBJENJD)
    KIDBFKJEJJD_MCFLGBJENJD = 35,
    // @@protoc_insertion_point(enum_value:KIDBFKJEJJD.KIDBFKJEJJD_CEDFKEJBCCJ)
    KIDBFKJEJJD_CEDFKEJBCCJ = 53,
}

impl ::protobuf::Enum for KIDBFKJEJJD {
    const NAME: &'static str = "KIDBFKJEJJD";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<KIDBFKJEJJD> {
        match value {
            0 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_NLCDGIPGFDJ),
            47 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HDDNALCIJDE),
            58 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PJMINBJDKCC),
            3 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_IPDCEJGOFKI),
            24 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_DGKKANKIDLG),
            31 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_DOGHFIAJIHP),
            37 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_DHHMBIGPPFB),
            36 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BLPDFGFMCBK),
            15 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_OFIEPOPANGH),
            59 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BFMIAMIHIED),
            22 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JFLKFMHCFFF),
            20 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CAEEPLEGLCK),
            28 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_EEMJCDKIJOP),
            66 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_POACPAFBFKJ),
            23 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JIIJIOKAAOH),
            96 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_IBPHMNFDGCA),
            9 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KJLKLPLIFDK),
            56 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HLAAGBFPKPH),
            25 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_GNAOLJNMAFC),
            93 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_LLGMMAPJDLI),
            76 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_MKHNJMFNPBB),
            21 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_FCNEJBELPDL),
            18 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PPBANCPJPHG),
            91 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KCCMJKHJMAB),
            85 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CLHGHKAAEIJ),
            32 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JBHLDLGENMB),
            78 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_ONNNLNCMMGJ),
            29 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CJOBOBANBOA),
            81 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PBPJJFPBHHK),
            55 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HONJDBCACEB),
            54 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_AGHGBNPIOGK),
            6 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_ECHEKPDIPPA),
            75 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HJAIHJAHMKN),
            68 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KOKCPOPBBCD),
            62 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JGLNKENAIEB),
            39 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_MCOKJKLKHDL),
            5 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_FPHMFIPGANO),
            63 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CFMGLJJOJDJ),
            10 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_FFLOLBNNBJJ),
            73 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BBECFFBPOGG),
            95 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_ABAKFMHMHPD),
            34 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HLKKHFGJEOL),
            50 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JPADFDNCDAO),
            40 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_LDFPOBPPCIH),
            61 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JHFOOFEBNEL),
            1 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PFAAOODLAPI),
            44 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BCOPKPAPNAI),
            65 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_OAMNNICMJLH),
            11 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_GONKEIBLBOI),
            19 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_AIHKMIKNPOH),
            13 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KLNEFLGGGIL),
            4 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_MLGEKIJAIBO),
            70 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CLOMOECMLPH),
            99 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KGCPBEOGMOP),
            41 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BLLKMJKMNIG),
            69 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_DOPJENGCOAN),
            8 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CBPDMEEEOJP),
            57 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_COENAOLHFEL),
            71 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PCMLAHACMPO),
            46 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_AFKIMICKEDM),
            30 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_LAKJLNGMLPC),
            26 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KPALKJHKPED),
            98 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_LHBKEJCGNCF),
            14 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_GKDOBOKBGPK),
            7 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_OPFIKLLIHBH),
            52 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_IKANNBLIACL),
            35 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_MCFLGBJENJD),
            53 => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CEDFKEJBCCJ),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<KIDBFKJEJJD> {
        match str {
            "KIDBFKJEJJD_NLCDGIPGFDJ" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_NLCDGIPGFDJ),
            "KIDBFKJEJJD_HDDNALCIJDE" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HDDNALCIJDE),
            "KIDBFKJEJJD_PJMINBJDKCC" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PJMINBJDKCC),
            "KIDBFKJEJJD_IPDCEJGOFKI" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_IPDCEJGOFKI),
            "KIDBFKJEJJD_DGKKANKIDLG" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_DGKKANKIDLG),
            "KIDBFKJEJJD_DOGHFIAJIHP" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_DOGHFIAJIHP),
            "KIDBFKJEJJD_DHHMBIGPPFB" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_DHHMBIGPPFB),
            "KIDBFKJEJJD_BLPDFGFMCBK" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BLPDFGFMCBK),
            "KIDBFKJEJJD_OFIEPOPANGH" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_OFIEPOPANGH),
            "KIDBFKJEJJD_BFMIAMIHIED" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BFMIAMIHIED),
            "KIDBFKJEJJD_JFLKFMHCFFF" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JFLKFMHCFFF),
            "KIDBFKJEJJD_CAEEPLEGLCK" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CAEEPLEGLCK),
            "KIDBFKJEJJD_EEMJCDKIJOP" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_EEMJCDKIJOP),
            "KIDBFKJEJJD_POACPAFBFKJ" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_POACPAFBFKJ),
            "KIDBFKJEJJD_JIIJIOKAAOH" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JIIJIOKAAOH),
            "KIDBFKJEJJD_IBPHMNFDGCA" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_IBPHMNFDGCA),
            "KIDBFKJEJJD_KJLKLPLIFDK" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KJLKLPLIFDK),
            "KIDBFKJEJJD_HLAAGBFPKPH" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HLAAGBFPKPH),
            "KIDBFKJEJJD_GNAOLJNMAFC" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_GNAOLJNMAFC),
            "KIDBFKJEJJD_LLGMMAPJDLI" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_LLGMMAPJDLI),
            "KIDBFKJEJJD_MKHNJMFNPBB" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_MKHNJMFNPBB),
            "KIDBFKJEJJD_FCNEJBELPDL" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_FCNEJBELPDL),
            "KIDBFKJEJJD_PPBANCPJPHG" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PPBANCPJPHG),
            "KIDBFKJEJJD_KCCMJKHJMAB" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KCCMJKHJMAB),
            "KIDBFKJEJJD_CLHGHKAAEIJ" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CLHGHKAAEIJ),
            "KIDBFKJEJJD_JBHLDLGENMB" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JBHLDLGENMB),
            "KIDBFKJEJJD_ONNNLNCMMGJ" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_ONNNLNCMMGJ),
            "KIDBFKJEJJD_CJOBOBANBOA" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CJOBOBANBOA),
            "KIDBFKJEJJD_PBPJJFPBHHK" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PBPJJFPBHHK),
            "KIDBFKJEJJD_HONJDBCACEB" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HONJDBCACEB),
            "KIDBFKJEJJD_AGHGBNPIOGK" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_AGHGBNPIOGK),
            "KIDBFKJEJJD_ECHEKPDIPPA" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_ECHEKPDIPPA),
            "KIDBFKJEJJD_HJAIHJAHMKN" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HJAIHJAHMKN),
            "KIDBFKJEJJD_KOKCPOPBBCD" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KOKCPOPBBCD),
            "KIDBFKJEJJD_JGLNKENAIEB" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JGLNKENAIEB),
            "KIDBFKJEJJD_MCOKJKLKHDL" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_MCOKJKLKHDL),
            "KIDBFKJEJJD_FPHMFIPGANO" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_FPHMFIPGANO),
            "KIDBFKJEJJD_CFMGLJJOJDJ" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CFMGLJJOJDJ),
            "KIDBFKJEJJD_FFLOLBNNBJJ" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_FFLOLBNNBJJ),
            "KIDBFKJEJJD_BBECFFBPOGG" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BBECFFBPOGG),
            "KIDBFKJEJJD_ABAKFMHMHPD" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_ABAKFMHMHPD),
            "KIDBFKJEJJD_HLKKHFGJEOL" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_HLKKHFGJEOL),
            "KIDBFKJEJJD_JPADFDNCDAO" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JPADFDNCDAO),
            "KIDBFKJEJJD_LDFPOBPPCIH" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_LDFPOBPPCIH),
            "KIDBFKJEJJD_JHFOOFEBNEL" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_JHFOOFEBNEL),
            "KIDBFKJEJJD_PFAAOODLAPI" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PFAAOODLAPI),
            "KIDBFKJEJJD_BCOPKPAPNAI" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BCOPKPAPNAI),
            "KIDBFKJEJJD_OAMNNICMJLH" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_OAMNNICMJLH),
            "KIDBFKJEJJD_GONKEIBLBOI" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_GONKEIBLBOI),
            "KIDBFKJEJJD_AIHKMIKNPOH" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_AIHKMIKNPOH),
            "KIDBFKJEJJD_KLNEFLGGGIL" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KLNEFLGGGIL),
            "KIDBFKJEJJD_MLGEKIJAIBO" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_MLGEKIJAIBO),
            "KIDBFKJEJJD_CLOMOECMLPH" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CLOMOECMLPH),
            "KIDBFKJEJJD_KGCPBEOGMOP" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KGCPBEOGMOP),
            "KIDBFKJEJJD_BLLKMJKMNIG" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_BLLKMJKMNIG),
            "KIDBFKJEJJD_DOPJENGCOAN" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_DOPJENGCOAN),
            "KIDBFKJEJJD_CBPDMEEEOJP" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CBPDMEEEOJP),
            "KIDBFKJEJJD_COENAOLHFEL" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_COENAOLHFEL),
            "KIDBFKJEJJD_PCMLAHACMPO" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_PCMLAHACMPO),
            "KIDBFKJEJJD_AFKIMICKEDM" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_AFKIMICKEDM),
            "KIDBFKJEJJD_LAKJLNGMLPC" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_LAKJLNGMLPC),
            "KIDBFKJEJJD_KPALKJHKPED" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_KPALKJHKPED),
            "KIDBFKJEJJD_LHBKEJCGNCF" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_LHBKEJCGNCF),
            "KIDBFKJEJJD_GKDOBOKBGPK" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_GKDOBOKBGPK),
            "KIDBFKJEJJD_OPFIKLLIHBH" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_OPFIKLLIHBH),
            "KIDBFKJEJJD_IKANNBLIACL" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_IKANNBLIACL),
            "KIDBFKJEJJD_MCFLGBJENJD" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_MCFLGBJENJD),
            "KIDBFKJEJJD_CEDFKEJBCCJ" => ::std::option::Option::Some(KIDBFKJEJJD::KIDBFKJEJJD_CEDFKEJBCCJ),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [KIDBFKJEJJD] = &[
        KIDBFKJEJJD::KIDBFKJEJJD_NLCDGIPGFDJ,
        KIDBFKJEJJD::KIDBFKJEJJD_HDDNALCIJDE,
        KIDBFKJEJJD::KIDBFKJEJJD_PJMINBJDKCC,
        KIDBFKJEJJD::KIDBFKJEJJD_IPDCEJGOFKI,
        KIDBFKJEJJD::KIDBFKJEJJD_DGKKANKIDLG,
        KIDBFKJEJJD::KIDBFKJEJJD_DOGHFIAJIHP,
        KIDBFKJEJJD::KIDBFKJEJJD_DHHMBIGPPFB,
        KIDBFKJEJJD::KIDBFKJEJJD_BLPDFGFMCBK,
        KIDBFKJEJJD::KIDBFKJEJJD_OFIEPOPANGH,
        KIDBFKJEJJD::KIDBFKJEJJD_BFMIAMIHIED,
        KIDBFKJEJJD::KIDBFKJEJJD_JFLKFMHCFFF,
        KIDBFKJEJJD::KIDBFKJEJJD_CAEEPLEGLCK,
        KIDBFKJEJJD::KIDBFKJEJJD_EEMJCDKIJOP,
        KIDBFKJEJJD::KIDBFKJEJJD_POACPAFBFKJ,
        KIDBFKJEJJD::KIDBFKJEJJD_JIIJIOKAAOH,
        KIDBFKJEJJD::KIDBFKJEJJD_IBPHMNFDGCA,
        KIDBFKJEJJD::KIDBFKJEJJD_KJLKLPLIFDK,
        KIDBFKJEJJD::KIDBFKJEJJD_HLAAGBFPKPH,
        KIDBFKJEJJD::KIDBFKJEJJD_GNAOLJNMAFC,
        KIDBFKJEJJD::KIDBFKJEJJD_LLGMMAPJDLI,
        KIDBFKJEJJD::KIDBFKJEJJD_MKHNJMFNPBB,
        KIDBFKJEJJD::KIDBFKJEJJD_FCNEJBELPDL,
        KIDBFKJEJJD::KIDBFKJEJJD_PPBANCPJPHG,
        KIDBFKJEJJD::KIDBFKJEJJD_KCCMJKHJMAB,
        KIDBFKJEJJD::KIDBFKJEJJD_CLHGHKAAEIJ,
        KIDBFKJEJJD::KIDBFKJEJJD_JBHLDLGENMB,
        KIDBFKJEJJD::KIDBFKJEJJD_ONNNLNCMMGJ,
        KIDBFKJEJJD::KIDBFKJEJJD_CJOBOBANBOA,
        KIDBFKJEJJD::KIDBFKJEJJD_PBPJJFPBHHK,
        KIDBFKJEJJD::KIDBFKJEJJD_HONJDBCACEB,
        KIDBFKJEJJD::KIDBFKJEJJD_AGHGBNPIOGK,
        KIDBFKJEJJD::KIDBFKJEJJD_ECHEKPDIPPA,
        KIDBFKJEJJD::KIDBFKJEJJD_HJAIHJAHMKN,
        KIDBFKJEJJD::KIDBFKJEJJD_KOKCPOPBBCD,
        KIDBFKJEJJD::KIDBFKJEJJD_JGLNKENAIEB,
        KIDBFKJEJJD::KIDBFKJEJJD_MCOKJKLKHDL,
        KIDBFKJEJJD::KIDBFKJEJJD_FPHMFIPGANO,
        KIDBFKJEJJD::KIDBFKJEJJD_CFMGLJJOJDJ,
        KIDBFKJEJJD::KIDBFKJEJJD_FFLOLBNNBJJ,
        KIDBFKJEJJD::KIDBFKJEJJD_BBECFFBPOGG,
        KIDBFKJEJJD::KIDBFKJEJJD_ABAKFMHMHPD,
        KIDBFKJEJJD::KIDBFKJEJJD_HLKKHFGJEOL,
        KIDBFKJEJJD::KIDBFKJEJJD_JPADFDNCDAO,
        KIDBFKJEJJD::KIDBFKJEJJD_LDFPOBPPCIH,
        KIDBFKJEJJD::KIDBFKJEJJD_JHFOOFEBNEL,
        KIDBFKJEJJD::KIDBFKJEJJD_PFAAOODLAPI,
        KIDBFKJEJJD::KIDBFKJEJJD_BCOPKPAPNAI,
        KIDBFKJEJJD::KIDBFKJEJJD_OAMNNICMJLH,
        KIDBFKJEJJD::KIDBFKJEJJD_GONKEIBLBOI,
        KIDBFKJEJJD::KIDBFKJEJJD_AIHKMIKNPOH,
        KIDBFKJEJJD::KIDBFKJEJJD_KLNEFLGGGIL,
        KIDBFKJEJJD::KIDBFKJEJJD_MLGEKIJAIBO,
        KIDBFKJEJJD::KIDBFKJEJJD_CLOMOECMLPH,
        KIDBFKJEJJD::KIDBFKJEJJD_KGCPBEOGMOP,
        KIDBFKJEJJD::KIDBFKJEJJD_BLLKMJKMNIG,
        KIDBFKJEJJD::KIDBFKJEJJD_DOPJENGCOAN,
        KIDBFKJEJJD::KIDBFKJEJJD_CBPDMEEEOJP,
        KIDBFKJEJJD::KIDBFKJEJJD_COENAOLHFEL,
        KIDBFKJEJJD::KIDBFKJEJJD_PCMLAHACMPO,
        KIDBFKJEJJD::KIDBFKJEJJD_AFKIMICKEDM,
        KIDBFKJEJJD::KIDBFKJEJJD_LAKJLNGMLPC,
        KIDBFKJEJJD::KIDBFKJEJJD_KPALKJHKPED,
        KIDBFKJEJJD::KIDBFKJEJJD_LHBKEJCGNCF,
        KIDBFKJEJJD::KIDBFKJEJJD_GKDOBOKBGPK,
        KIDBFKJEJJD::KIDBFKJEJJD_OPFIKLLIHBH,
        KIDBFKJEJJD::KIDBFKJEJJD_IKANNBLIACL,
        KIDBFKJEJJD::KIDBFKJEJJD_MCFLGBJENJD,
        KIDBFKJEJJD::KIDBFKJEJJD_CEDFKEJBCCJ,
    ];
}

impl ::protobuf::EnumFull for KIDBFKJEJJD {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("KIDBFKJEJJD").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            KIDBFKJEJJD::KIDBFKJEJJD_NLCDGIPGFDJ => 0,
            KIDBFKJEJJD::KIDBFKJEJJD_HDDNALCIJDE => 1,
            KIDBFKJEJJD::KIDBFKJEJJD_PJMINBJDKCC => 2,
            KIDBFKJEJJD::KIDBFKJEJJD_IPDCEJGOFKI => 3,
            KIDBFKJEJJD::KIDBFKJEJJD_DGKKANKIDLG => 4,
            KIDBFKJEJJD::KIDBFKJEJJD_DOGHFIAJIHP => 5,
            KIDBFKJEJJD::KIDBFKJEJJD_DHHMBIGPPFB => 6,
            KIDBFKJEJJD::KIDBFKJEJJD_BLPDFGFMCBK => 7,
            KIDBFKJEJJD::KIDBFKJEJJD_OFIEPOPANGH => 8,
            KIDBFKJEJJD::KIDBFKJEJJD_BFMIAMIHIED => 9,
            KIDBFKJEJJD::KIDBFKJEJJD_JFLKFMHCFFF => 10,
            KIDBFKJEJJD::KIDBFKJEJJD_CAEEPLEGLCK => 11,
            KIDBFKJEJJD::KIDBFKJEJJD_EEMJCDKIJOP => 12,
            KIDBFKJEJJD::KIDBFKJEJJD_POACPAFBFKJ => 13,
            KIDBFKJEJJD::KIDBFKJEJJD_JIIJIOKAAOH => 14,
            KIDBFKJEJJD::KIDBFKJEJJD_IBPHMNFDGCA => 15,
            KIDBFKJEJJD::KIDBFKJEJJD_KJLKLPLIFDK => 16,
            KIDBFKJEJJD::KIDBFKJEJJD_HLAAGBFPKPH => 17,
            KIDBFKJEJJD::KIDBFKJEJJD_GNAOLJNMAFC => 18,
            KIDBFKJEJJD::KIDBFKJEJJD_LLGMMAPJDLI => 19,
            KIDBFKJEJJD::KIDBFKJEJJD_MKHNJMFNPBB => 20,
            KIDBFKJEJJD::KIDBFKJEJJD_FCNEJBELPDL => 21,
            KIDBFKJEJJD::KIDBFKJEJJD_PPBANCPJPHG => 22,
            KIDBFKJEJJD::KIDBFKJEJJD_KCCMJKHJMAB => 23,
            KIDBFKJEJJD::KIDBFKJEJJD_CLHGHKAAEIJ => 24,
            KIDBFKJEJJD::KIDBFKJEJJD_JBHLDLGENMB => 25,
            KIDBFKJEJJD::KIDBFKJEJJD_ONNNLNCMMGJ => 26,
            KIDBFKJEJJD::KIDBFKJEJJD_CJOBOBANBOA => 27,
            KIDBFKJEJJD::KIDBFKJEJJD_PBPJJFPBHHK => 28,
            KIDBFKJEJJD::KIDBFKJEJJD_HONJDBCACEB => 29,
            KIDBFKJEJJD::KIDBFKJEJJD_AGHGBNPIOGK => 30,
            KIDBFKJEJJD::KIDBFKJEJJD_ECHEKPDIPPA => 31,
            KIDBFKJEJJD::KIDBFKJEJJD_HJAIHJAHMKN => 32,
            KIDBFKJEJJD::KIDBFKJEJJD_KOKCPOPBBCD => 33,
            KIDBFKJEJJD::KIDBFKJEJJD_JGLNKENAIEB => 34,
            KIDBFKJEJJD::KIDBFKJEJJD_MCOKJKLKHDL => 35,
            KIDBFKJEJJD::KIDBFKJEJJD_FPHMFIPGANO => 36,
            KIDBFKJEJJD::KIDBFKJEJJD_CFMGLJJOJDJ => 37,
            KIDBFKJEJJD::KIDBFKJEJJD_FFLOLBNNBJJ => 38,
            KIDBFKJEJJD::KIDBFKJEJJD_BBECFFBPOGG => 39,
            KIDBFKJEJJD::KIDBFKJEJJD_ABAKFMHMHPD => 40,
            KIDBFKJEJJD::KIDBFKJEJJD_HLKKHFGJEOL => 41,
            KIDBFKJEJJD::KIDBFKJEJJD_JPADFDNCDAO => 42,
            KIDBFKJEJJD::KIDBFKJEJJD_LDFPOBPPCIH => 43,
            KIDBFKJEJJD::KIDBFKJEJJD_JHFOOFEBNEL => 44,
            KIDBFKJEJJD::KIDBFKJEJJD_PFAAOODLAPI => 45,
            KIDBFKJEJJD::KIDBFKJEJJD_BCOPKPAPNAI => 46,
            KIDBFKJEJJD::KIDBFKJEJJD_OAMNNICMJLH => 47,
            KIDBFKJEJJD::KIDBFKJEJJD_GONKEIBLBOI => 48,
            KIDBFKJEJJD::KIDBFKJEJJD_AIHKMIKNPOH => 49,
            KIDBFKJEJJD::KIDBFKJEJJD_KLNEFLGGGIL => 50,
            KIDBFKJEJJD::KIDBFKJEJJD_MLGEKIJAIBO => 51,
            KIDBFKJEJJD::KIDBFKJEJJD_CLOMOECMLPH => 52,
            KIDBFKJEJJD::KIDBFKJEJJD_KGCPBEOGMOP => 53,
            KIDBFKJEJJD::KIDBFKJEJJD_BLLKMJKMNIG => 54,
            KIDBFKJEJJD::KIDBFKJEJJD_DOPJENGCOAN => 55,
            KIDBFKJEJJD::KIDBFKJEJJD_CBPDMEEEOJP => 56,
            KIDBFKJEJJD::KIDBFKJEJJD_COENAOLHFEL => 57,
            KIDBFKJEJJD::KIDBFKJEJJD_PCMLAHACMPO => 58,
            KIDBFKJEJJD::KIDBFKJEJJD_AFKIMICKEDM => 59,
            KIDBFKJEJJD::KIDBFKJEJJD_LAKJLNGMLPC => 60,
            KIDBFKJEJJD::KIDBFKJEJJD_KPALKJHKPED => 61,
            KIDBFKJEJJD::KIDBFKJEJJD_LHBKEJCGNCF => 62,
            KIDBFKJEJJD::KIDBFKJEJJD_GKDOBOKBGPK => 63,
            KIDBFKJEJJD::KIDBFKJEJJD_OPFIKLLIHBH => 64,
            KIDBFKJEJJD::KIDBFKJEJJD_IKANNBLIACL => 65,
            KIDBFKJEJJD::KIDBFKJEJJD_MCFLGBJENJD => 66,
            KIDBFKJEJJD::KIDBFKJEJJD_CEDFKEJBCCJ => 67,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for KIDBFKJEJJD {
    fn default() -> Self {
        KIDBFKJEJJD::KIDBFKJEJJD_NLCDGIPGFDJ
    }
}

impl KIDBFKJEJJD {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<KIDBFKJEJJD>("KIDBFKJEJJD")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11KIDBFKJEJJD.proto*\xc1\x0f\n\x0bKIDBFKJEJJD\x12\x1b\n\x17KIDBFKJEJ\
    JD_NLCDGIPGFDJ\x10\0\x12\x1b\n\x17KIDBFKJEJJD_HDDNALCIJDE\x10/\x12\x1b\n\
    \x17KIDBFKJEJJD_PJMINBJDKCC\x10:\x12\x1b\n\x17KIDBFKJEJJD_IPDCEJGOFKI\
    \x10\x03\x12\x1b\n\x17KIDBFKJEJJD_DGKKANKIDLG\x10\x18\x12\x1b\n\x17KIDBF\
    KJEJJD_DOGHFIAJIHP\x10\x1f\x12\x1b\n\x17KIDBFKJEJJD_DHHMBIGPPFB\x10%\x12\
    \x1b\n\x17KIDBFKJEJJD_BLPDFGFMCBK\x10$\x12\x1b\n\x17KIDBFKJEJJD_OFIEPOPA\
    NGH\x10\x0f\x12\x1b\n\x17KIDBFKJEJJD_BFMIAMIHIED\x10;\x12\x1b\n\x17KIDBF\
    KJEJJD_JFLKFMHCFFF\x10\x16\x12\x1b\n\x17KIDBFKJEJJD_CAEEPLEGLCK\x10\x14\
    \x12\x1b\n\x17KIDBFKJEJJD_EEMJCDKIJOP\x10\x1c\x12\x1b\n\x17KIDBFKJEJJD_P\
    OACPAFBFKJ\x10B\x12\x1b\n\x17KIDBFKJEJJD_JIIJIOKAAOH\x10\x17\x12\x1b\n\
    \x17KIDBFKJEJJD_IBPHMNFDGCA\x10`\x12\x1b\n\x17KIDBFKJEJJD_KJLKLPLIFDK\
    \x10\t\x12\x1b\n\x17KIDBFKJEJJD_HLAAGBFPKPH\x108\x12\x1b\n\x17KIDBFKJEJJ\
    D_GNAOLJNMAFC\x10\x19\x12\x1b\n\x17KIDBFKJEJJD_LLGMMAPJDLI\x10]\x12\x1b\
    \n\x17KIDBFKJEJJD_MKHNJMFNPBB\x10L\x12\x1b\n\x17KIDBFKJEJJD_FCNEJBELPDL\
    \x10\x15\x12\x1b\n\x17KIDBFKJEJJD_PPBANCPJPHG\x10\x12\x12\x1b\n\x17KIDBF\
    KJEJJD_KCCMJKHJMAB\x10[\x12\x1b\n\x17KIDBFKJEJJD_CLHGHKAAEIJ\x10U\x12\
    \x1b\n\x17KIDBFKJEJJD_JBHLDLGENMB\x10\x20\x12\x1b\n\x17KIDBFKJEJJD_ONNNL\
    NCMMGJ\x10N\x12\x1b\n\x17KIDBFKJEJJD_CJOBOBANBOA\x10\x1d\x12\x1b\n\x17KI\
    DBFKJEJJD_PBPJJFPBHHK\x10Q\x12\x1b\n\x17KIDBFKJEJJD_HONJDBCACEB\x107\x12\
    \x1b\n\x17KIDBFKJEJJD_AGHGBNPIOGK\x106\x12\x1b\n\x17KIDBFKJEJJD_ECHEKPDI\
    PPA\x10\x06\x12\x1b\n\x17KIDBFKJEJJD_HJAIHJAHMKN\x10K\x12\x1b\n\x17KIDBF\
    KJEJJD_KOKCPOPBBCD\x10D\x12\x1b\n\x17KIDBFKJEJJD_JGLNKENAIEB\x10>\x12\
    \x1b\n\x17KIDBFKJEJJD_MCOKJKLKHDL\x10'\x12\x1b\n\x17KIDBFKJEJJD_FPHMFIPG\
    ANO\x10\x05\x12\x1b\n\x17KIDBFKJEJJD_CFMGLJJOJDJ\x10?\x12\x1b\n\x17KIDBF\
    KJEJJD_FFLOLBNNBJJ\x10\n\x12\x1b\n\x17KIDBFKJEJJD_BBECFFBPOGG\x10I\x12\
    \x1b\n\x17KIDBFKJEJJD_ABAKFMHMHPD\x10_\x12\x1b\n\x17KIDBFKJEJJD_HLKKHFGJ\
    EOL\x10\"\x12\x1b\n\x17KIDBFKJEJJD_JPADFDNCDAO\x102\x12\x1b\n\x17KIDBFKJ\
    EJJD_LDFPOBPPCIH\x10(\x12\x1b\n\x17KIDBFKJEJJD_JHFOOFEBNEL\x10=\x12\x1b\
    \n\x17KIDBFKJEJJD_PFAAOODLAPI\x10\x01\x12\x1b\n\x17KIDBFKJEJJD_BCOPKPAPN\
    AI\x10,\x12\x1b\n\x17KIDBFKJEJJD_OAMNNICMJLH\x10A\x12\x1b\n\x17KIDBFKJEJ\
    JD_GONKEIBLBOI\x10\x0b\x12\x1b\n\x17KIDBFKJEJJD_AIHKMIKNPOH\x10\x13\x12\
    \x1b\n\x17KIDBFKJEJJD_KLNEFLGGGIL\x10\r\x12\x1b\n\x17KIDBFKJEJJD_MLGEKIJ\
    AIBO\x10\x04\x12\x1b\n\x17KIDBFKJEJJD_CLOMOECMLPH\x10F\x12\x1b\n\x17KIDB\
    FKJEJJD_KGCPBEOGMOP\x10c\x12\x1b\n\x17KIDBFKJEJJD_BLLKMJKMNIG\x10)\x12\
    \x1b\n\x17KIDBFKJEJJD_DOPJENGCOAN\x10E\x12\x1b\n\x17KIDBFKJEJJD_CBPDMEEE\
    OJP\x10\x08\x12\x1b\n\x17KIDBFKJEJJD_COENAOLHFEL\x109\x12\x1b\n\x17KIDBF\
    KJEJJD_PCMLAHACMPO\x10G\x12\x1b\n\x17KIDBFKJEJJD_AFKIMICKEDM\x10.\x12\
    \x1b\n\x17KIDBFKJEJJD_LAKJLNGMLPC\x10\x1e\x12\x1b\n\x17KIDBFKJEJJD_KPALK\
    JHKPED\x10\x1a\x12\x1b\n\x17KIDBFKJEJJD_LHBKEJCGNCF\x10b\x12\x1b\n\x17KI\
    DBFKJEJJD_GKDOBOKBGPK\x10\x0e\x12\x1b\n\x17KIDBFKJEJJD_OPFIKLLIHBH\x10\
    \x07\x12\x1b\n\x17KIDBFKJEJJD_IKANNBLIACL\x104\x12\x1b\n\x17KIDBFKJEJJD_\
    MCFLGBJENJD\x10#\x12\x1b\n\x17KIDBFKJEJJD_CEDFKEJBCCJ\x105b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(KIDBFKJEJJD::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
