// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `MFAHJPCHPIN.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:MFAHJPCHPIN)
pub enum MFAHJPCHPIN {
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_NLCDGIPGFDJ)
    MFAHJPCHPIN_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_ILBHOGLEIAG)
    MFAHJPCHPIN_ILBHOGLEIAG = 7377,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_CNLPNHLGIBG)
    MFAHJPCHPIN_CNLPNHLGIBG = 7362,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_HCAGJGCDPON)
    MFAHJPCHPIN_HCAGJGCDPON = 7360,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_OJNIMDFCMAM)
    MFAHJPCHPIN_OJNIMDFCMAM = 7366,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_PMBEKLJENGI)
    MFAHJPCHPIN_PMBEKLJENGI = 7372,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_CGNHPMEHMMF)
    MFAHJPCHPIN_CGNHPMEHMMF = 7355,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_JEBLFCMDDMD)
    MFAHJPCHPIN_JEBLFCMDDMD = 7353,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_CIJEGGADKJK)
    MFAHJPCHPIN_CIJEGGADKJK = 7385,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_KCIIOPIKCMN)
    MFAHJPCHPIN_KCIIOPIKCMN = 7381,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_OPELNAJOBHP)
    MFAHJPCHPIN_OPELNAJOBHP = 7390,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_GFEEMPEJIMH)
    MFAHJPCHPIN_GFEEMPEJIMH = 7375,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_MHKIHNGPLNA)
    MFAHJPCHPIN_MHKIHNGPLNA = 7361,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_ACOHEGOOIJA)
    MFAHJPCHPIN_ACOHEGOOIJA = 7359,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_APHHBOJIFDC)
    MFAHJPCHPIN_APHHBOJIFDC = 7364,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_NCACLCLAGPM)
    MFAHJPCHPIN_NCACLCLAGPM = 7363,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_BOJKKDBEFNL)
    MFAHJPCHPIN_BOJKKDBEFNL = 7365,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_HKGPMMJLLCP)
    MFAHJPCHPIN_HKGPMMJLLCP = 7397,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_OAOAGMHHEOB)
    MFAHJPCHPIN_OAOAGMHHEOB = 7356,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_PPMLDMMDPCK)
    MFAHJPCHPIN_PPMLDMMDPCK = 7387,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_MCBNPGCBMOK)
    MFAHJPCHPIN_MCBNPGCBMOK = 7383,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_PFHPPNDDCDN)
    MFAHJPCHPIN_PFHPPNDDCDN = 7399,
    // @@protoc_insertion_point(enum_value:MFAHJPCHPIN.MFAHJPCHPIN_PJJBGLIJHIJ)
    MFAHJPCHPIN_PJJBGLIJHIJ = 7354,
}

impl ::protobuf::Enum for MFAHJPCHPIN {
    const NAME: &'static str = "MFAHJPCHPIN";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<MFAHJPCHPIN> {
        match value {
            0 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_NLCDGIPGFDJ),
            7377 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_ILBHOGLEIAG),
            7362 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_CNLPNHLGIBG),
            7360 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_HCAGJGCDPON),
            7366 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_OJNIMDFCMAM),
            7372 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_PMBEKLJENGI),
            7355 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_CGNHPMEHMMF),
            7353 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_JEBLFCMDDMD),
            7385 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_CIJEGGADKJK),
            7381 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_KCIIOPIKCMN),
            7390 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_OPELNAJOBHP),
            7375 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_GFEEMPEJIMH),
            7361 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_MHKIHNGPLNA),
            7359 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_ACOHEGOOIJA),
            7364 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_APHHBOJIFDC),
            7363 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_NCACLCLAGPM),
            7365 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_BOJKKDBEFNL),
            7397 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_HKGPMMJLLCP),
            7356 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_OAOAGMHHEOB),
            7387 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_PPMLDMMDPCK),
            7383 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_MCBNPGCBMOK),
            7399 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_PFHPPNDDCDN),
            7354 => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_PJJBGLIJHIJ),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<MFAHJPCHPIN> {
        match str {
            "MFAHJPCHPIN_NLCDGIPGFDJ" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_NLCDGIPGFDJ),
            "MFAHJPCHPIN_ILBHOGLEIAG" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_ILBHOGLEIAG),
            "MFAHJPCHPIN_CNLPNHLGIBG" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_CNLPNHLGIBG),
            "MFAHJPCHPIN_HCAGJGCDPON" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_HCAGJGCDPON),
            "MFAHJPCHPIN_OJNIMDFCMAM" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_OJNIMDFCMAM),
            "MFAHJPCHPIN_PMBEKLJENGI" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_PMBEKLJENGI),
            "MFAHJPCHPIN_CGNHPMEHMMF" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_CGNHPMEHMMF),
            "MFAHJPCHPIN_JEBLFCMDDMD" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_JEBLFCMDDMD),
            "MFAHJPCHPIN_CIJEGGADKJK" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_CIJEGGADKJK),
            "MFAHJPCHPIN_KCIIOPIKCMN" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_KCIIOPIKCMN),
            "MFAHJPCHPIN_OPELNAJOBHP" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_OPELNAJOBHP),
            "MFAHJPCHPIN_GFEEMPEJIMH" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_GFEEMPEJIMH),
            "MFAHJPCHPIN_MHKIHNGPLNA" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_MHKIHNGPLNA),
            "MFAHJPCHPIN_ACOHEGOOIJA" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_ACOHEGOOIJA),
            "MFAHJPCHPIN_APHHBOJIFDC" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_APHHBOJIFDC),
            "MFAHJPCHPIN_NCACLCLAGPM" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_NCACLCLAGPM),
            "MFAHJPCHPIN_BOJKKDBEFNL" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_BOJKKDBEFNL),
            "MFAHJPCHPIN_HKGPMMJLLCP" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_HKGPMMJLLCP),
            "MFAHJPCHPIN_OAOAGMHHEOB" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_OAOAGMHHEOB),
            "MFAHJPCHPIN_PPMLDMMDPCK" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_PPMLDMMDPCK),
            "MFAHJPCHPIN_MCBNPGCBMOK" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_MCBNPGCBMOK),
            "MFAHJPCHPIN_PFHPPNDDCDN" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_PFHPPNDDCDN),
            "MFAHJPCHPIN_PJJBGLIJHIJ" => ::std::option::Option::Some(MFAHJPCHPIN::MFAHJPCHPIN_PJJBGLIJHIJ),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [MFAHJPCHPIN] = &[
        MFAHJPCHPIN::MFAHJPCHPIN_NLCDGIPGFDJ,
        MFAHJPCHPIN::MFAHJPCHPIN_ILBHOGLEIAG,
        MFAHJPCHPIN::MFAHJPCHPIN_CNLPNHLGIBG,
        MFAHJPCHPIN::MFAHJPCHPIN_HCAGJGCDPON,
        MFAHJPCHPIN::MFAHJPCHPIN_OJNIMDFCMAM,
        MFAHJPCHPIN::MFAHJPCHPIN_PMBEKLJENGI,
        MFAHJPCHPIN::MFAHJPCHPIN_CGNHPMEHMMF,
        MFAHJPCHPIN::MFAHJPCHPIN_JEBLFCMDDMD,
        MFAHJPCHPIN::MFAHJPCHPIN_CIJEGGADKJK,
        MFAHJPCHPIN::MFAHJPCHPIN_KCIIOPIKCMN,
        MFAHJPCHPIN::MFAHJPCHPIN_OPELNAJOBHP,
        MFAHJPCHPIN::MFAHJPCHPIN_GFEEMPEJIMH,
        MFAHJPCHPIN::MFAHJPCHPIN_MHKIHNGPLNA,
        MFAHJPCHPIN::MFAHJPCHPIN_ACOHEGOOIJA,
        MFAHJPCHPIN::MFAHJPCHPIN_APHHBOJIFDC,
        MFAHJPCHPIN::MFAHJPCHPIN_NCACLCLAGPM,
        MFAHJPCHPIN::MFAHJPCHPIN_BOJKKDBEFNL,
        MFAHJPCHPIN::MFAHJPCHPIN_HKGPMMJLLCP,
        MFAHJPCHPIN::MFAHJPCHPIN_OAOAGMHHEOB,
        MFAHJPCHPIN::MFAHJPCHPIN_PPMLDMMDPCK,
        MFAHJPCHPIN::MFAHJPCHPIN_MCBNPGCBMOK,
        MFAHJPCHPIN::MFAHJPCHPIN_PFHPPNDDCDN,
        MFAHJPCHPIN::MFAHJPCHPIN_PJJBGLIJHIJ,
    ];
}

impl ::protobuf::EnumFull for MFAHJPCHPIN {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("MFAHJPCHPIN").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            MFAHJPCHPIN::MFAHJPCHPIN_NLCDGIPGFDJ => 0,
            MFAHJPCHPIN::MFAHJPCHPIN_ILBHOGLEIAG => 1,
            MFAHJPCHPIN::MFAHJPCHPIN_CNLPNHLGIBG => 2,
            MFAHJPCHPIN::MFAHJPCHPIN_HCAGJGCDPON => 3,
            MFAHJPCHPIN::MFAHJPCHPIN_OJNIMDFCMAM => 4,
            MFAHJPCHPIN::MFAHJPCHPIN_PMBEKLJENGI => 5,
            MFAHJPCHPIN::MFAHJPCHPIN_CGNHPMEHMMF => 6,
            MFAHJPCHPIN::MFAHJPCHPIN_JEBLFCMDDMD => 7,
            MFAHJPCHPIN::MFAHJPCHPIN_CIJEGGADKJK => 8,
            MFAHJPCHPIN::MFAHJPCHPIN_KCIIOPIKCMN => 9,
            MFAHJPCHPIN::MFAHJPCHPIN_OPELNAJOBHP => 10,
            MFAHJPCHPIN::MFAHJPCHPIN_GFEEMPEJIMH => 11,
            MFAHJPCHPIN::MFAHJPCHPIN_MHKIHNGPLNA => 12,
            MFAHJPCHPIN::MFAHJPCHPIN_ACOHEGOOIJA => 13,
            MFAHJPCHPIN::MFAHJPCHPIN_APHHBOJIFDC => 14,
            MFAHJPCHPIN::MFAHJPCHPIN_NCACLCLAGPM => 15,
            MFAHJPCHPIN::MFAHJPCHPIN_BOJKKDBEFNL => 16,
            MFAHJPCHPIN::MFAHJPCHPIN_HKGPMMJLLCP => 17,
            MFAHJPCHPIN::MFAHJPCHPIN_OAOAGMHHEOB => 18,
            MFAHJPCHPIN::MFAHJPCHPIN_PPMLDMMDPCK => 19,
            MFAHJPCHPIN::MFAHJPCHPIN_MCBNPGCBMOK => 20,
            MFAHJPCHPIN::MFAHJPCHPIN_PFHPPNDDCDN => 21,
            MFAHJPCHPIN::MFAHJPCHPIN_PJJBGLIJHIJ => 22,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for MFAHJPCHPIN {
    fn default() -> Self {
        MFAHJPCHPIN::MFAHJPCHPIN_NLCDGIPGFDJ
    }
}

impl MFAHJPCHPIN {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<MFAHJPCHPIN>("MFAHJPCHPIN")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11MFAHJPCHPIN.proto*\xbe\x05\n\x0bMFAHJPCHPIN\x12\x1b\n\x17MFAHJPCHP\
    IN_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17MFAHJPCHPIN_ILBHOGLEIAG\x10\xd19\x12\
    \x1c\n\x17MFAHJPCHPIN_CNLPNHLGIBG\x10\xc29\x12\x1c\n\x17MFAHJPCHPIN_HCAG\
    JGCDPON\x10\xc09\x12\x1c\n\x17MFAHJPCHPIN_OJNIMDFCMAM\x10\xc69\x12\x1c\n\
    \x17MFAHJPCHPIN_PMBEKLJENGI\x10\xcc9\x12\x1c\n\x17MFAHJPCHPIN_CGNHPMEHMM\
    F\x10\xbb9\x12\x1c\n\x17MFAHJPCHPIN_JEBLFCMDDMD\x10\xb99\x12\x1c\n\x17MF\
    AHJPCHPIN_CIJEGGADKJK\x10\xd99\x12\x1c\n\x17MFAHJPCHPIN_KCIIOPIKCMN\x10\
    \xd59\x12\x1c\n\x17MFAHJPCHPIN_OPELNAJOBHP\x10\xde9\x12\x1c\n\x17MFAHJPC\
    HPIN_GFEEMPEJIMH\x10\xcf9\x12\x1c\n\x17MFAHJPCHPIN_MHKIHNGPLNA\x10\xc19\
    \x12\x1c\n\x17MFAHJPCHPIN_ACOHEGOOIJA\x10\xbf9\x12\x1c\n\x17MFAHJPCHPIN_\
    APHHBOJIFDC\x10\xc49\x12\x1c\n\x17MFAHJPCHPIN_NCACLCLAGPM\x10\xc39\x12\
    \x1c\n\x17MFAHJPCHPIN_BOJKKDBEFNL\x10\xc59\x12\x1c\n\x17MFAHJPCHPIN_HKGP\
    MMJLLCP\x10\xe59\x12\x1c\n\x17MFAHJPCHPIN_OAOAGMHHEOB\x10\xbc9\x12\x1c\n\
    \x17MFAHJPCHPIN_PPMLDMMDPCK\x10\xdb9\x12\x1c\n\x17MFAHJPCHPIN_MCBNPGCBMO\
    K\x10\xd79\x12\x1c\n\x17MFAHJPCHPIN_PFHPPNDDCDN\x10\xe79\x12\x1c\n\x17MF\
    AHJPCHPIN_PJJBGLIJHIJ\x10\xba9b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(MFAHJPCHPIN::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
