// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `MKFFJFHICCC.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:MKFFJFHICCC)
pub enum MKFFJFHICCC {
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_NLCDGIPGFDJ)
    MKFFJFHICCC_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_ELFNDPILMAA)
    MKFFJFHICCC_ELFNDPILMAA = 9006,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_CIKABIHPHBB)
    MKFFJFHICCC_CIKABIHPHBB = 9014,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_GAJEAKPBNFF)
    MKFFJFHICCC_GAJEAKPBNFF = 9037,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_NMKDPKKOIND)
    MKFFJFHICCC_NMKDPKKOIND = 9015,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_MOOAPCIMGKL)
    MKFFJFHICCC_MOOAPCIMGKL = 9010,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_LGKONGHLLMO)
    MKFFJFHICCC_LGKONGHLLMO = 9040,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_IFKDHMBBDEE)
    MKFFJFHICCC_IFKDHMBBDEE = 9033,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_CCEHNGLMKDO)
    MKFFJFHICCC_CCEHNGLMKDO = 9004,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_NLEEGCLPGKJ)
    MKFFJFHICCC_NLEEGCLPGKJ = 9031,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_PKNBJGOAMAL)
    MKFFJFHICCC_PKNBJGOAMAL = 9025,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_JAFFDCKGMAA)
    MKFFJFHICCC_JAFFDCKGMAA = 9003,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_MFMBMPIHJMA)
    MKFFJFHICCC_MFMBMPIHJMA = 9012,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_EJMPJIMMGFM)
    MKFFJFHICCC_EJMPJIMMGFM = 9011,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_KPABCGKCOCI)
    MKFFJFHICCC_KPABCGKCOCI = 9027,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_GOLFFCAEBAA)
    MKFFJFHICCC_GOLFFCAEBAA = 9009,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_NJOOMIGMMPH)
    MKFFJFHICCC_NJOOMIGMMPH = 9022,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_GMGCKLMOMLC)
    MKFFJFHICCC_GMGCKLMOMLC = 9047,
    // @@protoc_insertion_point(enum_value:MKFFJFHICCC.MKFFJFHICCC_ABCCLHIPMGG)
    MKFFJFHICCC_ABCCLHIPMGG = 9049,
}

impl ::protobuf::Enum for MKFFJFHICCC {
    const NAME: &'static str = "MKFFJFHICCC";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<MKFFJFHICCC> {
        match value {
            0 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_NLCDGIPGFDJ),
            9006 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_ELFNDPILMAA),
            9014 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_CIKABIHPHBB),
            9037 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_GAJEAKPBNFF),
            9015 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_NMKDPKKOIND),
            9010 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_MOOAPCIMGKL),
            9040 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_LGKONGHLLMO),
            9033 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_IFKDHMBBDEE),
            9004 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_CCEHNGLMKDO),
            9031 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_NLEEGCLPGKJ),
            9025 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_PKNBJGOAMAL),
            9003 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_JAFFDCKGMAA),
            9012 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_MFMBMPIHJMA),
            9011 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_EJMPJIMMGFM),
            9027 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_KPABCGKCOCI),
            9009 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_GOLFFCAEBAA),
            9022 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_NJOOMIGMMPH),
            9047 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_GMGCKLMOMLC),
            9049 => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_ABCCLHIPMGG),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<MKFFJFHICCC> {
        match str {
            "MKFFJFHICCC_NLCDGIPGFDJ" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_NLCDGIPGFDJ),
            "MKFFJFHICCC_ELFNDPILMAA" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_ELFNDPILMAA),
            "MKFFJFHICCC_CIKABIHPHBB" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_CIKABIHPHBB),
            "MKFFJFHICCC_GAJEAKPBNFF" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_GAJEAKPBNFF),
            "MKFFJFHICCC_NMKDPKKOIND" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_NMKDPKKOIND),
            "MKFFJFHICCC_MOOAPCIMGKL" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_MOOAPCIMGKL),
            "MKFFJFHICCC_LGKONGHLLMO" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_LGKONGHLLMO),
            "MKFFJFHICCC_IFKDHMBBDEE" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_IFKDHMBBDEE),
            "MKFFJFHICCC_CCEHNGLMKDO" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_CCEHNGLMKDO),
            "MKFFJFHICCC_NLEEGCLPGKJ" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_NLEEGCLPGKJ),
            "MKFFJFHICCC_PKNBJGOAMAL" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_PKNBJGOAMAL),
            "MKFFJFHICCC_JAFFDCKGMAA" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_JAFFDCKGMAA),
            "MKFFJFHICCC_MFMBMPIHJMA" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_MFMBMPIHJMA),
            "MKFFJFHICCC_EJMPJIMMGFM" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_EJMPJIMMGFM),
            "MKFFJFHICCC_KPABCGKCOCI" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_KPABCGKCOCI),
            "MKFFJFHICCC_GOLFFCAEBAA" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_GOLFFCAEBAA),
            "MKFFJFHICCC_NJOOMIGMMPH" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_NJOOMIGMMPH),
            "MKFFJFHICCC_GMGCKLMOMLC" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_GMGCKLMOMLC),
            "MKFFJFHICCC_ABCCLHIPMGG" => ::std::option::Option::Some(MKFFJFHICCC::MKFFJFHICCC_ABCCLHIPMGG),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [MKFFJFHICCC] = &[
        MKFFJFHICCC::MKFFJFHICCC_NLCDGIPGFDJ,
        MKFFJFHICCC::MKFFJFHICCC_ELFNDPILMAA,
        MKFFJFHICCC::MKFFJFHICCC_CIKABIHPHBB,
        MKFFJFHICCC::MKFFJFHICCC_GAJEAKPBNFF,
        MKFFJFHICCC::MKFFJFHICCC_NMKDPKKOIND,
        MKFFJFHICCC::MKFFJFHICCC_MOOAPCIMGKL,
        MKFFJFHICCC::MKFFJFHICCC_LGKONGHLLMO,
        MKFFJFHICCC::MKFFJFHICCC_IFKDHMBBDEE,
        MKFFJFHICCC::MKFFJFHICCC_CCEHNGLMKDO,
        MKFFJFHICCC::MKFFJFHICCC_NLEEGCLPGKJ,
        MKFFJFHICCC::MKFFJFHICCC_PKNBJGOAMAL,
        MKFFJFHICCC::MKFFJFHICCC_JAFFDCKGMAA,
        MKFFJFHICCC::MKFFJFHICCC_MFMBMPIHJMA,
        MKFFJFHICCC::MKFFJFHICCC_EJMPJIMMGFM,
        MKFFJFHICCC::MKFFJFHICCC_KPABCGKCOCI,
        MKFFJFHICCC::MKFFJFHICCC_GOLFFCAEBAA,
        MKFFJFHICCC::MKFFJFHICCC_NJOOMIGMMPH,
        MKFFJFHICCC::MKFFJFHICCC_GMGCKLMOMLC,
        MKFFJFHICCC::MKFFJFHICCC_ABCCLHIPMGG,
    ];
}

impl ::protobuf::EnumFull for MKFFJFHICCC {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("MKFFJFHICCC").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            MKFFJFHICCC::MKFFJFHICCC_NLCDGIPGFDJ => 0,
            MKFFJFHICCC::MKFFJFHICCC_ELFNDPILMAA => 1,
            MKFFJFHICCC::MKFFJFHICCC_CIKABIHPHBB => 2,
            MKFFJFHICCC::MKFFJFHICCC_GAJEAKPBNFF => 3,
            MKFFJFHICCC::MKFFJFHICCC_NMKDPKKOIND => 4,
            MKFFJFHICCC::MKFFJFHICCC_MOOAPCIMGKL => 5,
            MKFFJFHICCC::MKFFJFHICCC_LGKONGHLLMO => 6,
            MKFFJFHICCC::MKFFJFHICCC_IFKDHMBBDEE => 7,
            MKFFJFHICCC::MKFFJFHICCC_CCEHNGLMKDO => 8,
            MKFFJFHICCC::MKFFJFHICCC_NLEEGCLPGKJ => 9,
            MKFFJFHICCC::MKFFJFHICCC_PKNBJGOAMAL => 10,
            MKFFJFHICCC::MKFFJFHICCC_JAFFDCKGMAA => 11,
            MKFFJFHICCC::MKFFJFHICCC_MFMBMPIHJMA => 12,
            MKFFJFHICCC::MKFFJFHICCC_EJMPJIMMGFM => 13,
            MKFFJFHICCC::MKFFJFHICCC_KPABCGKCOCI => 14,
            MKFFJFHICCC::MKFFJFHICCC_GOLFFCAEBAA => 15,
            MKFFJFHICCC::MKFFJFHICCC_NJOOMIGMMPH => 16,
            MKFFJFHICCC::MKFFJFHICCC_GMGCKLMOMLC => 17,
            MKFFJFHICCC::MKFFJFHICCC_ABCCLHIPMGG => 18,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for MKFFJFHICCC {
    fn default() -> Self {
        MKFFJFHICCC::MKFFJFHICCC_NLCDGIPGFDJ
    }
}

impl MKFFJFHICCC {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<MKFFJFHICCC>("MKFFJFHICCC")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11MKFFJFHICCC.proto*\xc6\x04\n\x0bMKFFJFHICCC\x12\x1b\n\x17MKFFJFHIC\
    CC_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17MKFFJFHICCC_ELFNDPILMAA\x10\xaeF\x12\
    \x1c\n\x17MKFFJFHICCC_CIKABIHPHBB\x10\xb6F\x12\x1c\n\x17MKFFJFHICCC_GAJE\
    AKPBNFF\x10\xcdF\x12\x1c\n\x17MKFFJFHICCC_NMKDPKKOIND\x10\xb7F\x12\x1c\n\
    \x17MKFFJFHICCC_MOOAPCIMGKL\x10\xb2F\x12\x1c\n\x17MKFFJFHICCC_LGKONGHLLM\
    O\x10\xd0F\x12\x1c\n\x17MKFFJFHICCC_IFKDHMBBDEE\x10\xc9F\x12\x1c\n\x17MK\
    FFJFHICCC_CCEHNGLMKDO\x10\xacF\x12\x1c\n\x17MKFFJFHICCC_NLEEGCLPGKJ\x10\
    \xc7F\x12\x1c\n\x17MKFFJFHICCC_PKNBJGOAMAL\x10\xc1F\x12\x1c\n\x17MKFFJFH\
    ICCC_JAFFDCKGMAA\x10\xabF\x12\x1c\n\x17MKFFJFHICCC_MFMBMPIHJMA\x10\xb4F\
    \x12\x1c\n\x17MKFFJFHICCC_EJMPJIMMGFM\x10\xb3F\x12\x1c\n\x17MKFFJFHICCC_\
    KPABCGKCOCI\x10\xc3F\x12\x1c\n\x17MKFFJFHICCC_GOLFFCAEBAA\x10\xb1F\x12\
    \x1c\n\x17MKFFJFHICCC_NJOOMIGMMPH\x10\xbeF\x12\x1c\n\x17MKFFJFHICCC_GMGC\
    KLMOMLC\x10\xd7F\x12\x1c\n\x17MKFFJFHICCC_ABCCLHIPMGG\x10\xd9Fb\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(MKFFJFHICCC::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
