// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `NCBOENDMDIC.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:NCBOENDMDIC)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NCBOENDMDIC {
    // message fields
    // @@protoc_insertion_point(field:NCBOENDMDIC.level)
    pub level: u32,
    // @@protoc_insertion_point(field:NCBOENDMDIC.PDABDEJBPEL)
    pub PDABDEJBPEL: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:NCBOENDMDIC.HBDMBLAPEMH)
    pub HBDMBLAPEMH: ::std::vec::Vec<super::KDANACKPJIP::KDANACKPJIP>,
    // @@protoc_insertion_point(field:NCBOENDMDIC.retcode)
    pub retcode: u32,
    // @@protoc_insertion_point(field:NCBOENDMDIC.NFAOAGIFKEG)
    pub NFAOAGIFKEG: u32,
    // @@protoc_insertion_point(field:NCBOENDMDIC.HINFJMIMBIN)
    pub HINFJMIMBIN: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:NCBOENDMDIC.ILLHHMHBJCG)
    pub ILLHHMHBJCG: u32,
    // @@protoc_insertion_point(field:NCBOENDMDIC.LDEJLFKJBCL)
    pub LDEJLFKJBCL: ::std::vec::Vec<super::GCJCLFOLBPP::GCJCLFOLBPP>,
    // special fields
    // @@protoc_insertion_point(special_field:NCBOENDMDIC.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NCBOENDMDIC {
    fn default() -> &'a NCBOENDMDIC {
        <NCBOENDMDIC as ::protobuf::Message>::default_instance()
    }
}

impl NCBOENDMDIC {
    pub fn new() -> NCBOENDMDIC {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "level",
            |m: &NCBOENDMDIC| { &m.level },
            |m: &mut NCBOENDMDIC| { &mut m.level },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "PDABDEJBPEL",
            |m: &NCBOENDMDIC| { &m.PDABDEJBPEL },
            |m: &mut NCBOENDMDIC| { &mut m.PDABDEJBPEL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "HBDMBLAPEMH",
            |m: &NCBOENDMDIC| { &m.HBDMBLAPEMH },
            |m: &mut NCBOENDMDIC| { &mut m.HBDMBLAPEMH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retcode",
            |m: &NCBOENDMDIC| { &m.retcode },
            |m: &mut NCBOENDMDIC| { &mut m.retcode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NFAOAGIFKEG",
            |m: &NCBOENDMDIC| { &m.NFAOAGIFKEG },
            |m: &mut NCBOENDMDIC| { &mut m.NFAOAGIFKEG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "HINFJMIMBIN",
            |m: &NCBOENDMDIC| { &m.HINFJMIMBIN },
            |m: &mut NCBOENDMDIC| { &mut m.HINFJMIMBIN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ILLHHMHBJCG",
            |m: &NCBOENDMDIC| { &m.ILLHHMHBJCG },
            |m: &mut NCBOENDMDIC| { &mut m.ILLHHMHBJCG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "LDEJLFKJBCL",
            |m: &NCBOENDMDIC| { &m.LDEJLFKJBCL },
            |m: &mut NCBOENDMDIC| { &mut m.LDEJLFKJBCL },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NCBOENDMDIC>(
            "NCBOENDMDIC",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NCBOENDMDIC {
    const NAME: &'static str = "NCBOENDMDIC";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                16 => {
                    self.level = is.read_uint32()?;
                },
                26 => {
                    is.read_repeated_packed_uint32_into(&mut self.PDABDEJBPEL)?;
                },
                24 => {
                    self.PDABDEJBPEL.push(is.read_uint32()?);
                },
                34 => {
                    self.HBDMBLAPEMH.push(is.read_message()?);
                },
                48 => {
                    self.retcode = is.read_uint32()?;
                },
                56 => {
                    self.NFAOAGIFKEG = is.read_uint32()?;
                },
                90 => {
                    is.read_repeated_packed_uint32_into(&mut self.HINFJMIMBIN)?;
                },
                88 => {
                    self.HINFJMIMBIN.push(is.read_uint32()?);
                },
                112 => {
                    self.ILLHHMHBJCG = is.read_uint32()?;
                },
                122 => {
                    self.LDEJLFKJBCL.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.level != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.level);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(3, &self.PDABDEJBPEL);
        for value in &self.HBDMBLAPEMH {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.retcode != 0 {
            my_size += ::protobuf::rt::uint32_size(6, self.retcode);
        }
        if self.NFAOAGIFKEG != 0 {
            my_size += ::protobuf::rt::uint32_size(7, self.NFAOAGIFKEG);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(11, &self.HINFJMIMBIN);
        if self.ILLHHMHBJCG != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.ILLHHMHBJCG);
        }
        for value in &self.LDEJLFKJBCL {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.level != 0 {
            os.write_uint32(2, self.level)?;
        }
        os.write_repeated_packed_uint32(3, &self.PDABDEJBPEL)?;
        for v in &self.HBDMBLAPEMH {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        if self.retcode != 0 {
            os.write_uint32(6, self.retcode)?;
        }
        if self.NFAOAGIFKEG != 0 {
            os.write_uint32(7, self.NFAOAGIFKEG)?;
        }
        os.write_repeated_packed_uint32(11, &self.HINFJMIMBIN)?;
        if self.ILLHHMHBJCG != 0 {
            os.write_uint32(14, self.ILLHHMHBJCG)?;
        }
        for v in &self.LDEJLFKJBCL {
            ::protobuf::rt::write_message_field_with_cached_size(15, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NCBOENDMDIC {
        NCBOENDMDIC::new()
    }

    fn clear(&mut self) {
        self.level = 0;
        self.PDABDEJBPEL.clear();
        self.HBDMBLAPEMH.clear();
        self.retcode = 0;
        self.NFAOAGIFKEG = 0;
        self.HINFJMIMBIN.clear();
        self.ILLHHMHBJCG = 0;
        self.LDEJLFKJBCL.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NCBOENDMDIC {
        static instance: NCBOENDMDIC = NCBOENDMDIC {
            level: 0,
            PDABDEJBPEL: ::std::vec::Vec::new(),
            HBDMBLAPEMH: ::std::vec::Vec::new(),
            retcode: 0,
            NFAOAGIFKEG: 0,
            HINFJMIMBIN: ::std::vec::Vec::new(),
            ILLHHMHBJCG: 0,
            LDEJLFKJBCL: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NCBOENDMDIC {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NCBOENDMDIC").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NCBOENDMDIC {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NCBOENDMDIC {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11NCBOENDMDIC.proto\x1a\x11GCJCLFOLBPP.proto\x1a\x11KDANACKPJIP.prot\
    o\"\xa5\x02\n\x0bNCBOENDMDIC\x12\x14\n\x05level\x18\x02\x20\x01(\rR\x05l\
    evel\x12\x20\n\x0bPDABDEJBPEL\x18\x03\x20\x03(\rR\x0bPDABDEJBPEL\x12.\n\
    \x0bHBDMBLAPEMH\x18\x04\x20\x03(\x0b2\x0c.KDANACKPJIPR\x0bHBDMBLAPEMH\
    \x12\x18\n\x07retcode\x18\x06\x20\x01(\rR\x07retcode\x12\x20\n\x0bNFAOAG\
    IFKEG\x18\x07\x20\x01(\rR\x0bNFAOAGIFKEG\x12\x20\n\x0bHINFJMIMBIN\x18\
    \x0b\x20\x03(\rR\x0bHINFJMIMBIN\x12\x20\n\x0bILLHHMHBJCG\x18\x0e\x20\x01\
    (\rR\x0bILLHHMHBJCG\x12.\n\x0bLDEJLFKJBCL\x18\x0f\x20\x03(\x0b2\x0c.GCJC\
    LFOLBPPR\x0bLDEJLFKJBCLb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::GCJCLFOLBPP::file_descriptor().clone());
            deps.push(super::KDANACKPJIP::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(NCBOENDMDIC::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
