// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `NKAEOPAAJLG.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:NKAEOPAAJLG)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NKAEOPAAJLG {
    // message oneof groups
    pub BHGKHELCPGO: ::std::option::Option<nkaeopaajlg::BHGKHELCPGO>,
    // special fields
    // @@protoc_insertion_point(special_field:NKAEOPAAJLG.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NKAEOPAAJLG {
    fn default() -> &'a NKAEOPAAJLG {
        <NKAEOPAAJLG as ::protobuf::Message>::default_instance()
    }
}

impl NKAEOPAAJLG {
    pub fn new() -> NKAEOPAAJLG {
        ::std::default::Default::default()
    }

    // uint32 EAGPOCAGMCA = 1;

    pub fn EAGPOCAGMCA(&self) -> u32 {
        match self.BHGKHELCPGO {
            ::std::option::Option::Some(nkaeopaajlg::BHGKHELCPGO::EAGPOCAGMCA(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_EAGPOCAGMCA(&mut self) {
        self.BHGKHELCPGO = ::std::option::Option::None;
    }

    pub fn has_EAGPOCAGMCA(&self) -> bool {
        match self.BHGKHELCPGO {
            ::std::option::Option::Some(nkaeopaajlg::BHGKHELCPGO::EAGPOCAGMCA(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_EAGPOCAGMCA(&mut self, v: u32) {
        self.BHGKHELCPGO = ::std::option::Option::Some(nkaeopaajlg::BHGKHELCPGO::EAGPOCAGMCA(v))
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "EAGPOCAGMCA",
            NKAEOPAAJLG::has_EAGPOCAGMCA,
            NKAEOPAAJLG::EAGPOCAGMCA,
            NKAEOPAAJLG::set_EAGPOCAGMCA,
        ));
        oneofs.push(nkaeopaajlg::BHGKHELCPGO::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NKAEOPAAJLG>(
            "NKAEOPAAJLG",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NKAEOPAAJLG {
    const NAME: &'static str = "NKAEOPAAJLG";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.BHGKHELCPGO = ::std::option::Option::Some(nkaeopaajlg::BHGKHELCPGO::EAGPOCAGMCA(is.read_uint32()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.BHGKHELCPGO {
            match v {
                &nkaeopaajlg::BHGKHELCPGO::EAGPOCAGMCA(v) => {
                    my_size += ::protobuf::rt::uint32_size(1, v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.BHGKHELCPGO {
            match v {
                &nkaeopaajlg::BHGKHELCPGO::EAGPOCAGMCA(v) => {
                    os.write_uint32(1, v)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NKAEOPAAJLG {
        NKAEOPAAJLG::new()
    }

    fn clear(&mut self) {
        self.BHGKHELCPGO = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NKAEOPAAJLG {
        static instance: NKAEOPAAJLG = NKAEOPAAJLG {
            BHGKHELCPGO: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NKAEOPAAJLG {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NKAEOPAAJLG").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NKAEOPAAJLG {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NKAEOPAAJLG {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `NKAEOPAAJLG`
pub mod nkaeopaajlg {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:NKAEOPAAJLG.BHGKHELCPGO)
    pub enum BHGKHELCPGO {
        // @@protoc_insertion_point(oneof_field:NKAEOPAAJLG.EAGPOCAGMCA)
        EAGPOCAGMCA(u32),
    }

    impl ::protobuf::Oneof for BHGKHELCPGO {
    }

    impl ::protobuf::OneofFull for BHGKHELCPGO {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::NKAEOPAAJLG as ::protobuf::MessageFull>::descriptor().oneof_by_name("BHGKHELCPGO").unwrap()).clone()
        }
    }

    impl BHGKHELCPGO {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<BHGKHELCPGO>("BHGKHELCPGO")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11NKAEOPAAJLG.proto\"@\n\x0bNKAEOPAAJLG\x12\"\n\x0bEAGPOCAGMCA\x18\
    \x01\x20\x01(\rH\0R\x0bEAGPOCAGMCAB\r\n\x0bBHGKHELCPGOb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(NKAEOPAAJLG::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
