// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `NLIBEBMOKCI.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:NLIBEBMOKCI)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NLIBEBMOKCI {
    // message fields
    // @@protoc_insertion_point(field:NLIBEBMOKCI.OFHBPNGDEGO)
    pub OFHBPNGDEGO: u32,
    // @@protoc_insertion_point(field:NLIBEBMOKCI.avatar_list)
    pub avatar_list: ::std::vec::Vec<super::PKCIPJBKAFO::PKCIPJBKAFO>,
    // @@protoc_insertion_point(field:NLIBEBMOKCI.battle_id)
    pub battle_id: u32,
    // @@protoc_insertion_point(field:NLIBEBMOKCI.buff_list)
    pub buff_list: ::std::vec::Vec<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:NLIBEBMOKCI.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NLIBEBMOKCI {
    fn default() -> &'a NLIBEBMOKCI {
        <NLIBEBMOKCI as ::protobuf::Message>::default_instance()
    }
}

impl NLIBEBMOKCI {
    pub fn new() -> NLIBEBMOKCI {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "OFHBPNGDEGO",
            |m: &NLIBEBMOKCI| { &m.OFHBPNGDEGO },
            |m: &mut NLIBEBMOKCI| { &mut m.OFHBPNGDEGO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "avatar_list",
            |m: &NLIBEBMOKCI| { &m.avatar_list },
            |m: &mut NLIBEBMOKCI| { &mut m.avatar_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "battle_id",
            |m: &NLIBEBMOKCI| { &m.battle_id },
            |m: &mut NLIBEBMOKCI| { &mut m.battle_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "buff_list",
            |m: &NLIBEBMOKCI| { &m.buff_list },
            |m: &mut NLIBEBMOKCI| { &mut m.buff_list },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NLIBEBMOKCI>(
            "NLIBEBMOKCI",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NLIBEBMOKCI {
    const NAME: &'static str = "NLIBEBMOKCI";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                24 => {
                    self.OFHBPNGDEGO = is.read_uint32()?;
                },
                66 => {
                    self.avatar_list.push(is.read_message()?);
                },
                72 => {
                    self.battle_id = is.read_uint32()?;
                },
                114 => {
                    is.read_repeated_packed_uint32_into(&mut self.buff_list)?;
                },
                112 => {
                    self.buff_list.push(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.OFHBPNGDEGO != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.OFHBPNGDEGO);
        }
        for value in &self.avatar_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.battle_id != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.battle_id);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(14, &self.buff_list);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.OFHBPNGDEGO != 0 {
            os.write_uint32(3, self.OFHBPNGDEGO)?;
        }
        for v in &self.avatar_list {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        };
        if self.battle_id != 0 {
            os.write_uint32(9, self.battle_id)?;
        }
        os.write_repeated_packed_uint32(14, &self.buff_list)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NLIBEBMOKCI {
        NLIBEBMOKCI::new()
    }

    fn clear(&mut self) {
        self.OFHBPNGDEGO = 0;
        self.avatar_list.clear();
        self.battle_id = 0;
        self.buff_list.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NLIBEBMOKCI {
        static instance: NLIBEBMOKCI = NLIBEBMOKCI {
            OFHBPNGDEGO: 0,
            avatar_list: ::std::vec::Vec::new(),
            battle_id: 0,
            buff_list: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NLIBEBMOKCI {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NLIBEBMOKCI").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NLIBEBMOKCI {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NLIBEBMOKCI {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11NLIBEBMOKCI.proto\x1a\x11PKCIPJBKAFO.proto\"\x98\x01\n\x0bNLIBEBMO\
    KCI\x12\x20\n\x0bOFHBPNGDEGO\x18\x03\x20\x01(\rR\x0bOFHBPNGDEGO\x12-\n\
    \x0bavatar_list\x18\x08\x20\x03(\x0b2\x0c.PKCIPJBKAFOR\navatarList\x12\
    \x1b\n\tbattle_id\x18\t\x20\x01(\rR\x08battleId\x12\x1b\n\tbuff_list\x18\
    \x0e\x20\x03(\rR\x08buffListb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::PKCIPJBKAFO::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(NLIBEBMOKCI::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
