// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `PHAPALJNLBE.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:PHAPALJNLBE)
pub enum PHAPALJNLBE {
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_NLCDGIPGFDJ)
    PHAPALJNLBE_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_PGGPINKJPJA)
    PHAPALJNLBE_PGGPINKJPJA = 7572,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_BHGAAEBOBOO)
    PHAPALJNLBE_BHGAAEBOBOO = 7575,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_KDBOPFPFGNF)
    PHAPALJNLBE_KDBOPFPFGNF = 7576,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_PJFKKFFGNJO)
    PHAPALJNLBE_PJFKKFFGNJO = 7577,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_APKIMNNBLIE)
    PHAPALJNLBE_APKIMNNBLIE = 7584,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_LKFCANNCJPC)
    PHAPALJNLBE_LKFCANNCJPC = 7585,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_LJFKOLLPGKP)
    PHAPALJNLBE_LJFKOLLPGKP = 7591,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_IMBKCHOMGBP)
    PHAPALJNLBE_IMBKCHOMGBP = 7574,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_GFPOONKNKPD)
    PHAPALJNLBE_GFPOONKNKPD = 7588,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_LHHIDMNPKGM)
    PHAPALJNLBE_LHHIDMNPKGM = 7573,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_PHBPMCMMCGJ)
    PHAPALJNLBE_PHBPMCMMCGJ = 7599,
    // @@protoc_insertion_point(enum_value:PHAPALJNLBE.PHAPALJNLBE_HJMPAGJEBOI)
    PHAPALJNLBE_HJMPAGJEBOI = 7590,
}

impl ::protobuf::Enum for PHAPALJNLBE {
    const NAME: &'static str = "PHAPALJNLBE";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<PHAPALJNLBE> {
        match value {
            0 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_NLCDGIPGFDJ),
            7572 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_PGGPINKJPJA),
            7575 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_BHGAAEBOBOO),
            7576 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_KDBOPFPFGNF),
            7577 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_PJFKKFFGNJO),
            7584 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_APKIMNNBLIE),
            7585 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_LKFCANNCJPC),
            7591 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_LJFKOLLPGKP),
            7574 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_IMBKCHOMGBP),
            7588 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_GFPOONKNKPD),
            7573 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_LHHIDMNPKGM),
            7599 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_PHBPMCMMCGJ),
            7590 => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_HJMPAGJEBOI),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<PHAPALJNLBE> {
        match str {
            "PHAPALJNLBE_NLCDGIPGFDJ" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_NLCDGIPGFDJ),
            "PHAPALJNLBE_PGGPINKJPJA" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_PGGPINKJPJA),
            "PHAPALJNLBE_BHGAAEBOBOO" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_BHGAAEBOBOO),
            "PHAPALJNLBE_KDBOPFPFGNF" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_KDBOPFPFGNF),
            "PHAPALJNLBE_PJFKKFFGNJO" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_PJFKKFFGNJO),
            "PHAPALJNLBE_APKIMNNBLIE" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_APKIMNNBLIE),
            "PHAPALJNLBE_LKFCANNCJPC" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_LKFCANNCJPC),
            "PHAPALJNLBE_LJFKOLLPGKP" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_LJFKOLLPGKP),
            "PHAPALJNLBE_IMBKCHOMGBP" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_IMBKCHOMGBP),
            "PHAPALJNLBE_GFPOONKNKPD" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_GFPOONKNKPD),
            "PHAPALJNLBE_LHHIDMNPKGM" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_LHHIDMNPKGM),
            "PHAPALJNLBE_PHBPMCMMCGJ" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_PHBPMCMMCGJ),
            "PHAPALJNLBE_HJMPAGJEBOI" => ::std::option::Option::Some(PHAPALJNLBE::PHAPALJNLBE_HJMPAGJEBOI),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [PHAPALJNLBE] = &[
        PHAPALJNLBE::PHAPALJNLBE_NLCDGIPGFDJ,
        PHAPALJNLBE::PHAPALJNLBE_PGGPINKJPJA,
        PHAPALJNLBE::PHAPALJNLBE_BHGAAEBOBOO,
        PHAPALJNLBE::PHAPALJNLBE_KDBOPFPFGNF,
        PHAPALJNLBE::PHAPALJNLBE_PJFKKFFGNJO,
        PHAPALJNLBE::PHAPALJNLBE_APKIMNNBLIE,
        PHAPALJNLBE::PHAPALJNLBE_LKFCANNCJPC,
        PHAPALJNLBE::PHAPALJNLBE_LJFKOLLPGKP,
        PHAPALJNLBE::PHAPALJNLBE_IMBKCHOMGBP,
        PHAPALJNLBE::PHAPALJNLBE_GFPOONKNKPD,
        PHAPALJNLBE::PHAPALJNLBE_LHHIDMNPKGM,
        PHAPALJNLBE::PHAPALJNLBE_PHBPMCMMCGJ,
        PHAPALJNLBE::PHAPALJNLBE_HJMPAGJEBOI,
    ];
}

impl ::protobuf::EnumFull for PHAPALJNLBE {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("PHAPALJNLBE").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            PHAPALJNLBE::PHAPALJNLBE_NLCDGIPGFDJ => 0,
            PHAPALJNLBE::PHAPALJNLBE_PGGPINKJPJA => 1,
            PHAPALJNLBE::PHAPALJNLBE_BHGAAEBOBOO => 2,
            PHAPALJNLBE::PHAPALJNLBE_KDBOPFPFGNF => 3,
            PHAPALJNLBE::PHAPALJNLBE_PJFKKFFGNJO => 4,
            PHAPALJNLBE::PHAPALJNLBE_APKIMNNBLIE => 5,
            PHAPALJNLBE::PHAPALJNLBE_LKFCANNCJPC => 6,
            PHAPALJNLBE::PHAPALJNLBE_LJFKOLLPGKP => 7,
            PHAPALJNLBE::PHAPALJNLBE_IMBKCHOMGBP => 8,
            PHAPALJNLBE::PHAPALJNLBE_GFPOONKNKPD => 9,
            PHAPALJNLBE::PHAPALJNLBE_LHHIDMNPKGM => 10,
            PHAPALJNLBE::PHAPALJNLBE_PHBPMCMMCGJ => 11,
            PHAPALJNLBE::PHAPALJNLBE_HJMPAGJEBOI => 12,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for PHAPALJNLBE {
    fn default() -> Self {
        PHAPALJNLBE::PHAPALJNLBE_NLCDGIPGFDJ
    }
}

impl PHAPALJNLBE {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<PHAPALJNLBE>("PHAPALJNLBE")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11PHAPALJNLBE.proto*\x92\x03\n\x0bPHAPALJNLBE\x12\x1b\n\x17PHAPALJNL\
    BE_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17PHAPALJNLBE_PGGPINKJPJA\x10\x94;\x12\
    \x1c\n\x17PHAPALJNLBE_BHGAAEBOBOO\x10\x97;\x12\x1c\n\x17PHAPALJNLBE_KDBO\
    PFPFGNF\x10\x98;\x12\x1c\n\x17PHAPALJNLBE_PJFKKFFGNJO\x10\x99;\x12\x1c\n\
    \x17PHAPALJNLBE_APKIMNNBLIE\x10\xa0;\x12\x1c\n\x17PHAPALJNLBE_LKFCANNCJP\
    C\x10\xa1;\x12\x1c\n\x17PHAPALJNLBE_LJFKOLLPGKP\x10\xa7;\x12\x1c\n\x17PH\
    APALJNLBE_IMBKCHOMGBP\x10\x96;\x12\x1c\n\x17PHAPALJNLBE_GFPOONKNKPD\x10\
    \xa4;\x12\x1c\n\x17PHAPALJNLBE_LHHIDMNPKGM\x10\x95;\x12\x1c\n\x17PHAPALJ\
    NLBE_PHBPMCMMCGJ\x10\xaf;\x12\x1c\n\x17PHAPALJNLBE_HJMPAGJEBOI\x10\xa6;b\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(PHAPALJNLBE::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
